# Data Immersion Task 6.1 - Sourcing Open Data

### Table of Contents

##### 1. Historical Monthly Inventory Zip data from Realtor.com
        A. Consistency Checks
        B. Data Cleaning
        C. Basic descriptive statistical analysis
##### 2. Zillow Observed Rent Index by ZIP code
        A. Consistency Checks
        B. Data Cleaning
        C. Basic descriptive statistical analysis
##### 3. Apartment List Vacancy Index
        A. Consistency Checks
        B. Data Cleaning
        C. Basic descriptive statistical analysis
##### 4. Apartment List Rent Estimates
        A. Consistency Checks
        B. Data Cleaning
        C. Basic descriptive statistical analysis
##### 5. Zip code list acquired from major protein company facility locations
        A. Consistency Checks
        B. Data Cleaning
        C. Basic descriptive statistical analysis
        D. Creating zip code list to be used for web scraper
##### 6. Realtor.com scraped homes for sale listings for zip codes in list
        A. Web scraping script
        B. Consistency Checks
        C. Data Cleaning
        D. Basic descriptive statistical analysis
##### 7. Realtor.com scraped rental listings for zip codes in list
        A. Web scraping script
        B. Consistency Checks
        C. Data Cleaning
        D. Basic descriptive statistical analysis

In [2]:
# Importing libraries

import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt
import scipy

In [3]:
# Defining path
path=r'D:\Adam\Employment\Data Analysis Course\Final Data Project'

## 1.Historical Monthly Inventory Zip data from Realtor.com

In [8]:
# Importing dataframe
df_rh = pd.read_csv(os.path.join(path, 'Data', 'Original', 'RDC_Inventory_Core_Metrics_Zip_History.csv'), index_col = False)

C:\Users\Madag\AppData\Local\Temp\ipykernel_19012\1421803694.py:2: DtypeWarning: Columns (0,1) have mixed types. Specify dtype option on import or set low_memory=False.
  df_rh = pd.read_csv(os.path.join(path, 'Data', 'RDC_Inventory_Core_Metrics_Zip_History.csv'), index_col = False)

### 1A. Consistency Checks

In [6]:
# checking dataset info
df_rh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2298453 entries, 0 to 2298452
Data columns (total 40 columns):
 #   Column                                   Dtype
---  ------                                   -----
 0   month_date_yyyymm                        object
 1   postal_code                              object
 2   zip_name                                 object
 3   median_listing_price                     float64
 4   median_listing_price_mm                  float64
 5   median_listing_price_yy                  float64
 6   active_listing_count                     float64
 7   active_listing_count_mm                  float64
 8   active_listing_count_yy                  float64
 9   median_days_on_market                    float64
 10  median_days_on_market_mm                 float64
 11  median_days_on_market_yy                 float64
 12  new_listing_count                        float64
 13  new_listing_count_mm                     float64
 14  new_listing_count_yy                     float64
 15  price_increased_count                    float64
 16  price_increased_count_mm                 float64
 17  price_increased_count_yy                 float64
 18  price_reduced_count                      float64
 19  price_reduced_count_mm                   float64
 20  price_reduced_count_yy                   float64
 21  pending_listing_count                    float64
 22  pending_listing_count_mm                 float64
 23  pending_listing_count_yy                 float64
 24  median_listing_price_per_square_foot     float64
 25  median_listing_price_per_square_foot_mm  float64
 26  median_listing_price_per_square_foot_yy  float64
 27  median_square_feet                       float64
 28  median_square_feet_mm                    float64
 29  median_square_feet_yy                    float64
 30  average_listing_price                    float64
 31  average_listing_price_mm                 float64
 32  average_listing_price_yy                 float64
 33  total_listing_count                      float64
 34  total_listing_count_mm                   float64
 35  total_listing_count_yy                   float64
 36  pending_ratio                            float64
 37  pending_ratio_mm                         float64
 38  pending_ratio_yy                         float64
 39  quality_flag                             float64
dtypes: float64(37), object(3)
memory usage: 701.4+ MB

### 1B. Data Cleaning

In [9]:
# Checking for duplicates (and removing them if there are any)

df_rh.drop_duplicates(inplace=True)

In [10]:
df_rh.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2298453 entries, 0 to 2298452
Data columns (total 40 columns):
 #   Column                                   Dtype
---  ------                                   -----
 0   month_date_yyyymm                        object
 1   postal_code                              object
 2   zip_name                                 object
 3   median_listing_price                     float64
 4   median_listing_price_mm                  float64
 5   median_listing_price_yy                  float64
 6   active_listing_count                     float64
 7   active_listing_count_mm                  float64
 8   active_listing_count_yy                  float64
 9   median_days_on_market                    float64
 10  median_days_on_market_mm                 float64
 11  median_days_on_market_yy                 float64
 12  new_listing_count                        float64
 13  new_listing_count_mm                     float64
 14  new_listing_count_yy                     float64
 15  price_increased_count                    float64
 16  price_increased_count_mm                 float64
 17  price_increased_count_yy                 float64
 18  price_reduced_count                      float64
 19  price_reduced_count_mm                   float64
 20  price_reduced_count_yy                   float64
 21  pending_listing_count                    float64
 22  pending_listing_count_mm                 float64
 23  pending_listing_count_yy                 float64
 24  median_listing_price_per_square_foot     float64
 25  median_listing_price_per_square_foot_mm  float64
 26  median_listing_price_per_square_foot_yy  float64
 27  median_square_feet                       float64
 28  median_square_feet_mm                    float64
 29  median_square_feet_yy                    float64
 30  average_listing_price                    float64
 31  average_listing_price_mm                 float64
 32  average_listing_price_yy                 float64
 33  total_listing_count                      float64
 34  total_listing_count_mm                   float64
 35  total_listing_count_yy                   float64
 36  pending_ratio                            float64
 37  pending_ratio_mm                         float64
 38  pending_ratio_yy                         float64
 39  quality_flag                             float64
dtypes: float64(37), object(3)
memory usage: 719.0+ MB

#### No duplicates were found

In [12]:
# Removing unneeded columns
# I'm removing all month-over-month values because I'm not interested in monthly changes in the housing market
# since housing is very seasonal. However, I'm leaving year-over-year values, because it can help predict
# larger trends of availability in the housing market. I'm also keeping all the variables that track number of homes,
# the cost of the homes (average & median), and the squarefeet, as well as price per square foot

df_rh_new = df_rh.drop(['active_listing_count_mm', 'median_listing_price_mm', 'median_days_on_market', 'median_days_on_market_mm', 'median_days_on_market_yy', 'new_listing_count_mm', 'price_increased_count', 'price_increased_count_mm', 'price_increased_count_yy', 'price_reduced_count', 'price_reduced_count_mm', 'price_reduced_count_yy', 'pending_listing_count', 'pending_listing_count_mm', 'pending_listing_count_yy', 'median_listing_price_per_square_foot_mm', 'median_square_feet_mm', 'average_listing_price_mm', 'total_listing_count_mm', 'pending_ratio', 'pending_ratio_mm', 'pending_ratio_yy'], axis=1)

In [13]:
df_rh_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2298453 entries, 0 to 2298452
Data columns (total 18 columns):
 #   Column                                   Dtype
---  ------                                   -----
 0   month_date_yyyymm                        object
 1   postal_code                              object
 2   zip_name                                 object
 3   median_listing_price                     float64
 4   median_listing_price_yy                  float64
 5   active_listing_count                     float64
 6   active_listing_count_yy                  float64
 7   new_listing_count                        float64
 8   new_listing_count_yy                     float64
 9   median_listing_price_per_square_foot     float64
 10  median_listing_price_per_square_foot_yy  float64
 11  median_square_feet                       float64
 12  median_square_feet_yy                    float64
 13  average_listing_price                    float64
 14  average_listing_price_yy                 float64
 15  total_listing_count                      float64
 16  total_listing_count_yy                   float64
 17  quality_flag                             float64
dtypes: float64(15), object(3)
memory usage: 397.7+ MB

In [18]:
# Checking for missing values
missing_values = df_rh_new.isnull().sum()

# total rows in dataframe
total_rows = df_rh_new.shape[0]

# calculating percentage of missing values
percent_missing = ((missing_values / total_rows) * 100).round(2)

# Making a dataframe to show missing values
missing_value_table = pd.concat([missing_values, percent_missing], axis=1)

# Naming columns for sorting
missing_value_table.columns = ['Missing Values', 'Percent Missing']

# sorting the view based on most missing values %
missing_value_table.sort_values('Percent Missing', ascending=True, inplace=True)

print(missing_value_table)

                                         Missing Values  Percent Missing
month_date_yyyymm                                     0             0.00
postal_code                                           0             0.00
total_listing_count                                3277             0.14
new_listing_count                                  3277             0.14
active_listing_count                               4728             0.21
median_listing_price                               6752             0.29
average_listing_price                              6752             0.29
median_square_feet                                26112             1.14
median_listing_price_per_square_foot              26357             1.15
zip_name                                          65838             2.86
quality_flag                                     348411            15.16
total_listing_count_yy                           448028            19.49
average_listing_price_yy                         464177            20.20
median_listing_price_yy                          464177            20.20
active_listing_count_yy                          475107            20.67
median_square_feet_yy                            482414            20.99
median_listing_price_per_square_foot_yy          482660            21.00
new_listing_count_yy                            1084797            47.20

Interestingly, I see that a whole lot of the year over year data is missing.
None of the postal codes are missing, which is helpful. But I can't guess why so much year-over-year data is missing.
Presumably it has something to do with some zip codes having less historical data. Maybe they weren't calculating the year-over-year for those zip codes.
I think, because I'm not sure if I'll use all that year-over-year data, I'll ignore the missing values for now.
If I find a good use case for that data, I may still be able to use it even if some zip codes don't have long-reaching historical data.

In [19]:
# Renaming one column

df_rh_new = df_rh_new.rename(columns={'zip_name': 'city state'})

### 1C. Basic descriptive statistical analysis

In [21]:
# counting number of unique values in each column

print(df_rh_new.nunique())

month_date_yyyymm                              83
postal_code                                 38373
city state                                  25728
median_listing_price                       204371
median_listing_price_yy                     55684
active_listing_count                         1232
active_listing_count_yy                     23369
new_listing_count                             191
new_listing_count_yy                         4329
median_listing_price_per_square_foot         2854
median_listing_price_per_square_foot_yy     46435
median_square_feet                           7856
median_square_feet_yy                       33256
average_listing_price                      739779
average_listing_price_yy                    56802
total_listing_count                          1414
total_listing_count_yy                      21477
quality_flag                                    2
dtype: int64

In [24]:
df_rh_new.describe().applymap(lambda x: f"{x:0.2f}")

,median_listing_price,median_listing_price_yy,active_listing_count,active_listing_count_yy,new_listing_count,new_listing_count_yy,median_listing_price_per_square_foot,median_listing_price_per_square_foot_yy,median_square_feet,median_square_feet_yy,average_listing_price,average_listing_price_yy,total_listing_count,total_listing_count_yy,quality_flag
count,2291701.00,1834276.00,2293725.00,1823346.00,2295176.00,1213656.00,2272096.00,1815793.00,2272341.00,1816039.00,2291701.00,1834276.00,2295176.00,1850425.00,1950042.00
mean,348570.43,13.92,33.12,0.05,14.60,-0.02,177.05,10.25,2006.73,0.09,424998.59,13.57,48.49,0.07,0.55
std,844241.55,2444.92,59.84,0.95,24.41,0.75,1271.31,1723.15,17252.76,13.77,984581.78,2436.91,81.80,1.06,0.50
min,1.00,-1.00,0.00,-1.00,0.00,-1.00,0.00,-1.00,1.00,-1.00,1.00,-1.00,0.00,-1.00,0.00
25%,142975.00,-0.08,3.00,-0.39,0.00,-0.44,86.00,-0.03,1498.00,-0.11,165062.00,-0.09,4.00,-0.30,0.00
50%,242000.00,0.07,11.00,-0.11,4.00,-0.06,129.00,0.07,1815.00,0.00,278533.00,0.06,16.00,-0.07,1.00
75%,395000.00,0.27,39.00,0.20,20.00,0.22,193.00,0.21,2234.00,0.12,463792.00,0.26,60.00,0.18,1.00
max,279000000.00,1789999.00,2646.00,233.00,802.00,39.00,795000.00,836107.24,12503400.00,8681.66,279000000.00,1789999.00,2860.00,274.00,1.00

#### All of the descriptive statistics seem to fall within expected ranges, particularly the quartiles for things like median listing price, square feet, listing price, etc

In [26]:
df_rh_new['month_date_yyyymm'].value_counts()

201709                                                       29313
201707                                                       29293
201809                                                       29291
201610                                                       29264
201608                                                       29261
                                                             ...
202203                                                       26734
202202                                                       26513
201607                                                       24683
201607                                                        4692
quality_flag = 1:  year-over-year figures may be impacted        1
Name: month_date_yyyymm, Length: 83, dtype: int64

In [27]:
# Removing the one totally unneccessary row

df_rh_new = df_rh_new[df_rh_new['month_date_yyyymm'] != 'quality_flag = 1:  year-over-year figures may be impacted']

In [28]:
df_rh_new['month_date_yyyymm'].value_counts()

201709    29313
201707    29293
201809    29291
201610    29264
201608    29261
          ...
202102    26845
202203    26734
202202    26513
201607    24683
201607     4692
Name: month_date_yyyymm, Length: 82, dtype: int64

In [31]:
# Exporting cleaned data

df_rh_new.to_csv(os.path.join(path, 'Data', 'Cleaned', 'Realtor_Historical_Zip_Inventory_ForSale.csv'), index=False)

## 2. Zillow Observed Rent Index by ZIP code

In [32]:
# Importing dataframe
df_zr = pd.read_csv(os.path.join(path, 'Data', 'Original', 'Zip_zori_sm_month.csv'), index_col = False)

### 2A. Consistency Checks

In [40]:
# checking dataset info

df_zr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6376 entries, 0 to 6375
Columns: 106 entries, RegionID to 2023-03-31
dtypes: float64(97), int64(3), object(6)
memory usage: 5.2+ MB

In [48]:
df_zr.head(10)

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,2015-03-31,2015-04-30,2015-05-31,2015-06-30,2015-07-31,2015-08-31,2015-09-30,2015-10-31,2015-11-30,2015-12-31,2016-01-31,2016-02-29,2016-03-31,2016-04-30,2016-05-31,2016-06-30,2016-07-31,2016-08-31,2016-09-30,2016-10-31,2016-11-30,2016-12-31,2017-01-31,2017-02-28,2017-03-31,2017-04-30,2017-05-31,2017-06-30,2017-07-31,2017-08-31,2017-09-30,2017-10-31,2017-11-30,2017-12-31,2018-01-31,2018-02-28,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,2018-08-31,2018-09-30,2018-10-31,2018-11-30,2018-12-31,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,2019-06-30,2019-07-31,2019-08-31,2019-09-30,2019-10-31,2019-11-30,2019-12-31,2020-01-31,2020-02-29,2020-03-31,2020-04-30,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2022-04-30,2022-05-31,2022-06-30,2022-07-31,2022-08-31,2022-09-30,2022-10-31,2022-11-30,2022-12-31,2023-01-31,2023-02-28,2023-03-31
0,91982,1,77494,zip,TX,TX,Katy,"Houston-The Woodlands-Sugar Land, TX",Fort Bend County,1497.424718,1499.248530,1511.190697,1518.373209,1524.778886,1534.467413,1525.972679,1513.825732,1496.067628,1484.176959,1477.602784,1469.893330,1469.266453,1465.506633,1460.697490,1464.839719,1463.348701,1463.308774,1451.153055,1440.484725,1414.325031,1403.325081,1401.745874,1422.660319,1436.056953,1452.028342,1457.738077,1465.455128,1456.703293,1446.772335,1444.602727,1455.723864,1471.962899,1478.867489,1485.714413,1490.908561,1490.231947,1486.949121,1484.584374,1491.146678,1492.230793,1488.545118,1470.569482,1467.520836,1468.130101,1479.471622,1480.837720,1484.407342,1489.211373,1492.102559,1496.527475,1501.177687,1505.780830,1515.566709,1506.300283,1510.691959,1499.980684,1505.795181,1495.972559,1498.902275,1502.508405,1514.348774,1507.873714,1506.337641,1504.307536,1513.752688,1527.794248,1524.872925,1537.864851,1534.983419,1542.192281,1533.228151,1535.895213,1558.783273,1594.669434,1648.675204,1694.636887,1731.006308,1744.970826,1758.066255,1775.214637,1781.542878,1776.812683,1779.581445,1784.772240,1805.412721,1820.739019,1842.220063,1868.047131,1873.817718,1878.928788,1858.462009,1840.580666,1837.859685,1866.420457,1878.317284,1879.541555
1,91940,2,77449,zip,TX,TX,Katy,"Houston-The Woodlands-Sugar Land, TX",Harris County,1277.132974,1290.552348,1297.324146,1310.568023,1319.342211,1328.941113,1325.851755,1324.083586,1323.559282,1325.397940,1320.378924,1316.058328,1319.733662,1327.915762,1333.973771,1327.529580,1321.263721,1321.523778,1321.007518,1325.192442,1316.672574,1309.092448,1299.634126,1303.065700,1313.825541,1322.124167,1325.332426,1324.231674,1331.204495,1332.155926,1344.550593,1342.235872,1349.215973,1345.989620,1356.093238,1361.766509,1367.501081,1371.292204,1375.634822,1384.091429,1389.244946,1393.950416,1388.586372,1384.673133,1385.688017,1383.849626,1376.778312,1372.473906,1377.052443,1383.838332,1390.497816,1396.109101,1406.476355,1405.774508,1408.497078,1403.872928,1402.392732,1397.623038,1402.252585,1407.792889,1417.250549,1419.855427,1406.522741,1407.013628,1410.859196,1435.006098,1439.897578,1444.169843,1454.399468,1476.262250,1487.010318,1491.236476,1501.682413,1519.444443,1568.593329,1608.079967,1663.924436,1675.820344,1686.698612,1682.038321,1687.457652,1695.160415,1698.073415,1720.708202,1738.002891,1750.625491,1744.870716,1751.848602,1802.897432,1844.663002,1839.843822,1817.949304,1784.282291,1780.857238,1772.767233,1782.596162,1792.935784
2,92593,4,78660,zip,TX,TX,Pflugerville,"Austin-Round Rock-Georgetown, TX",Travis County,1213.896723,1202.061542,1210.648750,1235.145033,1257.007757,1257.881811,1257.506468,1255.223144,1256.377940,1259.291195,1266.857438,1262.929548,NaN,1276.916177,1291.094497,1300.589664,1309.258325,1308.464719,1299.734453,1306.002029,1310.972730,1300.607528,1284.189301,1280.334085,1295.872435,1309.923928,1310.853327,1318.664933,1314.511684,1324.520001,1322.754487,1328.076910,1320.924809,1313.570585,1303.632042,1317.669723,1327.345552,1343.325990,1347.656499,1358.513485,1357.594438,1356.668627,1355.378540,1358.251351,1362.794213,1361.303731,1362.842623,1357.634069,1359.213324,1367.584804,1378.622480,1388.271416,1394.832913,1399.472838,1402.246878,1398.979755,1392.002211,1398.620300,1399.746265,1410.945804,1416.001456,1419.887578,1419.578231,1407.293023,1410.266391,1430.904864,1441.446165,1444.441106,1429.829386,1433.071054,1440.360359,1437.513873,1450.528819,1478.001050,1534.609844,1585.627305,1631.632943,NaN,1716.093367,1745.067127,1740.623827,1753.971036,1757.736583,1762.095083,1774.815096,1776.177778,1805.584129,1829.508574,1855.754040,1844.563025,1836.608744,1829.236068,1832.788915,1818.796956,1825.326246,1824.967456,1828.388042
3,62093,5,11385,zip,NY,NY,New York,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,2002.268262,2037.526224,2061.543907,2082.223290,2090.946531,2101.119163,2127.159394,2124.550233,2120.522267,2119.040449,2119.092187,2156.149319,2180.213141,2212.880008,2195.068840,2185.687996,2189.945202,2207.495780,2217.205063,2229.215506,2196.001381,2188.261579,2164.387386,2177.838793,2191.762129,2194.234774,2197.057057,2195.851515,2225.323260,2256.535411,2265.851461,2251.343189,2232.207050,2227.860084,2211.190543,2212.089833,2199.359855,2219.327416,2223.110451,2236.012802,2245.854843,2262.433113,2282.367337,2301.812405,2285.690402,2274.918462,2273.711925,2297.896204,2303.359826,2298.496611,2292.571896,2309.365078,2329.386519,2349.984191,2354.155218,2350.999494,2361.658657,2362.270450,2350.602492,2346.078132,2349.509720,2352.878880,2375.710817,2359.507560,2356.634053,2316.063959,2299.685891,2271.613823,2227.638376,2219.586462,2210.811419,2201.843389,2181.017894,2173.213028,2200.773561,2238.683011,2278.745160,2316.200824,2358.112678,2410.649920,2426.294188,2451.322199,2445.761932,2479.873594,2489.440934,2544.843223,2589.899639,2690.483038,2767.820061,2844.072074,2850.187383,2849.302473,2818.582220,2771.866885,2723.280995,2722.922736,2746.429739
4,93144,6,79936,zip,TX,TX,El Paso,"El Paso, TX",El Paso County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1132.474356,1135.498773,1140.499609,1145.384713,1179.258952,1216.892264,1215.499492,1233.988449,1230.355814,1252.408703,1265.835938,1254.378579,1262.539224,1273.463572,1319.020253,1352.624832,1364.329298,1341.859387,1352.863897,1360.447722,1397.850669,1414.703422,1412.378205
5,62019,7,11208,zip,NY,NY,New York,"New York-Newark-Jersey City, NY-NJ-PA",Kings County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2030.940908,2025.097436,1949.032972,1999.685305,2007.965498,2110.120608,2112.371382,2164.624200,2167.730603,2144.357726,2102.545288,2081.750948,2145.478402,2111.107917,2146.378433,2176.348498,2349.645808,2430.384194,2396.611870,2424.384161,2470.706539,2516.266950,2487.859244,2456.280551,2489.307247,2563.947896,2610.525206,2676.616409,2620.478358,2563.108333
6,95992,8,90011,zip,CA,CA,Los Angeles,"Los Angeles-Long Beach-Anaheim, CA",Los Angeles County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2405.565205,2355.519949,2428.117584,2451.329700,2519.001799,2539.021831,2501.664937,2513.533320,2463.372364,2515.000000
7,91733,9,77084,zip,TX,TX,Houston,"Houston-The Woodlands-Sugar Land, TX",Harris County,1233.641967,1244.075336,1247.713054,1254.876364,1259.601486,1270.391466,1276.234223,1271.331775,1265.734134,1261.182921,1262.469330,1265.067362,1264.973080,1267.502484,1266.446462,1257.095838,1261.365986,1267.677070,1273.270092,1268.341789,1261.121591,1262.989288,1262.565952,1256.035087,1257.852953,1264.966178,1276.345520,1281.561890,1285.075282,1287.668497,1307.381558,1323.800426,1338.370093,1323.963358,1314.530976,1307.837366,1305.776412,1315.449421,1320.412394,1332.744922,1324.810525,1332.027619,1350.403947,1352.831016,1360.323345,1341.403137,1345.967308,1328.688460,1340.097493,1348.519395,1374.659935,1374.870573,1379.988053,1372.430132,1370.333551,1364.991152,1364.554445,1367.731956,1365.790042,1374.852702,1382.178910,1394.477302,1393.408276,1396.069150,1395.075050,1398.666761,1405.830410,1404.734647,1407.847035,1409.717848,1420.190451,1428.472731,1435.355058,1450.284327,1470.039106,1503.411920,1549.867020,1600.297150,1650.683210,1647.014189,1645.690382,1646.895238,1666.982436,1675.483034,1661.685858,1668.536190,1684.548159,1719.482869,1742.866425,1727.629830,1710.984213,1695.807557,1709.414886,1701.107999,1700.951012,1694.641319,1712.270396
8,91926,10,77433,zip,TX,TX,Cypress,"Houston-The Woodlands-Sugar Land, TX",Harris County,1271.117945,1275.211973,1261.860826,1262.016176,1277.909648,1298.317110,1307.127937,1310.138559,1294.814174,1290.963166,1283.638030,1297.653204,1309.647767,1308.717502,1312.976293,1306.662112,1320.529641,1322.345581,1327.979332,1311.284587,1292.597219,1278.892625,1281.110115,1301.119041,1304.663159,1308.460275,1305.620214,1310.262601,1317.587642,1324.306140,1332.365748,1344.160547,1356.577275,1364.518387,1359.989701,1374.236887,1379.954356,1391.194625,1374.672072,1372.730616,1372.661370,1372.318824,1379.835119,1376.254080,1375.858065,1376.246811,1380.438751,1385.217597,1375.113366,1378.293585,1390.830751,1405.288417,1411.988846,1413.133151,1410.933394,1406.120132,1398.630794,1400.894480,1417.781026,1422.959677,1440.987031,1435.822648,1446.099193,1437.744322,1447.171931,1451.813395,1455.613663,1460.769998,1479.559194,1494.942613,1505.261530,1492.467617,1488.277120,1497.332756,1535.902039,1589.605508,1640.338707,1680.083689,1683.627711,1687.008185,1704.620010,1743.561824,1766.490613,1761.327204,1760.505734,1761.984858,1763.880680,1781.881801,1804.866395,1827.713655,1798.208562,1786.982792,1784.521263,1791.036310,1802.417200,1803.497801,1804.064127
9,84630,11,60629,zip,IL,IL,Chicago,"Chicago-Naperville-Elgin, IL-IN-WI",Cook County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,959.539515,954.803226,951.800956,956.730579,959.406923,968.090732,975.391790,997.122444,1005.856883,1026.783942,1008.533068,1011.548906,1015.097193,1052.609519,1073.280237,1091.769474,1060.861816,1064.324606,1053.516263,1075.694733,1093.260254,1104.233046,1109.350385,1104.877778,1111.897029,1140.708333

In [44]:
# figuring out the dtype for each column because there are too many of them

# making it show me all the rows
pd.options.display.max_rows = len(df_zr.dtypes)

print(df_zr.dtypes)

RegionID        int64
SizeRank        int64
RegionName      int64
RegionType     object
StateName      object
State          object
City           object
Metro          object
CountyName     object
2015-03-31    float64
2015-04-30    float64
2015-05-31    float64
2015-06-30    float64
2015-07-31    float64
2015-08-31    float64
2015-09-30    float64
2015-10-31    float64
2015-11-30    float64
2015-12-31    float64
2016-01-31    float64
2016-02-29    float64
2016-03-31    float64
2016-04-30    float64
2016-05-31    float64
2016-06-30    float64
2016-07-31    float64
2016-08-31    float64
2016-09-30    float64
2016-10-31    float64
2016-11-30    float64
2016-12-31    float64
2017-01-31    float64
2017-02-28    float64
2017-03-31    float64
2017-04-30    float64
2017-05-31    float64
2017-06-30    float64
2017-07-31    float64
2017-08-31    float64
2017-09-30    float64
2017-10-31    float64
2017-11-30    float64
2017-12-31    float64
2018-01-31    float64
2018-02-28    float64
2018-03-31    float64
2018-04-30    float64
2018-05-31    float64
2018-06-30    float64
2018-07-31    float64
2018-08-31    float64
2018-09-30    float64
2018-10-31    float64
2018-11-30    float64
2018-12-31    float64
2019-01-31    float64
2019-02-28    float64
2019-03-31    float64
2019-04-30    float64
2019-05-31    float64
2019-06-30    float64
2019-07-31    float64
2019-08-31    float64
2019-09-30    float64
2019-10-31    float64
2019-11-30    float64
2019-12-31    float64
2020-01-31    float64
2020-02-29    float64
2020-03-31    float64
2020-04-30    float64
2020-05-31    float64
2020-06-30    float64
2020-07-31    float64
2020-08-31    float64
2020-09-30    float64
2020-10-31    float64
2020-11-30    float64
2020-12-31    float64
2021-01-31    float64
2021-02-28    float64
2021-03-31    float64
2021-04-30    float64
2021-05-31    float64
2021-06-30    float64
2021-07-31    float64
2021-08-31    float64
2021-09-30    float64
2021-10-31    float64
2021-11-30    float64
2021-12-31    float64
2022-01-31    float64
2022-02-28    float64
2022-03-31    float64
2022-04-30    float64
2022-05-31    float64
2022-06-30    float64
2022-07-31    float64
2022-08-31    float64
2022-09-30    float64
2022-10-31    float64
2022-11-30    float64
2022-12-31    float64
2023-01-31    float64
2023-02-28    float64
2023-03-31    float64
dtype: object

All the datatypes look appropriate

In [49]:
# Checking for duplicates (and removing them if there are any)

df_zr.drop_duplicates(inplace=True)

In [50]:
df_zr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6376 entries, 0 to 6375
Columns: 106 entries, RegionID to 2023-03-31
dtypes: float64(97), int64(3), object(6)
memory usage: 5.2+ MB

Apparently there weren't any duplicates

In [51]:
# Checking for missing values
missing_values = df_zr.isnull().sum()

# total rows in dataframe
total_rows = df_zr.shape[0]

# calculating percentage of missing values
percent_missing = ((missing_values / total_rows) * 100).round(2)

# Making a dataframe to show missing values
missing_value_table = pd.concat([missing_values, percent_missing], axis=1)

# Naming columns for sorting
missing_value_table.columns = ['Missing Values', 'Percent Missing']

# sorting the view based on most missing values %
missing_value_table.sort_values('Percent Missing', ascending=True, inplace=True)

print(missing_value_table)

            Missing Values  Percent Missing
RegionID                 0             0.00
SizeRank                 0             0.00
RegionName               0             0.00
RegionType               0             0.00
StateName                0             0.00
State                    0             0.00
CountyName               0             0.00
2023-03-31               7             0.11
Metro                    8             0.13
City                    53             0.83
2023-02-28             903            14.16
2023-01-31            1198            18.79
2022-12-31            1557            24.42
2022-11-30            1697            26.62
2022-10-31            1789            28.06
2022-09-30            1903            29.85
2022-08-31            1950            30.58
2022-07-31            2012            31.56
2022-06-30            2076            32.56
2022-05-31            2161            33.89
2022-04-30            2278            35.73
2022-03-31            2363            37.06
2022-02-28            2538            39.81
2022-01-31            2673            41.92
2021-12-31            2877            45.12
2021-11-30            3019            47.35
2021-10-31            3105            48.70
2021-09-30            3199            50.17
2021-08-31            3249            50.96
2021-07-31            3283            51.49
2021-06-30            3290            51.60
2021-05-31            3325            52.15
2021-04-30            3360            52.70
2021-03-31            3399            53.31
2021-02-28            3560            55.83
2021-01-31            3634            56.99
2020-12-31            3748            58.78
2020-11-30            3801            59.61
2020-10-31            3832            60.10
2020-09-30            3861            60.56
2020-08-31            3867            60.65
2020-07-31            3872            60.73
2020-06-30            3878            60.82
2020-05-31            3879            60.84
2020-04-30            3897            61.12
2020-03-31            3905            61.25
2020-02-29            3910            61.32
2020-01-31            3919            61.46
2019-12-31            3931            61.65
2019-11-30            3946            61.89
2019-10-31            3951            61.97
2019-08-31            3952            61.98
2019-09-30            3956            62.05
2019-06-30            3957            62.06
2019-07-31            3959            62.09
2019-05-31            3960            62.11
2019-04-30            3964            62.17
2019-03-31            3969            62.25
2019-02-28            3996            62.67
2019-01-31            4008            62.86
2018-12-31            4062            63.71
2018-11-30            4094            64.21
2018-10-31            4098            64.27
2018-09-30            4107            64.41
2018-08-31            4112            64.49
2018-07-31            4117            64.57
2018-06-30            4125            64.70
2018-05-31            4126            64.71
2018-04-30            4141            64.95
2018-03-31            4156            65.18
2018-02-28            4185            65.64
2018-01-31            4203            65.92
2017-12-31            4287            67.24
2017-11-30            4306            67.53
2017-10-31            4326            67.85
2017-09-30            4346            68.16
2017-08-31            4349            68.21
2017-07-31            4357            68.33
2017-06-30            4374            68.60
2017-05-31            4385            68.77
2017-04-30            4409            69.15
2017-03-31            4428            69.45
2017-02-28            4451            69.81
2017-01-31            4456            69.89
2016-12-31            4555            71.44
2016-11-30            4599            72.13
2016-10-31            4627            72.57
2016-09-30            4659            73.07
2016-08-31            4665            73.16
2016-07-31            4681            73.42
2016-06-30            4694            73.62
2016-05-31            4748            74.47
2016-04-30            4954            77.70
2016-03-31            5020            78.73
2016-02-29            5048            79.17
2016-01-31            5097            79.94
2015-12-31            5153            80.82
2015-11-30            5183            81.29
2015-10-31            5203            81.60
2015-09-30            5206            81.65
2015-08-31            5219            81.85
2015-07-31            5223            81.92
2015-06-30            5234            82.09
2015-05-31            5242            82.21
2015-04-30            5259            82.48
2015-03-31            5280            82.81

So, the older the data, the more zip codes are missing, that makes sense. Though it's strange that even just one month before there were 15% less bits of data by zip code.  And apparently some zip codes are represented but without any data.  I wonder why.

In [53]:
# counting number of unique values in each column

print(df_zr.nunique())

RegionID      6376
SizeRank      6012
RegionName    6376
RegionType       1
StateName       52
State           52
City          2565
Metro          480
CountyName     671
2015-03-31    1096
2015-04-30    1117
2015-05-31    1134
2015-06-30    1142
2015-07-31    1153
2015-08-31    1157
2015-09-30    1170
2015-10-31    1173
2015-11-30    1193
2015-12-31    1223
2016-01-31    1279
2016-02-29    1328
2016-03-31    1356
2016-04-30    1422
2016-05-31    1628
2016-06-30    1682
2016-07-31    1695
2016-08-31    1711
2016-09-30    1717
2016-10-31    1749
2016-11-30    1777
2016-12-31    1821
2017-01-31    1920
2017-02-28    1925
2017-03-31    1948
2017-04-30    1967
2017-05-31    1991
2017-06-30    2002
2017-07-31    2019
2017-08-31    2027
2017-09-30    2030
2017-10-31    2050
2017-11-30    2070
2017-12-31    2089
2018-01-31    2173
2018-02-28    2191
2018-03-31    2220
2018-04-30    2235
2018-05-31    2250
2018-06-30    2251
2018-07-31    2259
2018-08-31    2264
2018-09-30    2269
2018-10-31    2278
2018-11-30    2282
2018-12-31    2314
2019-01-31    2368
2019-02-28    2380
2019-03-31    2407
2019-04-30    2412
2019-05-31    2416
2019-06-30    2419
2019-07-31    2417
2019-08-31    2424
2019-09-30    2420
2019-10-31    2425
2019-11-30    2430
2019-12-31    2445
2020-01-31    2457
2020-02-29    2466
2020-03-31    2471
2020-04-30    2479
2020-05-31    2497
2020-06-30    2498
2020-07-31    2504
2020-08-31    2509
2020-09-30    2515
2020-10-31    2544
2020-11-30    2575
2020-12-31    2628
2021-01-31    2742
2021-02-28    2816
2021-03-31    2977
2021-04-30    3016
2021-05-31    3051
2021-06-30    3086
2021-07-31    3093
2021-08-31    3127
2021-09-30    3177
2021-10-31    3271
2021-11-30    3357
2021-12-31    3499
2022-01-31    3703
2022-02-28    3838
2022-03-31    4013
2022-04-30    4098
2022-05-31    4215
2022-06-30    4300
2022-07-31    4364
2022-08-31    4426
2022-09-30    4473
2022-10-31    4587
2022-11-30    4679
2022-12-31    4819
2023-01-31    5178
2023-02-28    5473
2023-03-31    5862
dtype: int64

### 2B. Data Cleaning

In [54]:
# Removing unneeded columns. The State and StateName appear to be the exact same and have the same number of values.
# I don't need RegionType because I already know they're all zip codes.
# I manually checked on the internet and RegionName is the real zip code and RegionID must correspond to something
# else in Zillow's systems (but unneeded). I'm also not interested in SizeRank, though City, Metro, and CountyName might all
# come in handy.

df_zr_new = df_zr.drop(['RegionID', 'SizeRank', 'RegionType', 'StateName'], axis=1)

### 2C. Basic Descriptive Analysis

In [55]:
df_zr_new.describe().applymap(lambda x: f"{x:0.2f}")

,RegionName,2015-03-31,2015-04-30,2015-05-31,2015-06-30,2015-07-31,2015-08-31,2015-09-30,2015-10-31,2015-11-30,2015-12-31,2016-01-31,2016-02-29,2016-03-31,2016-04-30,2016-05-31,2016-06-30,2016-07-31,2016-08-31,2016-09-30,2016-10-31,2016-11-30,2016-12-31,2017-01-31,2017-02-28,2017-03-31,2017-04-30,2017-05-31,2017-06-30,2017-07-31,2017-08-31,2017-09-30,2017-10-31,2017-11-30,2017-12-31,2018-01-31,2018-02-28,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,2018-08-31,2018-09-30,2018-10-31,2018-11-30,2018-12-31,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,2019-06-30,2019-07-31,2019-08-31,2019-09-30,2019-10-31,2019-11-30,2019-12-31,2020-01-31,2020-02-29,2020-03-31,2020-04-30,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2022-04-30,2022-05-31,2022-06-30,2022-07-31,2022-08-31,2022-09-30,2022-10-31,2022-11-30,2022-12-31,2023-01-31,2023-02-28,2023-03-31
count,6376.00,1096.00,1117.00,1134.00,1142.00,1153.00,1157.00,1170.00,1173.00,1193.00,1223.00,1279.00,1328.00,1356.00,1422.00,1628.00,1682.00,1695.00,1711.00,1717.00,1749.00,1777.00,1821.00,1920.00,1925.00,1948.00,1967.00,1991.00,2002.00,2019.00,2027.00,2030.00,2050.00,2070.00,2089.00,2173.00,2191.00,2220.00,2235.00,2250.00,2251.00,2259.00,2264.00,2269.00,2278.00,2282.00,2314.00,2368.00,2380.00,2407.00,2412.00,2416.00,2419.00,2417.00,2424.00,2420.00,2425.00,2430.00,2445.00,2457.00,2466.00,2471.00,2479.00,2497.00,2498.00,2504.00,2509.00,2515.00,2544.00,2575.00,2628.00,2742.00,2816.00,2977.00,3016.00,3051.00,3086.00,3093.00,3127.00,3177.00,3271.00,3357.00,3499.00,3703.00,3838.00,4013.00,4098.00,4215.00,4300.00,4364.00,4426.00,4473.00,4587.00,4679.00,4819.00,5178.00,5473.00,6369.00
mean,53564.17,1406.11,1421.92,1433.23,1443.50,1487.17,1494.81,1497.54,1498.99,1499.07,1497.39,1503.34,1504.85,1514.40,1516.03,1512.22,1514.56,1524.21,1524.12,1525.78,1521.25,1517.65,1513.37,1521.05,1531.12,1541.24,1557.00,1568.74,1577.86,1583.52,1578.85,1598.89,1598.21,1593.67,1592.45,1594.12,1600.86,1609.04,1620.57,1632.56,1644.67,1652.56,1657.90,1657.85,1656.10,1656.83,1655.51,1655.45,1661.15,1670.74,1682.16,1693.81,1704.90,1714.12,1715.40,1716.18,1713.88,1712.21,1710.85,1713.95,1721.47,1731.30,1731.96,1727.85,1724.79,1729.38,1730.53,1728.44,1725.34,1723.49,1718.14,1715.26,1716.08,1717.69,1741.27,1770.10,1806.26,1839.18,1874.02,1896.99,1904.61,1914.06,1913.91,1919.48,1931.05,1943.00,1964.35,1987.75,2007.49,2025.84,2042.79,2038.08,2025.93,2016.88,2015.69,2018.28,2020.93,2060.61
std,30000.75,621.26,626.24,629.06,633.83,1099.52,1113.07,1105.14,1112.10,1117.50,1137.50,1146.12,1155.77,1159.49,1131.85,1050.02,1016.06,1006.66,992.70,997.48,981.02,994.02,1000.87,1023.71,1031.39,1021.12,1004.23,993.15,1005.40,1007.55,892.75,1093.47,1098.57,1103.49,1108.42,1076.37,1064.16,1011.10,1009.36,1017.71,1039.57,1064.48,1081.52,1084.59,1060.19,1052.92,1037.64,1018.90,1010.74,1006.60,1008.24,1010.24,1026.86,1014.37,985.31,963.95,963.53,973.86,978.02,975.95,966.75,987.63,1003.44,1008.56,996.54,1000.52,969.04,939.51,926.69,964.11,987.07,985.08,990.78,1021.36,1061.68,1103.91,1131.60,1128.94,1082.11,1019.52,998.21,1011.90,1008.54,1042.37,1078.87,1144.70,1201.83,1211.40,1212.74,1171.62,1280.24,1205.56,1183.49,1203.08,1247.51,1332.26,1395.12,2026.07
min,901.00,501.49,505.98,494.02,502.58,518.89,529.47,535.31,529.66,530.77,492.83,522.68,529.15,526.14,531.10,536.46,539.60,544.15,463.29,469.31,480.57,504.69,495.90,490.65,488.76,570.27,570.27,571.91,563.91,564.49,557.88,48.92,51.90,50.93,52.07,53.72,54.59,54.33,52.60,51.78,52.01,53.93,53.64,52.66,51.78,52.18,51.78,50.96,50.87,51.99,53.56,52.74,52.10,52.30,55.52,56.87,57.56,54.26,54.29,55.21,56.72,56.60,52.91,56.52,58.70,64.02,63.60,66.30,64.40,64.74,55.60,60.80,59.70,513.45,80.75,93.12,94.47,96.52,102.85,105.57,104.82,99.72,103.15,105.67,109.31,117.95,118.71,128.19,89.71,68.42,191.24,151.01,554.18,548.57,548.95,542.81,560.90,575.56
25%,29831.50,1011.69,1024.27,1032.42,1038.43,1048.16,1048.72,1052.93,1054.00,1052.79,1053.21,1061.69,1064.46,1070.52,1072.85,1075.37,1080.34,1087.92,1089.55,1095.32,1091.18,1091.15,1090.44,1098.13,1104.20,1109.23,1120.04,1128.35,1134.23,1139.19,1145.22,1144.53,1142.53,1140.31,1142.27,1147.25,1149.69,1160.47,1170.61,1180.05,1189.18,1194.45,1200.96,1201.25,1202.72,1203.89,1206.88,1205.09,1210.64,1221.89,1231.97,1240.29,1251.24,1261.00,1266.14,1265.85,1259.85,1260.83,1260.54,1263.58,1270.35,1278.97,1275.95,1280.12,1283.86,1290.56,1299.13,1300.25,1305.52,1302.24,1299.04,1299.15,1301.47,1300.74,1318.35,1339.63,1367.28,1390.68,1421.42,1437.95,1443.36,1450.90,1453.19,1451.88,1452.64,1454.02,1467.37,1483.14,1496.14,1513.76,1521.16,1518.48,1506.30,1494.62,1491.87,1479.73,1479.30,1457.94
50%,52243.00,1237.94,1254.38,1265.36,1270.22,1278.57,1281.37,1282.06,1287.23,1291.99,1292.42,1299.54,1303.35,1310.10,1317.96,1321.22,1324.10,1333.91,1333.88,1332.30,1332.95,1329.97,1328.58,1331.34,1340.82,1351.00,1365.37,1375.96,1386.45,1393.99,1393.85,1394.90,1397.25,1385.48,1388.91,1391.77,1404.98,1412.04,1427.07,1433.20,1445.48,1451.74,1457.82,1457.73,1455.41,1455.63,1454.12,1453.51,1462.15,1471.70,1482.88,1495.35,1501.86,1510.36,1512.58,1513.30,1510.48,1505.31,1505.80,1506.76,1515.63,1530.15,1525.56,1523.09,1521.03,1533.19,1544.85,1554.15,1558.93,1557.96,1556.93,1552.77,1558.50,1567.58,1586.69,1611.38,1645.94,1683.36,1721.10,1747.11,1759.17,1766.77,1768.00,1768.77,1779.78,1786.73,1805.27,1828.59,1849.99,1871.77,1874.93,1876.35,1867.10,1851.69,1844.18,1834.88,1837.59,1832.00
75%,80408.25,1618.88,1640.48,1644.39,1664.60,1673.64,1681.90,1689.47,1699.41,1695.97,1699.80,1708.17,1706.69,1720.11,1716.48,1716.26,1729.14,1749.24,1748.61,1744.31,1744.20,1735.44,1723.47,1726.27,1740.16,1748.59,1772.78,1785.47,1801.98,1809.33,1814.11,1824.76,1817.68,1820.86,1819.35,1826.24,1839.75,1845.78,1858.15,1866.67,1880.25,1890.46,1893.85,1889.37,1889.56,1897.57,1905.32,1903.07,1905.53,1915.95,1929.09,1943.80,1950.91,1961.20,1965.50,1963.43,1965.75,1958.37,1958.83,1965.55,1968.91,1980.93,1987.54,1978.23,1978.82,1981.34,1988.07,1983.92,1982.71,1973.04,1968.17,1961.55,1960.70,1963.82,1988.02,2018.54,2062.22,2105.42,2150.84,2180.47,2178.60,2188.97,2185.89,2195.82,2211.18,2219.37,2244.76,2280.46,2309.40,2325.56,2337.20,2340.09,2331.77,2319.54,2323.54,2325.24,2326.97,2330.35
max,99705.00,7744.95,7997.14,7865.72,7776.15,26328.55,26927.08,27099.91,27190.27,27439.20,28197.74,28935.92,29867.54,30286.53,29905.67,28706.11,27081.51,27175.40,27017.13,27909.09,27011.84,27653.35,28045.20,29507.09,29753.62,29574.25,29051.19,28578.78,29685.46,28968.65,28844.86,27323.89,27912.22,27709.96,26844.35,25804.61,25693.05,23599.48,23823.28,24842.35,25818.49,26734.04,27489.88,27901.34,26908.53,26739.87,26248.02,25274.47,24972.28,25239.66,25694.41,25791.83,26045.16,25678.64,24321.40,23796.18,23815.16,23611.85,23188.28,23127.80,22470.94,24030.76,24405.69,25637.12,24958.47,25649.22,24957.91,25431.83,25215.08,27510.07,28261.31,28871.46,29044.89,30894.55,32307.99,33403.67,33655.55,33143.63,32615.16,29813.37,30484.96,30949.32,31220.70,32140.38,32309.65,36556.25,40047.53,41363.23,39379.65,38425.40,38528.87,36731.99,34685.66,36121.00,39250.20,40354.97,45075.03,68750.00

All the descriptive stats seem within the expected range. Though apparently rent max in some zip code is CRAZY! I will have to see if that same zip code is within the area I'm intending to analyze

In [56]:
# Counting value counts in some of the "object" columns

df_zr_new['RegionName'].value_counts()

77494    1
31558    1
97333    1
34747    1
71446    1
        ..
64804    1
38118    1
32714    1
45373    1
12085    1
Name: RegionName, Length: 6376, dtype: int64

In [57]:
df_zr_new['State'].value_counts()

CA    834
FL    611
TX    589
NY    293
PA    225
IL    211
GA    207
WA    194
OH    190
NC    183
VA    178
AZ    173
MA    162
CO    156
NJ    155
MI    147
MD    132
MN    122
MO    121
TN    116
IN    114
WI     95
SC     89
OK     85
OR     82
AL     82
NV     73
LA     71
CT     69
KS     65
UT     65
KY     64
NE     46
AR     45
IA     45
ID     35
RI     29
NM     28
MS     25
HI     25
DC     21
NH     20
DE     16
SD     14
ND     13
MT     13
WV     12
ME     11
AK     10
WY     10
VT      3
PR      2
Name: State, dtype: int64

This seems to check out

In [58]:
df_zr_new['Metro'].value_counts()

New York-Newark-Jersey City, NY-NJ-PA    317
Los Angeles-Long Beach-Anaheim, CA       299
Chicago-Naperville-Elgin, IL-IN-WI       189
Dallas-Fort Worth-Arlington, TX          186
Houston-The Woodlands-Sugar Land, TX     164
                                        ...
Red Bluff, CA                              1
Midland, MI                                1
Fremont, NE                                1
Rolla, MO                                  1
Sioux City, IA-NE-SD                       1
Name: Metro, Length: 480, dtype: int64

This also seems to check out

In [59]:
# Exporting cleaned data

df_zr_new.to_csv(os.path.join(path, 'Data', 'Cleaned', 'Zillow_Historical_Zip_Rental_Rates.csv'), index=False)

## 3. Apartment List Vacancy Index

In [4]:
# Importing dataframe
df_av = pd.read_csv(os.path.join(path, 'Data', 'Original', 'Apartment_List_Vacancy_Index_2023_04.csv'), index_col = False)

### 3A. Consistency Checks

In [61]:
# checking dataset info

df_av.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 455 entries, 0 to 454
Data columns (total 83 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   location_name       455 non-null    object
 1   location_type       455 non-null    object
 2   location_fips_code  455 non-null    int64
 3   population          455 non-null    int64
 4   state               353 non-null    object
 5   county              311 non-null    object
 6   metro               412 non-null    object
 7   2017_01             439 non-null    float64
 8   2017_02             443 non-null    float64
 9   2017_03             444 non-null    float64
 10  2017_04             445 non-null    float64
 11  2017_05             447 non-null    float64
 12  2017_06             447 non-null    float64
 13  2017_07             447 non-null    float64
 14  2017_08             447 non-null    float64
 15  2017_09             447 non-null    float64
 16  2017_10             447 non-null    float64
 17  2017_11             448 non-null    float64
 18  2017_12             448 non-null    float64
 19  2018_01             448 non-null    float64
 20  2018_02             448 non-null    float64
 21  2018_03             448 non-null    float64
 22  2018_04             448 non-null    float64
 23  2018_05             448 non-null    float64
 24  2018_06             449 non-null    float64
 25  2018_07             455 non-null    float64
 26  2018_08             455 non-null    float64
 27  2018_09             455 non-null    float64
 28  2018_10             455 non-null    float64
 29  2018_11             455 non-null    float64
 30  2018_12             455 non-null    float64
 31  2019_01             455 non-null    float64
 32  2019_02             455 non-null    float64
 33  2019_03             455 non-null    float64
 34  2019_04             455 non-null    float64
 35  2019_05             455 non-null    float64
 36  2019_06             455 non-null    float64
 37  2019_07             455 non-null    float64
 38  2019_08             455 non-null    float64
 39  2019_09             455 non-null    float64
 40  2019_10             455 non-null    float64
 41  2019_11             455 non-null    float64
 42  2019_12             455 non-null    float64
 43  2020_01             455 non-null    float64
 44  2020_02             455 non-null    float64
 45  2020_03             455 non-null    float64
 46  2020_04             455 non-null    float64
 47  2020_05             455 non-null    float64
 48  2020_06             455 non-null    float64
 49  2020_07             455 non-null    float64
 50  2020_08             455 non-null    float64
 51  2020_09             455 non-null    float64
 52  2020_10             455 non-null    float64
 53  2020_11             455 non-null    float64
 54  2020_12             455 non-null    float64
 55  2021_01             455 non-null    float64
 56  2021_02             455 non-null    float64
 57  2021_03             455 non-null    float64
 58  2021_04             455 non-null    float64
 59  2021_05             455 non-null    float64
 60  2021_06             455 non-null    float64
 61  2021_07             455 non-null    float64
 62  2021_08             455 non-null    float64
 63  2021_09             455 non-null    float64
 64  2021_10             455 non-null    float64
 65  2021_11             455 non-null    float64
 66  2021_12             455 non-null    float64
 67  2022_01             455 non-null    float64
 68  2022_02             455 non-null    float64
 69  2022_03             455 non-null    float64
 70  2022_04             455 non-null    float64
 71  2022_05             455 non-null    float64
 72  2022_06             455 non-null    float64
 73  2022_07             455 non-null    float64
 74  2022_08             455 non-null    float64
 75  2022_09             455 non-null    float64
 76  2022_10             455 non-null    float64
 77  2022_11             455 non-null    float64
 78  2022_12             455 non-null    float64
 79  2023_01             455 non-null    float64
 80  2023_02             455 non-null    float64
 81  2023_03             455 non-null    float64
 82  2023_04             455 non-null    float64
dtypes: float64(76), int64(2), object(5)
memory usage: 295.2+ KB

all the dtypes look appropriate

In [5]:
# Checking for duplicates (and removing them if there are any) - then checking if the numbers change

df_av.drop_duplicates(inplace=True)

df_av.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 455 entries, 0 to 454
Data columns (total 83 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   location_name       455 non-null    object
 1   location_type       455 non-null    object
 2   location_fips_code  455 non-null    int64
 3   population          455 non-null    int64
 4   state               353 non-null    object
 5   county              311 non-null    object
 6   metro               412 non-null    object
 7   2017_01             439 non-null    float64
 8   2017_02             443 non-null    float64
 9   2017_03             444 non-null    float64
 10  2017_04             445 non-null    float64
 11  2017_05             447 non-null    float64
 12  2017_06             447 non-null    float64
 13  2017_07             447 non-null    float64
 14  2017_08             447 non-null    float64
 15  2017_09             447 non-null    float64
 16  2017_10             447 non-null    float64
 17  2017_11             448 non-null    float64
 18  2017_12             448 non-null    float64
 19  2018_01             448 non-null    float64
 20  2018_02             448 non-null    float64
 21  2018_03             448 non-null    float64
 22  2018_04             448 non-null    float64
 23  2018_05             448 non-null    float64
 24  2018_06             449 non-null    float64
 25  2018_07             455 non-null    float64
 26  2018_08             455 non-null    float64
 27  2018_09             455 non-null    float64
 28  2018_10             455 non-null    float64
 29  2018_11             455 non-null    float64
 30  2018_12             455 non-null    float64
 31  2019_01             455 non-null    float64
 32  2019_02             455 non-null    float64
 33  2019_03             455 non-null    float64
 34  2019_04             455 non-null    float64
 35  2019_05             455 non-null    float64
 36  2019_06             455 non-null    float64
 37  2019_07             455 non-null    float64
 38  2019_08             455 non-null    float64
 39  2019_09             455 non-null    float64
 40  2019_10             455 non-null    float64
 41  2019_11             455 non-null    float64
 42  2019_12             455 non-null    float64
 43  2020_01             455 non-null    float64
 44  2020_02             455 non-null    float64
 45  2020_03             455 non-null    float64
 46  2020_04             455 non-null    float64
 47  2020_05             455 non-null    float64
 48  2020_06             455 non-null    float64
 49  2020_07             455 non-null    float64
 50  2020_08             455 non-null    float64
 51  2020_09             455 non-null    float64
 52  2020_10             455 non-null    float64
 53  2020_11             455 non-null    float64
 54  2020_12             455 non-null    float64
 55  2021_01             455 non-null    float64
 56  2021_02             455 non-null    float64
 57  2021_03             455 non-null    float64
 58  2021_04             455 non-null    float64
 59  2021_05             455 non-null    float64
 60  2021_06             455 non-null    float64
 61  2021_07             455 non-null    float64
 62  2021_08             455 non-null    float64
 63  2021_09             455 non-null    float64
 64  2021_10             455 non-null    float64
 65  2021_11             455 non-null    float64
 66  2021_12             455 non-null    float64
 67  2022_01             455 non-null    float64
 68  2022_02             455 non-null    float64
 69  2022_03             455 non-null    float64
 70  2022_04             455 non-null    float64
 71  2022_05             455 non-null    float64
 72  2022_06             455 non-null    float64
 73  2022_07             455 non-null    float64
 74  2022_08             455 non-null    float64
 75  2022_09             455 non-null    float64
 76  2022_10             455 non-null    float64
 77  2022_11             455 non-null    float64
 78  2022_12             455 non-null    float64
 79  2023_01             455 non-null    float64
 80  2023_02             455 non-null    float64
 81  2023_03             455 non-null    float64
 82  2023_04             455 non-null    float64
dtypes: float64(76), int64(2), object(5)
memory usage: 298.6+ KB

Nothing changed, there were no duplicates

In [7]:
# Checking for missing values
missing_values = df_av.isnull().sum()

# total rows in dataframe
total_rows = df_av.shape[0]

# making it show me all the rows
pd.options.display.max_rows = len(df_av.dtypes)

# calculating percentage of missing values
percent_missing = ((missing_values / total_rows) * 100).round(2)

# Making a dataframe to show missing values
missing_value_table = pd.concat([missing_values, percent_missing], axis=1)

# Naming columns for sorting
missing_value_table.columns = ['Missing Values', 'Percent Missing']

# sorting the view based on most missing values %
missing_value_table.sort_values('Percent Missing', ascending=True, inplace=True)

print(missing_value_table)

                    Missing Values  Percent Missing
location_name                    0             0.00
2021_05                          0             0.00
2021_04                          0             0.00
2021_03                          0             0.00
2021_02                          0             0.00
2021_01                          0             0.00
2020_12                          0             0.00
2020_11                          0             0.00
2020_10                          0             0.00
2020_09                          0             0.00
2020_08                          0             0.00
2020_07                          0             0.00
2020_06                          0             0.00
2020_05                          0             0.00
2020_04                          0             0.00
2020_03                          0             0.00
2020_02                          0             0.00
2020_01                          0             0.00
2021_06                          0             0.00
2019_12                          0             0.00
2021_07                          0             0.00
2021_09                          0             0.00
2023_02                          0             0.00
2023_01                          0             0.00
2022_12                          0             0.00
2022_11                          0             0.00
2022_10                          0             0.00
2022_09                          0             0.00
2022_08                          0             0.00
2022_07                          0             0.00
2022_06                          0             0.00
2022_05                          0             0.00
2022_04                          0             0.00
2022_03                          0             0.00
2022_02                          0             0.00
2022_01                          0             0.00
2021_12                          0             0.00
2021_11                          0             0.00
2021_10                          0             0.00
2021_08                          0             0.00
2023_03                          0             0.00
2019_11                          0             0.00
2019_09                          0             0.00
location_type                    0             0.00
location_fips_code               0             0.00
population                       0             0.00
2019_10                          0             0.00
2018_07                          0             0.00
2018_08                          0             0.00
2018_09                          0             0.00
2018_10                          0             0.00
2018_11                          0             0.00
2023_04                          0             0.00
2019_01                          0             0.00
2019_02                          0             0.00
2019_03                          0             0.00
2019_04                          0             0.00
2019_08                          0             0.00
2019_07                          0             0.00
2019_06                          0             0.00
2018_12                          0             0.00
2019_05                          0             0.00
2018_06                          6             1.32
2017_11                          7             1.54
2018_01                          7             1.54
2018_05                          7             1.54
2018_02                          7             1.54
2018_04                          7             1.54
2018_03                          7             1.54
2017_12                          7             1.54
2017_10                          8             1.76
2017_08                          8             1.76
2017_05                          8             1.76
2017_06                          8             1.76
2017_07                          8             1.76
2017_09                          8             1.76
2017_04                         10             2.20
2017_03                         11             2.42
2017_02                         12             2.64
2017_01                         16             3.52
metro                           43             9.45
state                          102            22.42
county                         144            31.65

So the historicity of the data is good. Lots of counties not mentioned, quite a few states not mentioned. But most mention metro.  I'll just have to see how many of my food production facility zip codes this matches up with to see if it's worth using or not.  My guess is that it'll give extra data consideration for some but not for most.

In [8]:
# counting number of unique values in each column

print(df_av.nunique())

location_name         455
location_type           5
location_fips_code    455
population            429
state                  42
county                157
metro                 193
2017_01               386
2017_02               389
2017_03               390
2017_04               392
2017_05               395
2017_06               397
2017_07               398
2017_08               399
2017_09               398
2017_10               399
2017_11               399
2017_12               405
2018_01               405
2018_02               403
2018_03               408
2018_04               407
2018_05               408
2018_06               408
2018_07               413
2018_08               411
2018_09               410
2018_10               416
2018_11               416
2018_12               417
2019_01               421
2019_02               418
2019_03               417
2019_04               418
2019_05               419
2019_06               421
2019_07               420
2019_08               422
2019_09               422
2019_10               425
2019_11               427
2019_12               425
2020_01               424
2020_02               421
2020_03               424
2020_04               423
2020_05               427
2020_06               423
2020_07               423
2020_08               422
2020_09               423
2020_10               423
2020_11               423
2020_12               422
2021_01               423
2021_02               423
2021_03               427
2021_04               426
2021_05               424
2021_06               423
2021_07               422
2021_08               424
2021_09               423
2021_10               422
2021_11               423
2021_12               425
2022_01               425
2022_02               422
2022_03               423
2022_04               423
2022_05               422
2022_06               426
2022_07               423
2022_08               424
2022_09               424
2022_10               425
2022_11               424
2022_12               426
2023_01               426
2023_02               426
2023_03               428
2023_04               427
dtype: int64

that all seems about right

### 3B. Data Cleaning

In [10]:
# Removing unneeded columns. I don't need the "location_fips_code" since it doesn't seem to correspond to anything recognizable
# that I might need. Similarly I don't need "population", but it's possible I'll find use for state, county, and metro
# to use for linking with my zip codes (since there are no zip codes here)

df_av_new = df_av.drop(['location_fips_code', 'population'], axis=1)

### 3C. Basic Descriptive Analysis

In [11]:
# Checking basic stats on each column

df_av_new.describe().applymap(lambda x: f"{x:0.2f}")

,2017_01,2017_02,2017_03,2017_04,2017_05,2017_06,2017_07,2017_08,2017_09,2017_10,...,2022_07,2022_08,2022_09,2022_10,2022_11,2022_12,2023_01,2023_02,2023_03,2023_04
count,439.00,443.00,444.00,445.00,447.00,447.00,447.00,447.00,447.00,447.00,...,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00
mean,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,...,0.05,0.05,0.05,0.05,0.06,0.06,0.06,0.06,0.07,0.07
std,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.02,0.02,...,0.02,0.01,0.01,0.01,0.01,0.01,0.01,0.02,0.02,0.02
min,0.00,0.00,0.01,0.01,0.01,0.01,0.02,0.02,0.02,0.02,...,0.01,0.01,0.01,0.02,0.02,0.02,0.02,0.02,0.03,0.03
25%,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.06,0.06,0.06,...,0.04,0.04,0.04,0.05,0.05,0.05,0.05,0.05,0.05,0.06
50%,0.06,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,...,0.05,0.05,0.05,0.05,0.06,0.06,0.06,0.06,0.06,0.07
75%,0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.08,...,0.06,0.06,0.06,0.06,0.06,0.07,0.07,0.07,0.07,0.08
max,0.20,0.20,0.21,0.23,0.26,0.28,0.30,0.29,0.27,0.26,...,0.13,0.13,0.14,0.14,0.13,0.13,0.13,0.13,0.13,0.13

That's about what I'd expect. Since it's percentage of inventory, all the numbers are between 0 and 1, but most of the time inventory percentage available is much lower

In [12]:
# Counting value counts in some of the "object" columns

df_av_new['location_name'].value_counts()

United States                1
Huntsville, AL Metro Area    1
Cleveland, OH                1
Savannah, GA Metro Area      1
Placer County, CA            1
                            ..
Milwaukee County, WI         1
Marion County, IN            1
Austin, TX                   1
Westchester County, NY       1
Katy, TX                     1
Name: location_name, Length: 455, dtype: int64

In [13]:
df_av_new['location_type'].value_counts()

County      166
City        145
Metro       101
State        42
National      1
Name: location_type, dtype: int64

In [14]:
df_av_new['state'].value_counts()

Texas                   38
California              32
Florida                 20
Virginia                16
North Carolina          15
Colorado                15
Washington              15
Georgia                 13
Tennessee               11
New Jersey              11
Arizona                 11
Maryland                11
North Dakota             9
Pennsylvania             9
South Carolina           9
Minnesota                8
Massachusetts            8
Oregon                   7
Michigan                 7
Ohio                     7
Nebraska                 6
Nevada                   6
Missouri                 6
New York                 5
Oklahoma                 5
Kentucky                 5
Wisconsin                5
Louisiana                4
Connecticut              4
Alabama                  4
Illinois                 4
New Mexico               3
South Dakota             3
Indiana                  3
Utah                     3
Kansas                   3
Arkansas                 3
Iowa                     3
District of Columbia     3
Mississippi              1
Idaho                    1
New Hampshire            1
Name: state, dtype: int64

In [15]:
df_av_new['county'].value_counts()

Maricopa County       8
King County           7
Los Angeles County    6
Dallas County         6
Montgomery County     6
                     ..
Chester County        1
Fairfield County      1
Volusia County        1
Bergen County         1
Burlington County     1
Name: county, Length: 157, dtype: int64

In [16]:
df_av_new['metro'].value_counts()

Dallas-Fort Worth-Arlington, TX                 17
Washington-Arlington-Alexandria, DC-VA-MD-WV    13
Seattle-Tacoma-Bellevue, WA                     11
New York-Newark-Jersey City, NY-NJ-PA           11
Houston-The Woodlands-Sugar Land, TX             9
                                                ..
Tucson, AZ Metro Area                            1
Tulsa, OK Metro Area                             1
Bridgeport-Stamford-Norwalk, CT Metro Area       1
Bridgeport-Stamford-Norwalk, CT                  1
Knoxville, TN Metro Area                         1
Name: metro, Length: 193, dtype: int64

I'd say that all of this is about what I'd expect.  So overall very clean, but possibly limited data. Hopefully I'll find enough of it that I can use.

In [17]:
# Exporting cleaned data

df_av_new.to_csv(os.path.join(path, 'Data', 'Cleaned', 'Apartment_List_Vacancy_Index.csv'), index=False)

## 4. Apartment List Rent Estimates

In [18]:
# Importing dataframe
df_ar = pd.read_csv(os.path.join(path, 'Data', 'Original', 'Apartment_List_Rent_Estimates_2023_04.csv'), index_col = False)

### 4A. Consistency Checks

In [19]:
# checking dataset info

df_ar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3378 entries, 0 to 3377
Data columns (total 84 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   location_name       3378 non-null   object
 1   location_type       3378 non-null   object
 2   location_fips_code  3378 non-null   int64
 3   population          3378 non-null   int64
 4   state               2835 non-null   object
 5   county              2694 non-null   object
 6   metro               3234 non-null   object
 7   bed_size            3378 non-null   object
 8   2017_01             3108 non-null   float64
 9   2017_02             3126 non-null   float64
 10  2017_03             3165 non-null   float64
 11  2017_04             3183 non-null   float64
 12  2017_05             3207 non-null   float64
 13  2017_06             3237 non-null   float64
 14  2017_07             3234 non-null   float64
 15  2017_08             3231 non-null   float64
 16  2017_09             3243 non-null   float64
 17  2017_10             3243 non-null   float64
 18  2017_11             3291 non-null   float64
 19  2017_12             3285 non-null   float64
 20  2018_01             3312 non-null   float64
 21  2018_02             3318 non-null   float64
 22  2018_03             3327 non-null   float64
 23  2018_04             3321 non-null   float64
 24  2018_05             3321 non-null   float64
 25  2018_06             3318 non-null   float64
 26  2018_07             3318 non-null   float64
 27  2018_08             3318 non-null   float64
 28  2018_09             3315 non-null   float64
 29  2018_10             3339 non-null   float64
 30  2018_11             3348 non-null   float64
 31  2018_12             3345 non-null   float64
 32  2019_01             3357 non-null   float64
 33  2019_02             3357 non-null   float64
 34  2019_03             3354 non-null   float64
 35  2019_04             3372 non-null   float64
 36  2019_05             3375 non-null   float64
 37  2019_06             3378 non-null   int64
 38  2019_07             3378 non-null   int64
 39  2019_08             3378 non-null   int64
 40  2019_09             3369 non-null   float64
 41  2019_10             3378 non-null   int64
 42  2019_11             3378 non-null   int64
 43  2019_12             3372 non-null   float64
 44  2020_01             3378 non-null   int64
 45  2020_02             3378 non-null   int64
 46  2020_03             3378 non-null   int64
 47  2020_04             3378 non-null   int64
 48  2020_05             3378 non-null   int64
 49  2020_06             3378 non-null   int64
 50  2020_07             3378 non-null   int64
 51  2020_08             3378 non-null   int64
 52  2020_09             3378 non-null   int64
 53  2020_10             3378 non-null   int64
 54  2020_11             3378 non-null   int64
 55  2020_12             3378 non-null   int64
 56  2021_01             3378 non-null   int64
 57  2021_02             3378 non-null   int64
 58  2021_03             3378 non-null   int64
 59  2021_04             3378 non-null   int64
 60  2021_05             3378 non-null   int64
 61  2021_06             3378 non-null   int64
 62  2021_07             3378 non-null   int64
 63  2021_08             3378 non-null   int64
 64  2021_09             3378 non-null   int64
 65  2021_10             3378 non-null   int64
 66  2021_11             3378 non-null   int64
 67  2021_12             3378 non-null   int64
 68  2022_01             3378 non-null   int64
 69  2022_02             3378 non-null   int64
 70  2022_03             3378 non-null   int64
 71  2022_04             3378 non-null   int64
 72  2022_05             3378 non-null   int64
 73  2022_06             3378 non-null   int64
 74  2022_07             3378 non-null   int64
 75  2022_08             3378 non-null   int64
 76  2022_09             3378 non-null   int64
 77  2022_10             3378 non-null   int64
 78  2022_11             3378 non-null   int64
 79  2022_12             3378 non-null   int64
 80  2023_01             3378 non-null   int64
 81  2023_02             3378 non-null   int64
 82  2023_03             3378 non-null   int64
 83  2023_04             3378 non-null   int64
dtypes: float64(31), int64(47), object(6)
memory usage: 2.2+ MB

it's interesting that some of the rent estimates for the different dates are either int64 or float64. I'll change it to make it consistent with the same info as in the apartment vacancies one

In [20]:
# changing the date columns that are int64 to float64 so that they can be consistent

df_ar = df_ar.astype({'2019_06': 'float64', '2019_07': 'float64', '2019_08': 'float64', '2019_10': 'float64', '2019_11': 'float64', '2020_01': 'float64', '2020_02': 'float64', '2020_03': 'float64', '2020_04': 'float64', '2020_05': 'float64', '2020_06': 'float64', '2020_07': 'float64', '2020_08': 'float64', '2020_09': 'float64', '2020_10': 'float64', '2020_11': 'float64', '2020_12': 'float64', '2021_01': 'float64', '2021_02': 'float64', '2021_03': 'float64', '2021_04': 'float64', '2021_05': 'float64', '2021_06': 'float64', '2021_07': 'float64', '2021_08': 'float64', '2021_09': 'float64', '2021_10': 'float64', '2021_11': 'float64', '2021_12': 'float64', '2022_01': 'float64','2022_02': 'float64', '2022_03': 'float64', '2022_04': 'float64', '2022_05': 'float64', '2022_06': 'float64', '2022_07': 'float64', '2022_08': 'float64', '2022_09': 'float64', '2022_10': 'float64', '2022_11': 'float64', '2022_12': 'float64', '2023_01': 'float64', '2023_02': 'float64', '2023_03': 'float64', '2023_04': 'float64'})

In [23]:
# Checking for duplicates (and removing them if there are any) - then checking if the numbers change

df_ar.drop_duplicates(inplace=True)

df_ar.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3378 entries, 0 to 3377
Data columns (total 84 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   location_name       3378 non-null   object
 1   location_type       3378 non-null   object
 2   location_fips_code  3378 non-null   int64
 3   population          3378 non-null   int64
 4   state               2835 non-null   object
 5   county              2694 non-null   object
 6   metro               3234 non-null   object
 7   bed_size            3378 non-null   object
 8   2017_01             3108 non-null   float64
 9   2017_02             3126 non-null   float64
 10  2017_03             3165 non-null   float64
 11  2017_04             3183 non-null   float64
 12  2017_05             3207 non-null   float64
 13  2017_06             3237 non-null   float64
 14  2017_07             3234 non-null   float64
 15  2017_08             3231 non-null   float64
 16  2017_09             3243 non-null   float64
 17  2017_10             3243 non-null   float64
 18  2017_11             3291 non-null   float64
 19  2017_12             3285 non-null   float64
 20  2018_01             3312 non-null   float64
 21  2018_02             3318 non-null   float64
 22  2018_03             3327 non-null   float64
 23  2018_04             3321 non-null   float64
 24  2018_05             3321 non-null   float64
 25  2018_06             3318 non-null   float64
 26  2018_07             3318 non-null   float64
 27  2018_08             3318 non-null   float64
 28  2018_09             3315 non-null   float64
 29  2018_10             3339 non-null   float64
 30  2018_11             3348 non-null   float64
 31  2018_12             3345 non-null   float64
 32  2019_01             3357 non-null   float64
 33  2019_02             3357 non-null   float64
 34  2019_03             3354 non-null   float64
 35  2019_04             3372 non-null   float64
 36  2019_05             3375 non-null   float64
 37  2019_06             3378 non-null   float64
 38  2019_07             3378 non-null   float64
 39  2019_08             3378 non-null   float64
 40  2019_09             3369 non-null   float64
 41  2019_10             3378 non-null   float64
 42  2019_11             3378 non-null   float64
 43  2019_12             3372 non-null   float64
 44  2020_01             3378 non-null   float64
 45  2020_02             3378 non-null   float64
 46  2020_03             3378 non-null   float64
 47  2020_04             3378 non-null   float64
 48  2020_05             3378 non-null   float64
 49  2020_06             3378 non-null   float64
 50  2020_07             3378 non-null   float64
 51  2020_08             3378 non-null   float64
 52  2020_09             3378 non-null   float64
 53  2020_10             3378 non-null   float64
 54  2020_11             3378 non-null   float64
 55  2020_12             3378 non-null   float64
 56  2021_01             3378 non-null   float64
 57  2021_02             3378 non-null   float64
 58  2021_03             3378 non-null   float64
 59  2021_04             3378 non-null   float64
 60  2021_05             3378 non-null   float64
 61  2021_06             3378 non-null   float64
 62  2021_07             3378 non-null   float64
 63  2021_08             3378 non-null   float64
 64  2021_09             3378 non-null   float64
 65  2021_10             3378 non-null   float64
 66  2021_11             3378 non-null   float64
 67  2021_12             3378 non-null   float64
 68  2022_01             3378 non-null   float64
 69  2022_02             3378 non-null   float64
 70  2022_03             3378 non-null   float64
 71  2022_04             3378 non-null   float64
 72  2022_05             3378 non-null   float64
 73  2022_06             3378 non-null   float64
 74  2022_07             3378 non-null   float64
 75  2022_08             3378 non-null   float64
 76  2022_09             3378 non-null   float64
 77  2022_10             3378 non-null   float64
 78  2022_11             3378 non-null   float64
 79  2022_12             3378 non-null   float64
 80  2023_01             3378 non-null   float64
 81  2023_02             3378 non-null   float64
 82  2023_03             3378 non-null   float64
 83  2023_04             3378 non-null   float64
dtypes: float64(76), int64(2), object(6)
memory usage: 2.2+ MB

no duplicates

In [25]:
# Checking for missing values
missing_values = df_ar.isnull().sum()

# total rows in dataframe
total_rows = df_ar.shape[0]

# making it show me all the rows
pd.options.display.max_rows = len(df_ar.dtypes)

# calculating percentage of missing values
percent_missing = ((missing_values / total_rows) * 100).round(2)

# Making a dataframe to show missing values
missing_value_table = pd.concat([missing_values, percent_missing], axis=1)

# Naming columns for sorting
missing_value_table.columns = ['Missing Values', 'Percent Missing']

# sorting the view based on most missing values %
missing_value_table.sort_values('Percent Missing', ascending=True, inplace=True)

print(missing_value_table)

                    Missing Values  Percent Missing
location_name                    0             0.00
2021_05                          0             0.00
2021_04                          0             0.00
2021_03                          0             0.00
2021_02                          0             0.00
2021_01                          0             0.00
2020_12                          0             0.00
2020_11                          0             0.00
2020_10                          0             0.00
2020_09                          0             0.00
2020_08                          0             0.00
2020_07                          0             0.00
2020_06                          0             0.00
2020_05                          0             0.00
2020_04                          0             0.00
2020_03                          0             0.00
2020_02                          0             0.00
2020_01                          0             0.00
2021_06                          0             0.00
2019_11                          0             0.00
2021_07                          0             0.00
2021_09                          0             0.00
2023_02                          0             0.00
2023_01                          0             0.00
2022_12                          0             0.00
2022_11                          0             0.00
2022_10                          0             0.00
2022_09                          0             0.00
2022_08                          0             0.00
2022_07                          0             0.00
2022_06                          0             0.00
2022_05                          0             0.00
2022_04                          0             0.00
2022_03                          0             0.00
2022_02                          0             0.00
2022_01                          0             0.00
2021_12                          0             0.00
2021_11                          0             0.00
2021_10                          0             0.00
2021_08                          0             0.00
2023_03                          0             0.00
2019_10                          0             0.00
2019_08                          0             0.00
location_type                    0             0.00
location_fips_code               0             0.00
population                       0             0.00
bed_size                         0             0.00
2023_04                          0             0.00
2019_07                          0             0.00
2019_06                          0             0.00
2019_05                          3             0.09
2019_04                          6             0.18
2019_12                          6             0.18
2019_09                          9             0.27
2019_02                         21             0.62
2019_01                         21             0.62
2019_03                         24             0.71
2018_11                         30             0.89
2018_12                         33             0.98
2018_10                         39             1.15
2018_03                         51             1.51
2018_05                         57             1.69
2018_04                         57             1.69
2018_08                         60             1.78
2018_02                         60             1.78
2018_07                         60             1.78
2018_06                         60             1.78
2018_09                         63             1.87
2018_01                         66             1.95
2017_11                         87             2.58
2017_12                         93             2.75
2017_09                        135             4.00
2017_10                        135             4.00
2017_06                        141             4.17
metro                          144             4.26
2017_07                        144             4.26
2017_08                        147             4.35
2017_05                        171             5.06
2017_04                        195             5.77
2017_03                        213             6.31
2017_02                        252             7.46
2017_01                        270             7.99
state                          543            16.07
county                         684            20.25

I'd say this was expected. Older dates have less info. Metro state and county have much less missing info than the vacancy dataset, but otherwise similar trends.

In [26]:
# counting number of unique values in each column

print(df_ar.nunique())

location_name         1067
location_type            5
location_fips_code    1126
population            1066
state                   47
county                 299
metro                  181
bed_size                 3
2017_01               1178
2017_02               1213
2017_03               1215
2017_04               1207
2017_05               1219
2017_06               1244
2017_07               1220
2017_08               1216
2017_09               1223
2017_10               1206
2017_11               1220
2017_12               1203
2018_01               1204
2018_02               1226
2018_03               1214
2018_04               1242
2018_05               1235
2018_06               1235
2018_07               1252
2018_08               1252
2018_09               1251
2018_10               1248
2018_11               1254
2018_12               1235
2019_01               1241
2019_02               1264
2019_03               1262
2019_04               1236
2019_05               1255
2019_06               1259
2019_07               1295
2019_08               1272
2019_09               1277
2019_10               1264
2019_11               1266
2019_12               1267
2020_01               1245
2020_02               1278
2020_03               1268
2020_04               1278
2020_05               1247
2020_06               1214
2020_07               1246
2020_08               1229
2020_09               1222
2020_10               1221
2020_11               1225
2020_12               1229
2021_01               1215
2021_02               1233
2021_03               1244
2021_04               1258
2021_05               1304
2021_06               1312
2021_07               1346
2021_08               1406
2021_09               1415
2021_10               1414
2021_11               1400
2021_12               1404
2022_01               1397
2022_02               1406
2022_03               1432
2022_04               1442
2022_05               1422
2022_06               1447
2022_07               1465
2022_08               1441
2022_09               1446
2022_10               1434
2022_11               1413
2022_12               1410
2023_01               1372
2023_02               1409
2023_03               1409
2023_04               1425
dtype: int64

this all seems expected

### 4B. Data Cleaning

In [27]:
# Removing unneeded columns. Similar to rental vacancies, I don't need the "location_fips_code" since it doesn't 
# seem to correspond to anything recognizable that I might need. But I'm keeping the rest to possibly help
# identify the regions I want to link to my food production facility address list

df_ar_new = df_ar.drop(['location_fips_code', 'population'], axis=1)

### 4C. Basic descriptive analysis

In [28]:
# Checking basic stats on each column

df_ar_new.describe().applymap(lambda x: f"{x:0.2f}")

,2017_01,2017_02,2017_03,2017_04,2017_05,2017_06,2017_07,2017_08,2017_09,2017_10,...,2022_07,2022_08,2022_09,2022_10,2022_11,2022_12,2023_01,2023_02,2023_03,2023_04
count,3108.00,3126.00,3165.00,3183.00,3207.00,3237.00,3234.00,3231.00,3243.00,3243.00,...,3378.00,3378.00,3378.00,3378.00,3378.00,3378.00,3378.00,3378.00,3378.00,3378.00
mean,1131.48,1136.63,1141.31,1151.32,1164.75,1172.95,1178.15,1176.43,1172.98,1168.73,...,1541.56,1543.45,1533.49,1517.17,1499.01,1485.71,1481.55,1485.85,1495.12,1504.00
std,404.01,409.87,409.06,411.13,415.71,418.07,418.75,416.00,413.09,408.27,...,489.60,488.71,482.81,473.77,465.18,459.56,457.70,460.14,464.11,467.72
min,439.00,439.00,440.00,456.00,460.00,480.00,499.00,514.00,552.00,549.00,...,586.00,602.00,615.00,623.00,618.00,611.00,612.00,604.00,605.00,605.00
25%,849.00,851.00,854.00,863.00,870.00,875.00,882.00,881.00,876.50,876.00,...,1180.00,1183.00,1178.00,1165.00,1153.00,1143.00,1142.00,1145.00,1149.25,1156.00
50%,1037.00,1038.50,1043.00,1053.00,1063.00,1071.00,1077.00,1075.00,1074.00,1074.00,...,1464.00,1468.00,1457.50,1442.50,1427.00,1415.00,1407.00,1409.00,1417.00,1423.50
75%,1308.25,1316.75,1320.00,1330.00,1347.00,1360.00,1363.75,1362.00,1362.50,1353.50,...,1807.00,1809.00,1795.75,1772.00,1750.75,1735.00,1733.75,1738.75,1746.00,1756.75
max,4248.00,4278.00,4311.00,4321.00,4344.00,4342.00,4354.00,4369.00,4420.00,4435.00,...,5409.00,5417.00,5359.00,5315.00,5235.00,5212.00,5204.00,5254.00,5217.00,5216.00

this all seems likely very accurate

In [30]:
# Counting value counts in some of the "object" columns

df_ar_new['location_name'].value_counts()

Santa Fe, NM              6
Rochester, MN             6
Wilmington, NC            6
Knoxville, TN             6
Baton Rouge, LA           6
                         ..
Butler County, OH         3
Forsyth County, NC        3
Eugene-Springfield, OR    3
Lane County, OR           3
Glendale, CO              3
Name: location_name, Length: 1067, dtype: int64

It's interesting that some have 6, but I checked it out and it's the difference between one being the city and one being the metro.

In [31]:
# Counting value counts in some of the "object" columns

df_ar_new['location_type'].value_counts()

City        1707
County       987
Metro        540
State        141
National       3
Name: location_type, dtype: int64

In [32]:
# Counting value counts in some of the "object" columns

df_ar_new['state'].value_counts()

Texas                   339
California              315
Florida                 252
Georgia                 150
Virginia                138
Washington              105
Colorado                105
North Carolina          102
Maryland                102
Minnesota                81
Massachusetts            75
Illinois                 66
South Carolina           60
Tennessee                57
New Jersey               57
Arizona                  54
Indiana                  54
Ohio                     51
Louisiana                51
Michigan                 51
New York                 48
Pennsylvania             48
Oregon                   45
Alabama                  42
Missouri                 42
Utah                     33
Nevada                   33
Kansas                   27
Connecticut              27
Oklahoma                 24
Nebraska                 24
Wisconsin                18
Arkansas                 18
Kentucky                 18
New Mexico               15
Mississippi              15
Iowa                     15
Idaho                    12
New Hampshire            12
Rhode Island              9
South Dakota              9
North Dakota              9
District of Columbia      9
Hawaii                    6
Delaware                  6
Montana                   3
Wyoming                   3
Name: state, dtype: int64

In [33]:
# Counting value counts in some of the "object" columns

df_ar_new['county'].value_counts()

Orange County           60
Montgomery County       57
Los Angeles County      42
Broward County          42
King County             39
                        ..
Champaign County         3
Santa Barbara County     3
Berkeley County          3
Yolo County              3
Atlantic County          3
Name: county, Length: 299, dtype: int64

In [34]:
# Counting value counts in some of the "object" columns

df_ar_new['metro'].value_counts()

Washington-Arlington-Alexandria, DC-VA-MD-WV    138
Dallas-Fort Worth-Arlington, TX                 114
Atlanta-Sandy Springs-Alpharetta, GA            108
Miami-Fort Lauderdale-Pompano Beach, FL          90
Los Angeles-Long Beach-Anaheim, CA               90
                                               ...
Bismarck, ND                                      3
Harrisburg-Carlisle, PA                           3
Houma-Thibodaux, LA                               3
Toledo, OH                                        3
Moses Lake, WA                                    3
Name: metro, Length: 181, dtype: int64

In [35]:
# Counting value counts in some of the "object" columns

df_ar_new['bed_size'].value_counts()

overall    1126
1br        1126
2br        1126
Name: bed_size, dtype: int64

all of the above looks as expected

In [36]:
# Exporting cleaned data

df_ar_new.to_csv(os.path.join(path, 'Data', 'Cleaned', 'Apartment_List_Rent_Estimates.csv'), index=False)

## 5. Zip code list acquired from major protein company facility locations

In [37]:
# Importing dataframe
df_tz = pd.read_csv(os.path.join(path, 'Data', 'Original', '3.21.23 plant addresses.csv'), index_col = False)

In [38]:
# checking dataset info

df_tz.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113 entries, 0 to 112
Data columns (total 5 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Location                           113 non-null    object
 1   Location Address - Line 1          113 non-null    object
 2   Location Address - City            113 non-null    object
 3   Location Address - State/Province  113 non-null    object
 4   Location Address - Postal Code     113 non-null    object
dtypes: object(5)
memory usage: 4.5+ KB

I thought about changing the "postal code" to "int64" but I changed my mind so that the zeroes at the beginning of some zip codes will remain the way they are. And "int64" probably can't have a leading zero

In [39]:
# Checking for duplicates (and removing them if there are any) - then checking if the numbers change

df_tz.drop_duplicates(inplace=True)

df_tz.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 113 entries, 0 to 112
Data columns (total 5 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Location                           113 non-null    object
 1   Location Address - Line 1          113 non-null    object
 2   Location Address - City            113 non-null    object
 3   Location Address - State/Province  113 non-null    object
 4   Location Address - Postal Code     113 non-null    object
dtypes: object(5)
memory usage: 5.3+ KB

no duplicates, though it seems strange to me that now it's using slightly more memory

In [40]:
# Checking for missing values
missing_values = df_tz.isnull().sum()

# total rows in dataframe
total_rows = df_tz.shape[0]

# making it show me all the rows
pd.options.display.max_rows = len(df_tz.dtypes)

# calculating percentage of missing values
percent_missing = ((missing_values / total_rows) * 100).round(2)

# Making a dataframe to show missing values
missing_value_table = pd.concat([missing_values, percent_missing], axis=1)

# Naming columns for sorting
missing_value_table.columns = ['Missing Values', 'Percent Missing']

# sorting the view based on most missing values %
missing_value_table.sort_values('Percent Missing', ascending=True, inplace=True)

print(missing_value_table)

                                   Missing Values  Percent Missing
Location                                        0              0.0
Location Address - Line 1                       0              0.0
Location Address - City                         0              0.0
Location Address - State/Province               0              0.0
Location Address - Postal Code                  0              0.0

No missing values, just a clean straight list

In [41]:
# counting number of unique values in each column

print(df_tz.nunique())

Location                             113
Location Address - Line 1            105
Location Address - City               96
Location Address - State/Province     26
Location Address - Postal Code        97
dtype: int64

The interesting thing is that 8 locations share the same address line, even though they're technically considered different facilites.  I'll look into that later.  This dataset (i.e. the goals of the project) targets 97 specific zip codes, which are in 96 different cities.  So some cities/zip codes obviously have multiple facilities

### 5B. Data Cleaning

In [42]:
# I don't have any unwanted columns here, 
# but I want to change the column names to make them fit better with pandas df naming conventions

In [43]:
# Renaming columns

df_tz = df_tz.rename(columns={'Location Address - Line 1': 'address', 'Location Address - City': 'city', 'Location Address - State/Province': 'state', 'Location Address - Postal Code': 'zip'})

In [44]:
df_tz.head()

                   Location           address         city     state    zip
0        54th St Enid Plant  201 S Raleigh Rd         Enid  Oklahoma  73701
1              Albany Plant      2294 KY 90 W       Albany  Kentucky  42602
2  Albany Waste Water Plant      2294 KY 90 W       Albany  Kentucky  42602
3         Albertville Plant    6600 Hwy 431 S  Albertville   Alabama  35950
4            Amarillo Plant       5000 FM1912     Amarillo     Texas  79108

In [45]:
# Dropping rows that have facilities that were recently closed

df_tz.drop(df_tz[df_tz['city'] == 'Van Buren'].index, inplace=True)
df_tz.drop(df_tz[df_tz['city'] == 'Glen Allen'].index, inplace=True)

### 5C. Basic Descriptive Analysis

In [48]:
# There aren't any numeric columns to run stats on. So, counting value counts in the "object" columns

df_tz['Location'].value_counts()

54th St Enid Plant    1
New London Plant      1
                     ..
Dakota City Plant     1
Zeeland Plant         1
Name: Location, Length: 111, dtype: int64

In [49]:
df_tz['address'].value_counts()

57 Melvin Clark Road    3
2294 KY 90 W            2
                       ..
1131 Dakota Ave         1
8300 96th Avenue        1
Name: address, Length: 103, dtype: int64

In [50]:
df_tz['city'].value_counts()

Enid          4
Wilkesboro    3
             ..
Dallas        1
Zeeland       1
Name: city, Length: 94, dtype: int64

In [54]:
# making it show me all the rows
pd.set_option('display.max_rows', None)
df_tz['state'].value_counts().to_frame()

                state
Arkansas           18
Texas              10
Iowa                8
Alabama             7
Nebraska            7
Missouri            6
North Carolina      6
Tennessee           5
Kansas              5
Kentucky            5
Oklahoma            5
Georgia             5
Michigan            3
Illinois            3
Mississippi         3
Indiana             2
Virginia            2
Ohio                2
Pennsylvania        2
South Carolina      1
Florida             1
Wisconsin           1
Washington          1
Maine               1
California          1
New Jersey          1

In [55]:
df_tz['zip'].value_counts()

73701         4
28697         3
36027         3
68748         2
72756         2
50588         2
72638         2
31730         2
17557         2
42602         2
72764         2
50703         2
54961         1
68137         1
76180         1
64854         1
38059         1
99363         1
38261         1
72114         1
71852         1
71602         1
28112         1
65708         1
27332         1
52738         1
46947         1
50220         1
30161         1
04102         1
23442         1
68462         1
48091         1
72958         1
08360         1
31092         1
76384         1
72704         1
72802         1
68450         1
42452         1
64507         1
75090         1
37160         1
78155         1
65301         1
94580         1
35077         1
66106         1
68850         1
67505-1111    1
61257         1
32254         1
49684         1
39204         1
41001-9001    1
72830         1
28610         1
45246         1
60641         1
39183         1
75935         1
62232         1
39051         1
75633         1
74728         1
42101         1
35031         1
72616         1
44001         1
79108         1
35950         1
64020         1
47112         1
51501         1
72901         1
67501         1
38343         1
77029         1
71801         1
76117         1
71944         1
37072         1
35906         1
67851         1
30040         1
66801         1
29640         1
63841         1
51442         1
72834         1
24586         1
75237         1
68731         1
49464         1
Name: zip, dtype: int64

Looks like I need to update a couple of those zip codes to take off the numbers

In [56]:
# removing the latter parts of any zip codes that have the -

df_tz['zip'] = df_tz['zip'].str.split('-').str[0]

In [57]:
df_tz['zip'].value_counts()

73701    4
28697    3
36027    3
68748    2
72756    2
50588    2
72638    2
31730    2
17557    2
42602    2
72764    2
50703    2
54961    1
68137    1
76180    1
64854    1
38059    1
99363    1
38261    1
72114    1
71852    1
71602    1
28112    1
65708    1
27332    1
52738    1
46947    1
50220    1
30161    1
04102    1
23442    1
68462    1
48091    1
72958    1
08360    1
31092    1
76384    1
72704    1
72802    1
68450    1
42452    1
64507    1
75090    1
37160    1
78155    1
65301    1
94580    1
35077    1
66106    1
68850    1
67505    1
61257    1
32254    1
49684    1
39204    1
41001    1
72830    1
28610    1
45246    1
60641    1
39183    1
75935    1
62232    1
39051    1
75633    1
74728    1
42101    1
35031    1
72616    1
44001    1
79108    1
35950    1
64020    1
47112    1
51501    1
72901    1
67501    1
38343    1
77029    1
71801    1
76117    1
71944    1
37072    1
35906    1
67851    1
30040    1
66801    1
29640    1
63841    1
51442    1
72834    1
24586    1
75237    1
68731    1
49464    1
Name: zip, dtype: int64

it worked.  Looks like I've done all the checks on it I can do now, and it's a nice clean list.

In [58]:
# Exporting cleaned data

df_tz.to_csv(os.path.join(path, 'Data', 'Cleaned', 'All_Tyson_Addresses.csv'), index=False)

### 5D. Creating zip code list to be used for web scraper

In [120]:
# Creating a dataframe with just food processing facility zips but with no duplicates - to be used in the real estate scraper

# I came back in and modified this to do astype(str) so that I can preserve the leading zeroes
df_tzips = df_tz[['zip']].astype(str)

In [121]:
df_tzips.drop_duplicates(inplace=True)

df_tzips.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 95 entries, 0 to 112
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   zip     95 non-null     object
dtypes: object(1)
memory usage: 1.5+ KB

In [122]:
print(df_tzips)

       zip
0    73701
1    42602
3    35950
4    79108
5    44001
6    72764
7    72616
8    35031
9    42101
10   74728
11   31730
13   75633
14   39051
15   62232
16   75935
17   39183
18   60641
19   72756
20   45246
21   28610
22   72830
23   41001
24   39204
25   49684
26   64020
27   47112
28   51501
29   30040
30   68731
31   75237
32   24586
33   72834
34   51442
35   63841
36   29640
37   66801
39   36027
42   67851
43   72901
44   35906
46   37072
47   71944
48   72638
50   76117
51   71801
52   77029
53   38343
54   67505
55   67501
56   32254
57   61257
58   66106
59   68850
60   46947
61   52738
62   68748
64   27332
65   65708
66   28112
67   72114
68   71852
69   17557
71   54961
72   38059
73   64854
74   76180
75   38261
76   68137
77   99363
78   50220
79   71602
81   04102
83   42452
84   30161
85   35077
86   94580
87   65301
88   78155
89   37160
90   75090
91   64507
92   50588
94   68450
95   23442
96   72802
98   72704
100  76384
101  31092
102  08360
103  72958
104  48091
105  50703
107  68462
108  28697
112  49464

In [123]:
# Exporting zips only list

df_tzips.to_csv(os.path.join(path, 'Data', 'Cleaned', 'Tyson_zips_only.csv'), index=False, header=False)

It seems like it worked (to preserve leading zeroes) if I open in notepad or something. Not sure why it doesn't show up when I bring it back in here. I guess it automatically imports as string here?

In [131]:
# Checking to make sure that zip codes with leading zeroes remain intact

# Importing dataframe
df_tzips_import = pd.read_csv(os.path.join(path, 'Data', 'Cleaned', 'Tyson_zips_only.csv'), dtype ='str', index_col = False)

In [132]:
# Set display options to print all rows
pd.set_option('display.max_rows', None)

df_tzips_import.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94 entries, 0 to 93
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   73701   94 non-null     object
dtypes: object(1)
memory usage: 880.0+ bytes

In [133]:
print(df_tzips_import)

    73701
0   42602
1   35950
2   79108
3   44001
4   72764
5   72616
6   35031
7   42101
8   74728
9   31730
10  75633
11  39051
12  62232
13  75935
14  39183
15  60641
16  72756
17  45246
18  28610
19  72830
20  41001
21  39204
22  49684
23  64020
24  47112
25  51501
26  30040
27  68731
28  75237
29  24586
30  72834
31  51442
32  63841
33  29640
34  66801
35  36027
36  67851
37  72901
38  35906
39  37072
40  71944
41  72638
42  76117
43  71801
44  77029
45  38343
46  67505
47  67501
48  32254
49  61257
50  66106
51  68850
52  46947
53  52738
54  68748
55  27332
56  65708
57  28112
58  72114
59  71852
60  17557
61  54961
62  38059
63  64854
64  76180
65  38261
66  68137
67  99363
68  50220
69  71602
70  04102
71  42452
72  30161
73  35077
74  94580
75  65301
76  78155
77  37160
78  75090
79  64507
80  50588
81  68450
82  23442
83  72802
84  72704
85  76384
86  31092
87  08360
88  72958
89  48091
90  50703
91  68462
92  28697
93  49464

it didn't work the first time, so I'm going to convert the zip code column to "string" before exporting it then try again and check it again

OK, after playing with it a bit, I finally figured it out. Importing csv's like that in pandas automatically changes the dtype unless I specify the dtype is "str". Then it'll show correctly.

##  6. Realtor.com scraped homes for sale listings for zip codes in list

### 6A. Web Scraping Script

In [224]:
# Below is the code I created for scraping the for sale homes using the zip code list from realtor.com
# I developed this code in another notebook (that's a bit messy, because of a lot of trial and error)
# I wasn't going to run it again in this notebook, because it took a few hours to run
# But then I had to tweak it so it would include the zip code it was searching for in the dataframe.
# So then I ran it again (more than once, because it got caught once)
# I wrote this code by looking at a bunch of tutorials and also asking ChatGPT and Google Bard for help
# And then by learning more from the AI chatbots, and then fixing the code more, and talking to other people
# and a really long process of incrementally improving it until it worked just perfectly.

import os
import requests
from bs4 import BeautifulSoup
import pandas as pd
import datetime
import time
import random
import csv
import re

start_time = time.time()

# Defining path
path=r'D:\Adam\Employment\Data Analysis Course\Final Data Project'

# Defining location of zipfile
zipfile = 'D:\Adam\Employment\Data Analysis Course\Final Data Project\Data\Cleaned\Tyson_zips_only.csv'

# Open the CSV file that contains the list of zip codes.
with open(zipfile, 'r') as f:
    reader = csv.reader(f)
    zip_codes = list(reader)

data = []    
    
# Loop through the list of zip codes.
for zip_code in zip_codes:
    print(f"Processing zip code: {zip_code[0]}")
    
    # Add a random delay before going to next zip code
    time.sleep(random.randint(30, 90))
    
    # Loop through the page numbers (1-20).
    for page_num in range(1, 20):
        print(f"Processing page {page_num}")
    
        # Update the URL in the script.
        url_template = "https://www.realtor.com/realestateandhomes-search/{}/pg-{}"
        url = url_template.format(zip_code[0], page_num)

        # Set user-agent header to avoid bot detection
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}

        # Add a random delay before making the request
        time.sleep(random.randint(8, 16))

        # Send HTTP GET request to the URL and get the HTML response
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            print("Request successful")
        else:
            print(f"Request failed with status code: {response.status_code}. No more listings pages found.")
            break

        # Parse the HTML response using BeautifulSoup
        soup = BeautifulSoup(response.content, 'html.parser')

        # Find the container for all the properties
        container = soup.find('section', class_='srp-content')

        # Check if the container is empty
        if container is None:
            print("No listings found")
            break

        # Check if the page contains the text "We're Sorry"
        if "We're Sorry" in soup.text:
            print("No more pages")
            break

        # Find all the listings in the container
        listings = container.find_all('div', attrs={'data-label': 'property-card'})

        # Loop through each listing and extract the details
        for listing in listings:
            if listing is not None:
                try:
                    address1 = listing.find('div', attrs={'data-label': 'pc-address'}).text.strip()
                except AttributeError:
                    address1 = ''

                try:
                    address2 = listing.find('div', attrs={'data-label': 'pc-address-second'}).text.strip()
                except AttributeError:
                    address2 = ''

                try:
                    availability = listing.find('span', class_='statusText').text.strip()
                except AttributeError:
                    style = ''

                try:
                    price = listing.find('span', attrs={'data-label': 'pc-price'}).text.strip().replace('From', '').replace(',', '').replace('$', '')
                except AttributeError:
                    price = ''

                try:
                    beds = listing.find('li', attrs={'data-label': 'pc-meta-beds'}).text.strip().replace('bed', '')
                except AttributeError:
                    beds = ''

                try:
                    baths = listing.find('li', attrs={'data-label': 'pc-meta-baths'}).text.strip().replace('bath', '')
                except AttributeError:
                    baths = ''

                try:
                    sqft = listing.find('li', attrs={'data-label': 'pc-meta-sqft'}).text.strip().replace(',', '').split('sqft')[0]
                except AttributeError:
                    sqft = ''

            else:
                print('No listing found.')

            # Appending the data
            data.append([zip_code[0], address1, address2, availability, price, beds, baths, sqft])
       
        # stopping pagination if less than 41 listings found
        if soup.find(id="srp-footer-found-listing") is None:
            print("Not enough listings found for this zip code")
            break
        
        if int(soup.find(id="srp-footer-found-listing").text.strip().split()[1]) < 40:
            print("No more listings found")
            break
        
        else:
            continue
        
    print("Finished processing zip code")

# Create a Pandas dataframe from the extracted data
df = pd.DataFrame(data, columns=['TysonZip', 'Address1', 'Address2', 'Availability', 'Price', 'Beds', 'Baths', 'Sqft'])

# get today's date in the format YYYY-MM-DD
today = datetime.datetime.today().strftime('%Y-%m-%d')

# Export the dataframe to a CSV file
df.to_csv(os.path.join(path, 'Data', 'Scraped', f'TysonZips_forsale_{today}.csv'), index=False)

# Print the dataframe
print(df)

end_time = time.time()

execution_time = end_time - start_time

print("Execution time:", execution_time)

Processing zip code: 73701
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 42602
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 35950
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 79108
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 44001
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 72764
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request successful
Processing page 6
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 72616
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 35031
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 42101
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request successful
Processing page 6
Request successful
Processing page 7
Request successful
Processing page 8
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 74728
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request successful
Processing page 6
Request successful
Processing page 7
Request successful
Processing page 8
Request successful
Processing page 9
Request successful
Processing page 10
Request successful
Processing page 11
Request successful
Processing page 12
Request successful
Processing page 13
Request successful
Processing page 14
Request successful
Processing page 15
Request successful
Processing page 16
Request successful
Processing page 17
Request successful
Processing page 18
Request successful
Processing page 19
Request successful
Finished processing zip code
Processing zip code: 31730
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 75633
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 39051
Processing page 1
Request successful
Processing page 2
Request successful
No listings found
Finished processing zip code
Processing zip code: 62232
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 75935
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 39183
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 60641
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 72756
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request successful
Processing page 6
Request successful
Processing page 7
Request successful
Processing page 8
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 45246
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 28610
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 72830
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 41001
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request successful
Processing page 6
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 39204
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 49684
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request successful
Processing page 6
Request successful
Processing page 7
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 64020
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 47112
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 51501
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 30040
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request successful
Processing page 6
Request successful
Processing page 7
Request successful
Processing page 8
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 68731
Processing page 1
Request successful
Not enough listings found for this zip code
Finished processing zip code
Processing zip code: 75237
Processing page 1
Request successful
Not enough listings found for this zip code
Finished processing zip code
Processing zip code: 24586
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 72834
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 51442
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 63841
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 29640
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3

Request successful
Processing page 4
Request successful
Processing page 5
Request successful
Processing page 6
Request successful
Processing page 7
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 66801
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 36027
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 67851
Processing page 1
Request successful
Not enough listings found for this zip code
Finished processing zip code
Processing zip code: 72901
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 35906
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 37072
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 71944
Processing page 1
Request successful
Not enough listings found for this zip code
Finished processing zip code
Processing zip code: 72638
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 76117
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 71801
Processing page 1
Request successful
Processing page 2
Request failed with status code: 403. No more listings pages found.
Finished processing zip code
Processing zip code: 77029
Processing page 1
Request failed with status code: 403. No more listings pages found.
Finished processing zip code
Processing zip code: 38343
Processing page 1
Request failed with status code: 403. No more listings pages found.
Finished processing zip code
Processing zip code: 67505
Processing page 1
Request failed with status code: 403. No more listings pages found.
Finished processing zip code
Processing zip code: 67501
Processing page 1
Request failed with status code: 403. No more listings pages found.
Finished processing zip code
Processing zip code: 32254
Processing page 1
Request failed with status code: 403. No more listings pages found.
Finished processing zip code
Processing zip code: 61257
Processing page 1
Request failed with status code: 403. No more listings pages found.
Finished processing zip code
Processing zip code: 66106
Processing page 1
Request failed with status code: 403. No more listings pages found.
Finished processing zip code
Processing zip code: 68850
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 46947
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 52738
Processing page 1
Request successful
Not enough listings found for this zip code
Finished processing zip code
Processing zip code: 68748
Processing page 1
Request successful
Not enough listings found for this zip code
Finished processing zip code
Processing zip code: 27332
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request successful
Processing page 6
Request successful
Processing page 7
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 65708
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 28112
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request successful
Processing page 6
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 72114
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 71852
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 17557
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 54961
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 38059
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 64854
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 76180
Processing page 1
Request successful
Processing page 2
Request successful
No listings found
Finished processing zip code
Processing zip code: 38261
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 68137
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 99363
Processing page 1
Request successful
Not enough listings found for this zip code
Finished processing zip code
Processing zip code: 50220
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 71602
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 04102
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 42452
Processing page 1
Request successful
Not enough listings found for this zip code
Finished processing zip code
Processing zip code: 30161
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
No listings found
Finished processing zip code
Processing zip code: 35077
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 94580
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 65301
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request successful
Processing page 6
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 78155
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request successful
Processing page 6
Request successful
Processing page 7
Request successful
Processing page 8
Request successful
Processing page 9
Request successful
Processing page 10
Request successful
Processing page 11

Request successful
Processing page 12
Request successful
Processing page 13
Request successful
Processing page 14
Request successful
Processing page 15
Request successful
Processing page 16
Request successful
Processing page 17
Request successful
Processing page 18
Request successful
Processing page 19
Request successful
Finished processing zip code
Processing zip code: 37160
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
No listings found
Finished processing zip code
Processing zip code: 75090
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request successful
Processing page 6
Request successful
Processing page 7
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 64507
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 50588
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 68450
Processing page 1
Request successful
Not enough listings found for this zip code
Finished processing zip code
Processing zip code: 23442
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 72802
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 72704
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request successful
Processing page 6
Request successful
Processing page 7
Request successful
Processing page 8
Request successful
Processing page 9
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 76384
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 31092
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 08360
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 72958
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 48091
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 50703
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 68462
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 28697
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 49464
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
     TysonZip                                   Address1           Address2  \
0       73701              4801 Pocasset, Enid, OK 73701     Enid, OK 73701
1       73701         901 W Illinois Ave, Enid, OK 73701     Enid, OK 73701
2       73701         905 W Illinois Ave, Enid, OK 73701     Enid, OK 73701
3       73701   111 and 111 1/2 W Locust, Enid, OK 73701     Enid, OK 73701
4       73701              609 N 13th St, Enid, OK 73701     Enid, OK 73701
...       ...                                        ...                ...
8683    49464  3664 Garner Dr Unit 17, Zeeland, MI 49464  Zeeland, MI 49464
8684    49464         6876 C 80th Ave, Zeeland, MI 49464  Zeeland, MI 49464
8685    49464      7568 Rivertrail Ct, Zeeland, MI 49464  Zeeland, MI 49464
8686    49464          3652 Garner Dr, Zeeland, MI 49464  Zeeland, MI 49464
8687    49464    10100 Felch St Lot A, Zeeland, MI 49464  Zeeland, MI 49464

     Availability   Price Beds Baths  Sqft
0        For Sale  315000    4     2  1971
1        For Sale   69900    2     1   865
2        For Sale   84900    3     2  1260
3        For Sale   35000
4        For Sale   16500    2     1   994
...           ...     ...  ...   ...   ...
8683      Pending  489900    4   2.5  2250
8684     For Sale  140000
8685      Pending  498985    4   2.5  2217
8686      Pending   80000
8687      Pending  150000

[8688 rows x 8 columns]
Execution time: 9483.886217594147

This got caught partway and I had to turn on a vpn, so I'll have to do the other zip codes separately and combine the list

In [225]:
# Running it again with the skipped zips

import os
import requests
from bs4 import BeautifulSoup
import pandas as pd
import datetime
import time
import random
import csv
import re

start_time = time.time()

# Defining path
path=r'D:\Adam\Employment\Data Analysis Course\Final Data Project'

# Defining location of zipfile
zipfile = 'D:\Adam\Employment\Data Analysis Course\Final Data Project\Data\Cleaned\Tyson_skippedZips.csv'

# Open the CSV file that contains the list of zip codes.
with open(zipfile, 'r') as f:
    reader = csv.reader(f)
    zip_codes = list(reader)

data = []    
    
# Loop through the list of zip codes.
for zip_code in zip_codes:
    print(f"Processing zip code: {zip_code[0]}")
    
    # Add a random delay before going to next zip code
    time.sleep(random.randint(30, 90))
    
    # Loop through the page numbers (1-20).
    for page_num in range(1, 20):
        print(f"Processing page {page_num}")
    
        # Update the URL in the script.
        url_template = "https://www.realtor.com/realestateandhomes-search/{}/pg-{}"
        url = url_template.format(zip_code[0], page_num)

        # Set user-agent header to avoid bot detection
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}

        # Add a random delay before making the request
        time.sleep(random.randint(8, 16))

        # Send HTTP GET request to the URL and get the HTML response
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            print("Request successful")
        else:
            print(f"Request failed with status code: {response.status_code}. No more listings pages found.")
            break

        # Parse the HTML response using BeautifulSoup
        soup = BeautifulSoup(response.content, 'html.parser')

        # Find the container for all the properties
        container = soup.find('section', class_='srp-content')

        # Check if the container is empty
        if container is None:
            print("No listings found")
            break

        # Check if the page contains the text "We're Sorry"
        if "We're Sorry" in soup.text:
            print("No more pages")
            break

        # Find all the listings in the container
        listings = container.find_all('div', attrs={'data-label': 'property-card'})

        # Loop through each listing and extract the details
        for listing in listings:
            if listing is not None:
                try:
                    address1 = listing.find('div', attrs={'data-label': 'pc-address'}).text.strip()
                except AttributeError:
                    address1 = ''

                try:
                    address2 = listing.find('div', attrs={'data-label': 'pc-address-second'}).text.strip()
                except AttributeError:
                    address2 = ''

                try:
                    availability = listing.find('span', class_='statusText').text.strip()
                except AttributeError:
                    style = ''

                try:
                    price = listing.find('span', attrs={'data-label': 'pc-price'}).text.strip().replace('From', '').replace(',', '').replace('$', '')
                except AttributeError:
                    price = ''

                try:
                    beds = listing.find('li', attrs={'data-label': 'pc-meta-beds'}).text.strip().replace('bed', '')
                except AttributeError:
                    beds = ''

                try:
                    baths = listing.find('li', attrs={'data-label': 'pc-meta-baths'}).text.strip().replace('bath', '')
                except AttributeError:
                    baths = ''

                try:
                    sqft = listing.find('li', attrs={'data-label': 'pc-meta-sqft'}).text.strip().replace(',', '').split('sqft')[0]
                except AttributeError:
                    sqft = ''

            else:
                print('No listing found.')

            # Appending the data
            data.append([zip_code[0], address1, address2, availability, price, beds, baths, sqft])
       
        # stopping pagination if less than 41 listings found
        if soup.find(id="srp-footer-found-listing") is None:
            print("Not enough listings found for this zip code")
            break
        
        if int(soup.find(id="srp-footer-found-listing").text.strip().split()[1]) < 40:
            print("No more listings found")
            break
        
        else:
            continue
        
    print("Finished processing zip code")

# Create a Pandas dataframe from the extracted data
df = pd.DataFrame(data, columns=['TysonZip', 'Address1', 'Address2', 'Availability', 'Price', 'Beds', 'Baths', 'Sqft'])

# get today's date in the format YYYY-MM-DD
today = datetime.datetime.today().strftime('%Y-%m-%d')

# Export the dataframe to a CSV file
df.to_csv(os.path.join(path, 'Data', 'Scraped', f'Tyson_skippedZips_forsale_{today}.csv'), index=False)

# Print the dataframe
print(df)

end_time = time.time()

execution_time = end_time - start_time

print("Execution time:", execution_time)

Processing zip code: 71801
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 77029
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 38343
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 67505
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 67501
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 32254
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 61257
Processing page 1
Request successful
Not enough listings found for this zip code
Finished processing zip code
Processing zip code: 66106
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
    TysonZip                                           Address1  \
0      71801                  745 Highway 355 E, Hope, AR 71801
1      71801                      1504 S Elm St, Hope, AR 71801
2      71801                  3115 Highway 73 E, Hope, AR 71801
3      71801                      1010 W 7th St, Hope, AR 71801
4      71801                    621 S Fulton St, Hope, AR 71801
5      71801                   181 Highway 32 E, Hope, AR 71801
6      71801                205 Hempstead # 254, Hope, AR 71801
7      71801                3143 AR Highway 174, Hope, AR 71801
8      71801                      518 E 14th St, Hope, AR 71801
9      71801                     2603 E 23rd St, Hope, AR 71801
10     71801                  1020 N Sherman St, Hope, AR 71801
11     71801                  3093 Highway 29 N, Hope, AR 71801
12     71801                   512 E Hickory St, Hope, AR 71801
13     71801                 1901 Georgetown Dr, Hope, AR 71801
14     71801                         Walmart Dr, Hope, AR 71801
15     71801                3143 AR Highway 174, Hope, AR 71801
16     71801                         Highway 67, Hope, AR 71801
17     71801  5703 Patmos Hempstead 3 Rd Unit 5703, Hope, AR...
18     71801                    San Fernando Rd, Hope, AR 71801
19     71801                  3005 Highway 29 N, Hope, AR 71801
20     71801                 2818 Highway 278 E, Hope, AR 71801
21     71801                      1515 Pecan St, Hope, AR 71801
22     71801                      407 E 17th St, Hope, AR 71801
23     71801                       Highway 32 E, Hope, AR 71801
24     71801                  1412 Robinhood Ln, Hope, AR 71801
25     71801                      405 E 16th St, Hope, AR 71801
26     71801                   712 E Hickory St, Hope, AR 71801
27     71801                   415 E Hickory St, Hope, AR 71801
28     71801                2402 W Plainview St, Hope, AR 71801
29     71801                     1503 S Pine Dr, Hope, AR 71801
30     71801                  806 W Avenue F St, Hope, AR 71801
31     71801                       Hempstead 16, Hope, AR 71801
32     71801                     5703 Patmos Rd, Hope, AR 71801
33     71801                  4885 Highway 29 N, Hope, AR 71801
34     71801                313 N Washington St, Hope, AR 71801
35     71801                     1900 Strong St, Hope, AR 71801
36     71801                       Hempstead 16, Hope, AR 71801
37     71801                     1805 E 28th St, Hope, AR 71801
38     71801                 2717 Highway 278 E, Hope, AR 71801
39     71801                       517 W 5th St, Hope, AR 71801
40     71801                 706 E Short 6th St, Hope, AR 71801
41     71801                      504 S Pine St, Hope, AR 71801
42     71801                   1115 S Walnut St, Hope, AR 71801
43     71801                     1303 Center St, Hope, AR 71801
44     71801              2503 Evangeline St Dr, Hope, AR 71801
45     71801                  402 N Ferguson St, Hope, AR 71801
46     71801                   1000 N Hervey St, Hope, AR 71801
47     71801                      County Road 5, Hope, AR 71801
48     71801                      709 S Pine St, Hope, AR 71801
49     71801                     500 N McRae St, Hope, AR 71801
50     71801                      1401 S Elm St, Hope, AR 71801
51     71801                        Highway 195, Hope, AR 71801
52     71801                      406 W 16th St, Hope, AR 71801
53     71801                      308 E 13th St, Hope, AR 71801
54     71801                         Georgetown, Hope, AR 71801
55     71801
56     71801                    Bill Clinton Dr, Hope, AR 71801
57     71801                    510 S Fulton St, Hope, AR 71801
58     71801                   1005 S Walnut St, Hope, AR 71801
59     77029            10234 Burman St, Jacinto City, TX 77029
60     77029              10804 Palestine St, Houston, TX 77029
61     77029                 10426 Norvic St, Houston, TX 77029
62     77029                1515 Teanaway Ln, Houston, TX 77029
63     77029               8519 Farqueson St, Houston, TX 77029
64     77029            1314 Clinton Park St, Houston, TX 77029
65     77029                 433 Calloway St, Houston, TX 77029
66     77029                 11117 Oswego St, Houston, TX 77029
67     77029                10638 Fairfax St, Houston, TX 77029
68     77029                  8810 Cowart St, Houston, TX 77029
69     77029                    210 Owens St, Houston, TX 77029
70     77029                 1438 Demaree Ln, Houston, TX 77029
71     77029                  9702 Signet St, Houston, TX 77029
72     77029                 10530 Pillot St, Houston, TX 77029
73     77029        10209 Wiggins St Unit 14, Houston, TX 77029
74     77029                       Pelsey St, Houston, TX 77029
75     77029                  3827 Beaver Dr, Houston, TX 77029
76     77029                   3905 Amoor St, Houston, TX 77029
77     77029              430 Mississippi St, Houston, TX 77029
78     77029                 917 Defender St, Houston, TX 77029
79     77029          11213 Invierno St, Jacinto City, TX 77029
80     77029            322 New Hampshire St, Houston, TX 77029
81     77029             405 Rhode Island St, Houston, TX 77029
82     77029                 9704 Turnbow St, Houston, TX 77029
83     77029          314 Calloway St Lot 25, Houston, TX 77029
84     77029              10325 Lane St, Jacinto City, TX 77029
85     77029              10209 Palestine St, Houston, TX 77029
86     77029                    261 Owens St, Houston, TX 77029
87     77029                 10213 Burman St, Houston, TX 77029
88     77029                     326 Tite St, Houston, TX 77029
89     77029                9939 Lanewell St, Houston, TX 77029
90     77029               8603 Farqueson St, Houston, TX 77029
91     77029                 9802 Nedwald St, Houston, TX 77029
92     77029                   8715 Josie St, Houston, TX 77029
93     77029             604 Clinton Park St, Houston, TX 77029
94     77029                         Dehaven, Houston, TX 77029
95     77029                9702 Garcroft St, Houston, TX 77029
96     77029                 301 Delaware St, Houston, TX 77029
97     77029                 305 Delaware St, Houston, TX 77029
98     77029                 118 DE Haven St, Houston, TX 77029
99     77029            1224 Holland St, Jacinto City, TX 77029
100    77029                9927 Lanewell St, Houston, TX 77029
101    77029                     317 Gans St, Houston, TX 77029
102    77029                    9721 Yuma St, Houston, TX 77029
103    77029                1427 Teanaway Ln, Houston, TX 77029
104    77029                9919 Lanewell St, Houston, TX 77029
105    77029             308 Rhode Island St, Houston, TX 77029
106    77029                9923 Lanewell St, Houston, TX 77029
107    77029                 1309 Switzer St, Houston, TX 77029
108    77029          8221 Flaxman St Lot 11, Houston, TX 77029
109    77029              417 Mississippi St, Houston, TX 77029
110    77029                          Pelsey, Houston, TX 77029
111    77029             Tuffly Lots 33 & 34, Houston, TX 77029
112    77029                         Turnbow, Houston, TX 77029
113    77029                 7923 Clinton Dr, Houston, TX 77029
114    77029                9941 Lanewell St, Houston, TX 77029
115    77029          9700 Block of Garcroft, Houston, TX 77029
116    77029                     421 Gans St, Houston, TX 77029
117    77029                 9725 Clinton Dr, Houston, TX 77029
118    77029                9935 Lanewell St, Houston, TX 77029
119    77029              10517 Muscatine St, Houston, TX 77029
120    77029            1114 Clinton Park St, Houston, TX 77029
121    77029              336 Connecticut St, Houston, TX 77029
122    77029                 8783 Othello St, Houston, TX 77029
123    77029               9819 Mimbrough St, Houston, TX 77029
124    77029                9937 Lanewell St, Houston, TX 77029
125    77029                9931 Lanewell St, Houston, TX 77029
126    77029                9943 Lanewell St, Houston, TX 77029
127    77029                9929 Lanewell St, Houston, TX 77029
128    77029                 229 DE Haven St, Houston, TX 77029
129    77029                   435 Mascot St, Houston, TX 77029
130    77029                 9815 Turnbow St, Houston, TX 77029
131    77029                    Armstrong St, Houston, TX 77029
132    77029        Fillmore St Lots 23 & 24, Houston, TX 77029
133    77029                     Calloway St, Houston, TX 77029
134    77029                9834 Lanewell St, Houston, TX 77029
135    77029              230 Mississippi St, Houston, TX 77029
136    77029             1413 Sheryl St, Jacinto City, TX 77029
137    77029                9707 Garcroft St, Houston, TX 77029
138    77029                 8639 Tilgham St, Houston, TX 77029
139    38343              7801 Beau Beth Dr, Humboldt, TN 38343
140    38343     157 and 167 Saddle Tree Dr, Humboldt, TN 38343
141    38343                501 Craddock St, Humboldt, TN 38343
142    38343              1952 Stallings Rd, Humboldt, TN 38343
143    38343              32 Jim Jackson Rd, Humboldt, TN 38343
144    38343                 1905 E Main St, Humboldt, TN 38343
145    38343                 3009 Laurel St, Humboldt, TN 38343
146    38343               508 McLin St Ext, Humboldt, TN 38343
147    38343              9016 Highway 152W, Humboldt, TN 38343
148    38343                247 Fairview Dr, Humboldt, TN 38343
149    38343              2802 Pritchard Ln, Humboldt, TN 38343
150    38343          295 State Route 186 N, Humboldt, TN 38343
151    38343                1306 Osborne St, Humboldt, TN 38343
152    38343                 82 Craddock St, Humboldt, TN 38343
153    38343                 124 Calhoun St, Humboldt, TN 38343
154    38343                  N Central Ave, Humboldt, TN 38343
155    38343                 120 Calhoun St, Humboldt, TN 38343
156    38343                 84 Craddock St, Humboldt, TN 38343
157    38343                2425 St Mary Dr, Humboldt, TN 38343
158    38343              3977 Greenview Cv, Humboldt, TN 38343
159    38343                 2310 E Main St, Humboldt, TN 38343
160    38343              1521 Woodhaven St, Humboldt, TN 38343
161    38343              526 S Highway 186, Humboldt, TN 38343
162    38343                2815 Tinsley Rd, Humboldt, TN 38343
163    38343                  917 N 12th St, Humboldt, TN 38343
164    38343                827 Mary Key Dr, Humboldt, TN 38343
165    38343              2803 Pritchard Ln, Humboldt, TN 38343
166    38343                  1837 Salem Rd, Humboldt, TN 38343
167    38343                 709 N 16th Ave, Humboldt, TN 38343
168    38343              3112 Doe Trail Cv, Humboldt, TN 38343
169    38343                  112 Main St S, Humboldt, TN 38343
170    38343                   1619 Vine St, Humboldt, TN 38343
171    38343              1277 Woodhaven Dr, Humboldt, TN 38343
172    38343                   2818 Ward Dr, Humboldt, TN 38343
173    38343                242 Woodland Dr, Humboldt, TN 38343
174    38343               80 Olivewood Cv, Three Way, TN 38343
175    38343                2122 Hawks Loop, Humboldt, TN 38343
176    38343                  119 S Main St, Humboldt, TN 38343
177    38343              2810 Pritchard Ln, Humboldt, TN 38343
178    38343               13 Forked Oak Ln, Humboldt, TN 38343
179    38343                         217 St, Humboldt, TN 38343
180    38343                117 Garden Gate, Humboldt, TN 38343
181    38343                 508 N 14th Ave, Humboldt, TN 38343
182    38343                2001 Elliott St, Humboldt, TN 38343
183    38343                  615 N 21st St, Humboldt, TN 38343
184    38343                505 Craddock St, Humboldt, TN 38343
185    38343                 1675 Barker St, Humboldt, TN 38343
186    38343                    Woodgate Dr, Humboldt, TN 38343
187    38343             291 Jim Jackson Rd, Humboldt, TN 38343
188    38343            2846 Chere Carol Rd, Humboldt, TN 38343
189    38343                215 Craddock St, Humboldt, TN 38343
190    38343             105 Garden Gate Dr, Humboldt, TN 38343
191    38343                531 Westview Cv, Humboldt, TN 38343
192    38343   Highway 45W Bypass/Hudson St, Humboldt, TN 38343
193    38343             168 Saddle Tree Dr, Humboldt, TN 38343
194    38343             Highway 152, Crockett County, TN 38343
195    38343                 00B Davenport Rd, Medina, TN 38343
196    38343                   Etheridge St, Humboldt, TN 38343
197    38343                    Craddock St, Humboldt, TN 38343
198    38343                540 Westside Dr, Humboldt, TN 38343
199    38343             176 Saddle Tree Dr, Humboldt, TN 38343
200    38343                85 Olivewood Cv, Humboldt, TN 38343
201    38343                40 Clovewood Cv, Humboldt, TN 38343
202    38343        Hunters Ridge Dr Lot 48, Humboldt, TN 38343
203    38343      5003 Clover Run Dr Lot 46, Humboldt, TN 38343
204    38343  Highway 152 and Porters Grove Church Rd, Humbo...
205    38343                 157 N 28th Ave, Humboldt, TN 38343
206    67505         306 E Avenue F, South Hutchinson, KS 67505
207    67505          8 Savannah Dr, South Hutchinson, KS 67505
208    67505          44 Detroit Dr, South Hutchinson, KS 67505
209    67505              W K50 Hwy, South Hutchinson, KS 67505
210    67505           Blue Stem Dr, South Hutchinson, KS 67505
211    67505        525 N Poplar St, South Hutchinson, KS 67505
212    67505            Bluestem Dr, South Hutchinson, KS 67505
213    67505          Prosperity Dr, South Hutchinson, KS 67505
214    67505          Prosperity Dr, South Hutchinson, KS 67505
215    67505          Prosperity Dr, South Hutchinson, KS 67505
216    67505          Prosperity Dr, South Hutchinson, KS 67505
217    67505           Heartland Dr, South Hutchinson, KS 67505
218    67505             Cypress Ln, South Hutchinson, KS 67505
219    67505          Prosperity Dr, South Hutchinson, KS 67505
220    67505          Prosperity Dr, South Hutchinson, KS 67505
221    67501                20 S Carlo St, Hutchinson, KS 67501
222    67501              1023 College Ln, Hutchinson, KS 67501
223    67501             1307 N Poplar St, Hutchinson, KS 67501
224    67501            316 E Sherman Ave, Hutchinson, KS 67501
225    67501            410 E Sherman Ave, Hutchinson, KS 67501
226    67501                16 E 12th Ave, Hutchinson, KS 67501
227    67501         190 N Green Acres Dr, Hutchinson, KS 67501
228    67501                21 W 14th Ave, Hutchinson, KS 67501
229    67501               608 W 11th Ave, Hutchinson, KS 67501
230    67501               7170 Zolman Rd, Hutchinson, KS 67501
231    67501               113 W 16th Ave, Hutchinson, KS 67501
232    67501               719 E Avenue A, Hutchinson, KS 67501
233    67501               207 E 17th Ave, Hutchinson, KS 67501
234    67501                29 E Avenue F, Hutchinson, KS 67501
235    67501            303 N Westland Dr, Hutchinson, KS 67501
236    67501               1610 E 7th Ave, Hutchinson, KS 67501
237    67501               215 E 15th Ave, Hutchinson, KS 67501
238    67501               120 W 17th Ave, Hutchinson, KS 67501
239    67501               413 E 13th Ave, Hutchinson, KS 67501
240    67501                401 W 9th Ave, Hutchinson, KS 67501
241    67501                610 W 7th Ave, Hutchinson, KS 67501
242    67501            1501 N Harding St, Hutchinson, KS 67501
243    67501             1413 Eastland Dr, Hutchinson, KS 67501
244    67501               500 E Avenue A, Hutchinson, KS 67501
245    67501                225 W 9th Ave, Hutchinson, KS 67501
246    67501               212 E Avenue G, Hutchinson, KS 67501
247    67501                319 E 8th Ave, Hutchinson, KS 67501
248    67501               314 E Avenue G, Hutchinson, KS 67501
249    67501              800 N Monroe St, Hutchinson, KS 67501
250    67501         1220 N Washington St, Hutchinson, KS 67501
251    67501               111 W 13th Ave, Hutchinson, KS 67501
252    67501               315 N Maple St, Hutchinson, KS 67501
253    67501             2413 E Mills Ave, Hutchinson, KS 67501
254    67501                704 Herald St, Hutchinson, KS 67501
255    67501               105 E 12th Ave, Hutchinson, KS 67501
256    67501                514 W 9th Ave, Hutchinson, KS 67501
257    67501              422 E Walker St, Hutchinson, KS 67501
258    67501               409 Liberty St, Hutchinson, KS 67501
259    67501               422 Charles St, Hutchinson, KS 67501
260    67501               301 E 17th Ave, Hutchinson, KS 67501
261    67501               306 E 12th Ave, Hutchinson, KS 67501
262    67501               317 W 14th Ave, Hutchinson, KS 67501
263    67501               2900 W 4th Ave, Hutchinson, KS 67501
264    67501               1007 E 9th Ave, Hutchinson, KS 67501
265    67501             9913 S Mohawk Rd, Hutchinson, KS 67501
266    67501               309 W 17th Ave, Hutchinson, KS 67501
267    67501              8620 S K 14 Hwy, Hutchinson, KS 67501
268    67501            714 Cloverdale Dr, Hutchinson, KS 67501
269    67501               601 W Avenue A, Hutchinson, KS 67501
270    67501               938 E Avenue A, Hutchinson, KS 67501
271    67501           500 N Augustine St, Hutchinson, KS 67501
272    67501             908 N Gregory St, Hutchinson, KS 67501
273    67501         1501 N Clydesdale Dr, Hutchinson, KS 67501
274    67501                  E Bigger St, Hutchinson, KS 67501
275    32254              3504 W 1st St, Jacksonville, FL 32254
276    32254             3110 W 20th St, Jacksonville, FL 32254
277    32254              1027 St Clair, Jacksonville, FL 32254
278    32254             4815 Waller St, Jacksonville, FL 32254
279    32254              3152 Nolan St, Jacksonville, FL 32254
280    32254           1025 Odessa Dr E, Jacksonville, FL 32254
281    32254           1072 Odessa Dr N, Jacksonville, FL 32254
282    32254             934 George Cir, Jacksonville, FL 32254
283    32254          5231 Broadway Ave, Jacksonville, FL 32254
284    32254               825 Dixon St, Jacksonville, FL 32254
285    32254           5246 Potomac Ave, Jacksonville, FL 32254
286    32254            5533 Amazon Ave, Jacksonville, FL 32254

In [248]:
# I saw that two Tyson zips weren't represented below and I found out which ones, and when checking realtor.com
# myself, they have listings. So I'm going to try to run my script again on just those two.

import os
import requests
from bs4 import BeautifulSoup
import pandas as pd
import datetime
import time
import random
import csv
import re

start_time = time.time()

# Defining path
path=r'D:\Adam\Employment\Data Analysis Course\Final Data Project'

# Defining location of zipfile
zipfile = 'D:\Adam\Employment\Data Analysis Course\Final Data Project\Data\Cleaned\TwoTysonZips.csv'

# Open the CSV file that contains the list of zip codes.
with open(zipfile, 'r') as f:
    reader = csv.reader(f)
    zip_codes = list(reader)

data = []    
    
# Loop through the list of zip codes.
for zip_code in zip_codes:
    print(f"Processing zip code: {zip_code[0]}")
    
    # Add a random delay before going to next zip code
    time.sleep(random.randint(30, 90))
    
    # Loop through the page numbers (1-20).
    for page_num in range(1, 20):
        print(f"Processing page {page_num}")
    
        # Update the URL in the script.
        url_template = "https://www.realtor.com/realestateandhomes-search/{}/pg-{}"
        url = url_template.format(zip_code[0], page_num)

        # Set user-agent header to avoid bot detection
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}

        # Add a random delay before making the request
        time.sleep(random.randint(8, 16))

        # Send HTTP GET request to the URL and get the HTML response
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            print("Request successful")
        else:
            print(f"Request failed with status code: {response.status_code}. No more listings pages found.")
            break

        # Parse the HTML response using BeautifulSoup
        soup = BeautifulSoup(response.content, 'html.parser')

        # Find the container for all the properties
        container = soup.find('section', class_='srp-content')

        # Check if the container is empty
        if container is None:
            print("No listings found")
            break

        # Check if the page contains the text "We're Sorry"
        if "We're Sorry" in soup.text:
            print("No more pages")
            break

        # Find all the listings in the container
        listings = container.find_all('div', attrs={'data-label': 'property-card'})

        # Loop through each listing and extract the details
        for listing in listings:
            if listing is not None:
                try:
                    address1 = listing.find('div', attrs={'data-label': 'pc-address'}).text.strip()
                except AttributeError:
                    address1 = ''

                try:
                    address2 = listing.find('div', attrs={'data-label': 'pc-address-second'}).text.strip()
                except AttributeError:
                    address2 = ''

                try:
                    availability = listing.find('span', class_='statusText').text.strip()
                except AttributeError:
                    style = ''

                try:
                    price = listing.find('span', attrs={'data-label': 'pc-price'}).text.strip().replace('From', '').replace(',', '').replace('$', '')
                except AttributeError:
                    price = ''

                try:
                    beds = listing.find('li', attrs={'data-label': 'pc-meta-beds'}).text.strip().replace('bed', '')
                except AttributeError:
                    beds = ''

                try:
                    baths = listing.find('li', attrs={'data-label': 'pc-meta-baths'}).text.strip().replace('bath', '')
                except AttributeError:
                    baths = ''

                try:
                    sqft = listing.find('li', attrs={'data-label': 'pc-meta-sqft'}).text.strip().replace(',', '').split('sqft')[0]
                except AttributeError:
                    sqft = ''

            else:
                print('No listing found.')

            # Appending the data
            data.append([zip_code[0], address1, address2, availability, price, beds, baths, sqft])
       
        # stopping pagination if less than 41 listings found
        if soup.find(id="srp-footer-found-listing") is None:
            print("Not enough listings found for this zip code")
            break
        
        if int(soup.find(id="srp-footer-found-listing").text.strip().split()[1]) < 40:
            print("No more listings found")
            break
        
        else:
            continue
        
    print("Finished processing zip code")

# Create a Pandas dataframe from the extracted data
df = pd.DataFrame(data, columns=['TysonZip', 'Address1', 'Address2', 'Availability', 'Price', 'Beds', 'Baths', 'Sqft'])

# get today's date in the format YYYY-MM-DD
today = datetime.datetime.today().strftime('%Y-%m-%d')

# Export the dataframe to a CSV file
df.to_csv(os.path.join(path, 'Data', 'Scraped', f'2TysonZips_forsale_{today}.csv'), index=False)

# Print the dataframe
print(df)

end_time = time.time()

execution_time = end_time - start_time

print("Execution time:", execution_time)

Processing zip code: 31730
Processing page 1
Request successful
No more listings found
Finished processing zip code
Processing zip code: 76117
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
   TysonZip                                         Address1  \
0     31730           1432 County Line Rd, Camilla, GA 31730
1     31730                53 E Morgan St, Camilla, GA 31730
2     31730               555 Moultrie Rd, Camilla, GA 31730
3     31730                211 S Scott St, Camilla, GA 31730
..      ...                                              ...
89    76117  3516 Tourist Dr, North Richland Hills, TX 76117
90    76117              513 Fieldstone Ln, Haslet, TX 76117
91    76117            4609 Nadine Dr, Haltom City, TX 76117
92    76117     6208 Little Fossil Rd, Haltom City, TX 76117

                          Address2 Availability   Price Beds Baths  Sqft
0                Camilla, GA 31730     For Sale   49500    3     1  1163
1                Camilla, GA 31730     For Sale   53900    3     2  1742
2                Camilla, GA 31730     For Sale  249900    3   2.5  2256
3                Camilla, GA 31730      Pending   69900    3     2  1458
..                             ...          ...     ...  ...   ...   ...
89  North Richland Hills, TX 76117      Pending  114000
90                Haslet, TX 76117     For Sale  589000    4   2.5  2619
91           Haltom City, TX 76117     For Sale  235000    3     2  1245
92           Haltom City, TX 76117     For Sale  165000

[93 rows x 8 columns]
Execution time: 185.35513949394226

In [249]:
# Combining the three lists into a single csv

df_rs1 = pd.read_csv(os.path.join(path, 'Data', 'Scraped', 'TysonZips_forsale_2023-05-05.csv'), index_col = False)
df_rs2 = pd.read_csv(os.path.join(path, 'Data', 'Scraped', 'Tyson_skippedZips_forsale_2023-05-05.csv'), index_col = False)
df_rs3 = pd.read_csv(os.path.join(path, 'Data', 'Scraped', '2TysonZips_forsale_2023-05-05.csv'), index_col = False)

In [253]:
# combining the two dataframes

df_rs = pd.concat([df_rs1, df_rs2, df_rs3])

# resetting the index of the combined dataset
df_rs = df_rs.reset_index(drop=True)

# Making sure TysonZip stays as string (I hope)
df_rs['TysonZip'] = df_rs['TysonZip'].astype(str)

# exporting to a combined csv
df_rs.to_csv(os.path.join(path, 'Data', 'Scraped', f'TysonZips_forsale_combined_{today}.csv'), index=False)

In [254]:
# Importing scraped data
df_rs = pd.read_csv(os.path.join(path, 'Data', 'Scraped', f'TysonZips_forsale_combined_{today}.csv'), dtype={'TysonZip': str}, index_col = False)

### 6B. Consistency Checks

In [255]:
# checking dataset info

df_rs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9248 entries, 0 to 9247
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TysonZip      9248 non-null   object
 1   Address1      9227 non-null   object
 2   Address2      9227 non-null   object
 3   Availability  9248 non-null   object
 4   Price         9248 non-null   object
 5   Beds          6578 non-null   object
 6   Baths         6538 non-null   object
 7   Sqft          6331 non-null   float64
dtypes: float64(1), object(7)
memory usage: 578.1+ KB

These dtypes need to be cleaned up. Before I run my script again, I think I'll code that into the script

In [256]:
print(df_rs['Price'])

0       315000
1        69900
2        84900
3        35000
         ...
9244    114000
9245    589000
9246    235000
9247    165000
Name: Price, Length: 9248, dtype: object

I'm going back and re-using some of this code to make it easier on myself.  The output above no longer has the "From" on some of it because I changed my scraper script, so the section below is from the former implementation of it.

In [145]:
# Need to clean up the way some of those values were created (and later I'll fix that in the scraper script)

df_rs['Price'] = df_rs['Price'].str.replace('From', '')

In [257]:
# Looking for any other strange values in the Price column:

df_rs['Price'].value_counts()

150000     76
275000     71
250000     71
45000      66
           ..
1199995     1
687000      1
829900      1
245500      1
Name: Price, Length: 2645, dtype: int64

In [258]:
# Found a "Contact for Price" row and need to drop the whole row

df_rs.drop(df_rs[df_rs['Price'] == 'Contact For Price'].index, inplace=True)

In [259]:
df_rs['Price'] = df_rs['Price'].astype('float64')

In [260]:
df_rs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9240 entries, 0 to 9247
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TysonZip      9240 non-null   object
 1   Address1      9219 non-null   object
 2   Address2      9219 non-null   object
 3   Availability  9240 non-null   object
 4   Price         9240 non-null   float64
 5   Beds          6573 non-null   object
 6   Baths         6533 non-null   object
 7   Sqft          6327 non-null   float64
dtypes: float64(2), object(6)
memory usage: 649.7+ KB

This looks pretty good now

In [261]:
# Checking for duplicates (and removing them if there are any) - then checking if the numbers change

df_rs.drop_duplicates(inplace=True)

df_rs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8979 entries, 0 to 9244
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TysonZip      8979 non-null   object
 1   Address1      8959 non-null   object
 2   Address2      8959 non-null   object
 3   Availability  8979 non-null   object
 4   Price         8979 non-null   float64
 5   Beds          6431 non-null   object
 6   Baths         6391 non-null   object
 7   Sqft          6188 non-null   float64
dtypes: float64(2), object(6)
memory usage: 631.3+ KB

looks like there were a couple hundred duplicates.  Probably because of the way I re-did some zip codes when the tracker got caught and then combined the two lists.

In [262]:
# Checking for missing values
missing_values = df_rs.isnull().sum()

# total rows in dataframe
total_rows = df_rs.shape[0]

# making it show me all the rows
pd.options.display.max_rows = len(df_rs.dtypes)

# calculating percentage of missing values
percent_missing = ((missing_values / total_rows) * 100).round(2)

# Making a dataframe to show missing values
missing_value_table = pd.concat([missing_values, percent_missing], axis=1)

# Naming columns for sorting
missing_value_table.columns = ['Missing Values', 'Percent Missing']

# sorting the view based on most missing values %
missing_value_table.sort_values('Percent Missing', ascending=True, inplace=True)

print(missing_value_table)

              Missing Values  Percent Missing
TysonZip                   0             0.00
Availability               0             0.00
Price                      0             0.00
Address1                  20             0.22
Address2                  20             0.22
Beds                    2548            28.38
Baths                   2588            28.82
Sqft                    2791            31.08

In [263]:
# Sqft has a lot of missing values, and in looking at it, it appears that all the addresses with missing sqft values are
# just lots for sale. Which I don't believe helps the purpose of this analysis. So I'll remove all of those with missing
# sqft values. I'm not worried much about missing beds and baths info

df_rs.dropna(subset=['Sqft'], inplace=True)

In [264]:
df_rs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6188 entries, 0 to 9242
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TysonZip      6188 non-null   object
 1   Address1      6181 non-null   object
 2   Address2      6181 non-null   object
 3   Availability  6188 non-null   object
 4   Price         6188 non-null   float64
 5   Beds          6132 non-null   object
 6   Baths         6106 non-null   object
 7   Sqft          6188 non-null   float64
dtypes: float64(2), object(6)
memory usage: 435.1+ KB

In [265]:
# Figuring out what the 20 rows with missing addresses are (if they weren't already dropped)

# Select rows with missing values in the "Address1" column
missing_address1 = df_rs[df_rs['Address1'].isna()]

# Print the selected rows
print(missing_address1)

     TysonZip Address1 Address2 Availability     Price Beds Baths    Sqft
1892    39183      NaN      NaN     For Sale   67500.0    2     1   920.0
1924    39183      NaN      NaN      Pending  169900.0    3     2  1500.0
2132    72756      NaN      NaN     For Sale  399950.0    2     1  1104.0
3374    30040      NaN      NaN     For Sale  645000.0    5     4  3156.0
6452    78155      NaN      NaN     For Sale  154999.0    4     2  1176.0
7047    78155      NaN      NaN     For Sale  295000.0    3     2  1188.0
7725    72802      NaN      NaN      Pending  160000.0    3     1  1120.0

In [266]:
# Interestingly they have info without addresses.  I'm just going to drop them

df_rs.dropna(subset=['Address1'], inplace=True)

In [267]:
df_rs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6181 entries, 0 to 9242
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TysonZip      6181 non-null   object
 1   Address1      6181 non-null   object
 2   Address2      6181 non-null   object
 3   Availability  6181 non-null   object
 4   Price         6181 non-null   float64
 5   Beds          6125 non-null   object
 6   Baths         6099 non-null   object
 7   Sqft          6181 non-null   float64
dtypes: float64(2), object(6)
memory usage: 434.6+ KB

In [268]:
# counting number of unique values in each column

print(df_rs.nunique())

TysonZip          95
Address1        6161
Address2         274
Availability       5
Price           2070
Beds              20
Baths             33
Sqft            2324
dtype: int64

The number of different unique values in Beds and in Baths is surprising. I'll have to look that up later during the basic statisical analysis

### 6C. Data Cleaning

In [269]:
# I need to split up the Address2 data.  I'm not sure that the Address1 data is important for my goals so I'll only
# wrangle that later if I need to

df_rs['City'] = df_rs['Address2'].str.split(',', expand=True)[0]

In [270]:
# Now I'm making a new column for the state abbreviation

df_rs['State'] = df_rs['Address2'].str.split(', ', expand=True)[1]
df_rs['State'] = df_rs['State'].str.split(' ', expand=True)[0]

In [271]:
# Now I'm going to try to do that with zip code. Though I know some didn't capture zip code, but hopefully I won't have an error

df_rs['Zip'] = df_rs['Address2'].str.split(', ', expand=True)[1]
df_rs['Zip'] = df_rs['Zip'].str.split(' ', expand=True)[1]

In [272]:
df_rs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6181 entries, 0 to 9242
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TysonZip      6181 non-null   object
 1   Address1      6181 non-null   object
 2   Address2      6181 non-null   object
 3   Availability  6181 non-null   object
 4   Price         6181 non-null   float64
 5   Beds          6125 non-null   object
 6   Baths         6099 non-null   object
 7   Sqft          6181 non-null   float64
 8   City          6181 non-null   object
 9   State         6181 non-null   object
 10  Zip           5606 non-null   object
dtypes: float64(2), object(9)
memory usage: 579.5+ KB

Looks like it worked great!

### 6D. Basic Descriptive Analysis

In [273]:
# Checking basic stats on each column

# making it show me all the rows
pd.options.display.max_rows = len(df_rs.dtypes)

df_rs.describe().applymap(lambda x: f"{x:0.2f}")

             Price       Sqft
count      6181.00    6181.00
mean     399690.81    2123.99
std      644334.08    3757.50
min           1.00     288.00
25%      209900.00    1390.00
50%      305550.00    1808.00
75%      450000.00    2438.00
max    38500000.00  256672.00

I'd say that these results look about right, but the max values are pretty crazy!

In [274]:
# Now I'm going to count unique values in each object column

df_rs['Address1'].value_counts()

68 Ogden Rd, Broken Bow, OK 74728            2
116 S Union St, Traverse City, MI 49684      2
1205 Secrest Commons Dr, Monroe, NC 28112    2
23 Double Oak Dr, Broken Bow, OK 74728       2
1208 Secrest Commons Dr, Monroe, NC 28112    2
                                            ..
618 Prairie Blvd, Dakota Dunes, SD 57049     1
Elm, Dakota City, NE 68731                   1
1307 Mulberry St, Dakota City, NE 68731      1
603 S 20th St, Dakota City, NE 68731         1
4701 Kindred St, Haltom City, TX 76117       1
Name: Address1, Length: 6161, dtype: int64

In [275]:
# dropping houses with duplicate addresses and sqft listed

df_rs.drop_duplicates(subset=['Address1', 'Sqft'], inplace=True)

In [276]:
df_rs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6173 entries, 0 to 9242
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TysonZip      6173 non-null   object
 1   Address1      6173 non-null   object
 2   Address2      6173 non-null   object
 3   Availability  6173 non-null   object
 4   Price         6173 non-null   float64
 5   Beds          6117 non-null   object
 6   Baths         6091 non-null   object
 7   Sqft          6173 non-null   float64
 8   City          6173 non-null   object
 9   State         6173 non-null   object
 10  Zip           5598 non-null   object
dtypes: float64(2), object(9)
memory usage: 578.7+ KB

In [277]:
df_rs['Address1'].value_counts()

162 Pr # 3358, Clarksville, AR 72830         2
170 Pr # 3397, Clarksville, AR 72830         2
1205 Secrest Commons Dr, Monroe, NC 28112    2
3143 AR Highway 174, Hope, AR 71801          2
1208 Secrest Commons Dr, Monroe, NC 28112    2
                                            ..
4955 Stallions Gait Rd, Cumming, GA 30040    1
4315 Alister Park Dr, Cumming, GA 30040      1
3160 Amble Valley Ave, Cumming, GA 30040     1
4915 Stallions Gait Rd, Cumming, GA 30040    1
4701 Kindred St, Haltom City, TX 76117       1
Name: Address1, Length: 6161, dtype: int64

In [278]:
# Making list of duplicates

duplicates_rs = df_rs[df_rs.duplicated(['Address1'], keep=False)]

# making it show me all the rows
pd.options.display.max_rows = len(duplicates_rs)

print(duplicates_rs)

     TysonZip                                     Address1  \
880     74728     17 Happy Place Cir, Broken Bow, OK 74728
888     74728       23 Double Oak Dr, Broken Bow, OK 74728
1052    74728     17 Happy Place Cir, Broken Bow, OK 74728
1088    74728       16 Double Oak Dr, Broken Bow, OK 74728
1193    74728       23 Double Oak Dr, Broken Bow, OK 74728
1205    74728       16 Double Oak Dr, Broken Bow, OK 74728
2477    72830         162 Pr # 3358, Clarksville, AR 72830
2487    72830         162 Pr # 3358, Clarksville, AR 72830
2495    72830         170 Pr # 3397, Clarksville, AR 72830
2518    72830         170 Pr # 3397, Clarksville, AR 72830
2891    49684  810 Cottageview Dr, Traverse City, MI 49684
2922    49684  810 Cottageview Dr, Traverse City, MI 49684
4702    71801          3143 AR Highway 174, Hope, AR 71801
4710    71801          3143 AR Highway 174, Hope, AR 71801
5243    28112    1303 Secrest Commons Dr, Monroe, NC 28112
5265    28112    1240 Secrest Commons Dr, Monroe, NC 28112
5275    28112    1217 Secrest Commons Dr, Monroe, NC 28112
5278    28112    1208 Secrest Commons Dr, Monroe, NC 28112
5280    28112    1205 Secrest Commons Dr, Monroe, NC 28112
5348    28112    1217 Secrest Commons Dr, Monroe, NC 28112
5383    28112    1205 Secrest Commons Dr, Monroe, NC 28112
5387    28112    1303 Secrest Commons Dr, Monroe, NC 28112
5389    28112    1208 Secrest Commons Dr, Monroe, NC 28112
5398    28112    1240 Secrest Commons Dr, Monroe, NC 28112

                     Address2 Availability      Price Beds Baths    Sqft  \
880      Broken Bow, OK 74728     For Sale  3499000.0    9     9  3000.0
888      Broken Bow, OK 74728     For Sale   333000.0    1     1   320.0
1052     Broken Bow, OK 74728     For Sale  3499000.0    9     9  1500.0
1088     Broken Bow, OK 74728     For Sale   433000.0    2     2   480.0
1193     Broken Bow, OK 74728     For Sale   504000.0    2     2   560.0
1205     Broken Bow, OK 74728     For Sale   333000.0    1     1   320.0
2477    Clarksville, AR 72830     For Sale    84900.0    3     2  1819.0
2487    Clarksville, AR 72830     For Sale    84900.0    3     2  2879.0
2495    Clarksville, AR 72830     For Sale   169900.0    3     2  1500.0
2518    Clarksville, AR 72830     For Sale   159900.0    3     2  1400.0
2891  Traverse City, MI 49684     For Sale   515000.0    3   NaN  2294.0
2922  Traverse City, MI 49684     For Sale   685000.0    3     1  3310.0
4702           Hope, AR 71801     For Sale   240000.0    4     3  3360.0
4710           Hope, AR 71801     For Sale   240000.0    4     3  2582.0
5243         Monroe, NC 28112     For Sale   412090.0    4   2.5  2565.0
5265         Monroe, NC 28112     For Sale   407590.0    4   2.5  2565.0
5275         Monroe, NC 28112     For Sale   406590.0    4   2.5  2565.0
5278         Monroe, NC 28112      Pending   409590.0    4   2.5  2565.0
5280         Monroe, NC 28112     For Sale   407090.0    4   2.5  2565.0
5348         Monroe, NC 28112     For Sale   406590.0    4   3.5  2546.0
5383         Monroe, NC 28112     For Sale   407090.0    4   3.5  2546.0
5387         Monroe, NC 28112     For Sale   412090.0    4   3.5  2546.0
5389         Monroe, NC 28112      Pending   409590.0    4   3.5  2546.0
5398         Monroe, NC 28112     For Sale   407590.0    4   3.5  2546.0

               City State    Zip
880      Broken Bow    OK  74728
888      Broken Bow    OK  74728
1052     Broken Bow    OK  74728
1088     Broken Bow    OK  74728
1193     Broken Bow    OK  74728
1205     Broken Bow    OK  74728
2477    Clarksville    AR  72830
2487    Clarksville    AR  72830
2495    Clarksville    AR  72830
2518    Clarksville    AR  72830
2891  Traverse City    MI  49684
2922  Traverse City    MI  49684
4702           Hope    AR  71801
4710           Hope    AR  71801
5243         Monroe    NC  28112
5265         Monroe    NC  28112
5275         Monroe    NC  28112
5278         Monroe    NC  28112
5280         Monroe    NC  28112
5348         Monroe    NC  28112
5383         Monroe    NC  28112
5387         Monroe    NC  28112
5389         Monroe    NC  28112
5398         Monroe    NC  28112

That doesn't seem to have gotten rid of all the duplicates, but I'm going to keep it as-is for now, because I'm not sure what's causing them.

In [279]:
# Now I'm going to count unique values in each object column

df_rs['Address2'].value_counts()

Seguin, TX 78155           450
Broken Bow, OK 74728       311
Fayetteville, AR 72704     293
Seguin, TX                 263
Bowling Green, KY 42101    221
                          ...
Eltopia, WA 99301            1
Allen, TX 75013              1
Arlington, TX 76018          1
Dallas, TX 75223             1
Dallas, TX 75204             1
Name: Address2, Length: 274, dtype: int64

In [280]:
# Now I'm going to count unique values in each object column

df_rs['Availability'].value_counts()

For Sale       4000
Pending        1780
Contingent      376
Foreclosure      12
Coming Soon       5
Name: Availability, dtype: int64

In [281]:
# Now I'm going to count unique values in each object column

# making it show me all the rows
pd.options.display.max_rows = len(df_rs['Beds'])

df_rs['Beds'].value_counts()

3         2871
4         1715
2          772
5          436
1          111
6           86
3.0         44
7           21
8           12
Studio      12
2.0         12
4.0         11
9            4
5.0          2
12           2
14           2
13           1
41           1
155          1
6.0          1
Name: Beds, dtype: int64

In [282]:
print(df_rs[df_rs['Beds'] == '155'])

     TysonZip                                           Address1  \
2427    28610  2675 Bethlehem Dr Unit Portfolio, Claremont, N...

                 Address2 Availability      Price Beds  Baths     Sqft  \
2427  Claremont, NC 28610      Pending  8567000.0  155  86.5+  74945.0

           City State    Zip
2427  Claremont    NC  28610

74,000 sqft - a whole apartment complex I guess.  I'll take it off the list, as it's not a normal house for someone to buy.

In [283]:
print(df_rs[df_rs['Beds'] == '41'])

     TysonZip                         Address1          Address2 Availability  \
5360    28112  708 Cotton St, Monroe, NC 28112  Monroe, NC 28112      Pending

          Price Beds Baths     Sqft    City State    Zip
5360  3000000.0   41    41  43800.0  Monroe    NC  28112

In [288]:
print(df_rs[df_rs['Beds'] == '3.0'])

     TysonZip                                           Address1  \
9155    31730             1432 County Line Rd, Camilla, GA 31730
9156    31730                  53 E Morgan St, Camilla, GA 31730
9157    31730                 555 Moultrie Rd, Camilla, GA 31730
9158    31730                  211 S Scott St, Camilla, GA 31730
9159    31730              2989 Old Pelham Rd, Camilla, GA 31730
9165    31730                49 E Thompson St, Camilla, GA 31730
9167    31730                196 Macdonald St, Camilla, GA 31730
9172    31730               375 E Camellia Dr, Camilla, GA 31730
9174    31730                   64 Scott St S, Camilla, GA 31730
9175    31730              4558 Friendship Rd, Camilla, GA 31730
9176    31730                  110 Dogwood St, Camilla, GA 31730
9177    31730                199 Macdonald St, Camilla, GA 31730
9178    31730                     64 Scott St, Camilla, GA 31730
9179    31730              367 County Line Rd, Camilla, GA 31730
9185    76117              5813 Midway Rd, Haltom City, TX 76117
9186    76117              5416 Nadine Dr, Haltom City, TX 76117
9187    76117              4609 Nadine Dr, Haltom City, TX 76117
9189    76117              3629 Cheryl St, Haltom City, TX 76117
9191    76117               3204 Edith Ln, Haltom City, TX 76117
9194    76117               3000 Edith Ln, Haltom City, TX 76117
9196    76117        5102 Springlake Pkwy, Haltom City, TX 76117
9197    76117           4625 Starlight Dr, Haltom City, TX 76117
9199    76117    5940 Tourist Dr, North Richland Hills, TX 76117
9200    76117               3313 Earle Dr, Haltom City, TX 76117
9201    76117               3405 Edith Ln, Haltom City, TX 76117
9202    76117              3925 Janrue Ct, Haltom City, TX 76117
9206    76117              4213 Haltom Rd, Haltom City, TX 76117
9207    76117           3512 Eastridge Dr, Haltom City, TX 76117
9211    76117              5036 Nadine Dr, Haltom City, TX 76117
9212    76117               3013 Edith Ln, Haltom City, TX 76117
9213    76117            4121 Maryview Ct, Haltom City, TX 76117
9214    76117     3709 Matson St, North Richland Hills, TX 76117
9216    76117              3304 Aurora St, Haltom City, TX 76117
9219    76117              5021 Nadine Dr, Haltom City, TX 76117
9220    76117             5316 Madella St, Haltom City, TX 76117
9223    76117             4412 Wayne Ct N, Haltom City, TX 76117
9224    76117  Rhodes Plan, Heritage Village CommunityHaltom ...
9226    76117  Loyola Plan, Heritage Village CommunityHaltom ...
9227    76117        5416 Bonnie Wayne St, Haltom City, TX 76117
9230    76117             4316 Joy Lee St, Haltom City, TX 76117
9231    76117      4704 Simple Pathway St, Haltom City, TX 76117
9232    76117                3517 Jane Ln, Haltom City, TX 76117
9233    76117             2019 Layton Ave, Haltom City, TX 76117
9234    76117      5235 Stanley Keller Rd, Haltom City, TX 76117

                            Address2 Availability     Price Beds Baths  \
9155               Camilla, GA 31730     For Sale   49500.0  3.0   1.0
9156               Camilla, GA 31730     For Sale   53900.0  3.0   2.0
9157               Camilla, GA 31730     For Sale  249900.0  3.0   2.5
9158               Camilla, GA 31730      Pending   69900.0  3.0   2.0
9159               Camilla, GA 31730     For Sale  495000.0  3.0   2.0
9165               Camilla, GA 31730     For Sale   79900.0  3.0   2.0
9167               Camilla, GA 31730     For Sale   69900.0  3.0   2.0
9172               Camilla, GA 31730     For Sale  119000.0  3.0   2.0
9174               Camilla, GA 31730     For Sale   69900.0  3.0   1.0
9175               Camilla, GA 31730     For Sale  695900.0  3.0   3.0
9176               Camilla, GA 31730      Pending  165000.0  3.0   2.5
9177               Camilla, GA 31730     For Sale   54900.0  3.0   1.0
9178               Camilla, GA 31730     For Sale   69900.0  3.0   1.0
9179               Camilla, GA 31730      Pending  279900.0  3.0   2.0
9185           Haltom City, TX 76117     For Sale  245000.0  3.0   1.0
9186           Haltom City, TX 76117     For Sale  268612.0  3.0   2.0
9187           Haltom City, TX 76117     For Sale  235000.0  3.0   2.0
9189           Haltom City, TX 76117     For Sale  230000.0  3.0   1.0
9191           Haltom City, TX 76117     For Sale  259000.0  3.0   1.0
9194           Haltom City, TX 76117     For Sale  250000.0  3.0   1.5
9196           Haltom City, TX 76117     For Sale  319000.0  3.0   2.5
9197           Haltom City, TX 76117   Contingent  240000.0  3.0   2.0
9199  North Richland Hills, TX 76117   Contingent  274900.0  3.0   2.0
9200           Haltom City, TX 76117      Pending  220000.0  3.0   2.0
9201           Haltom City, TX 76117      Pending  150000.0  3.0   1.5
9202           Haltom City, TX 76117      Pending  250000.0  3.0   1.5
9206           Haltom City, TX 76117     For Sale  275000.0  3.0   2.0
9207           Haltom City, TX 76117      Pending  239000.0  3.0   2.0
9211           Haltom City, TX 76117      Pending  235000.0  3.0   1.0
9212           Haltom City, TX 76117      Pending  244000.0  3.0   1.5
9213           Haltom City, TX 76117   Contingent  299000.0  3.0   2.0
9214  North Richland Hills, TX 76117      Pending  280000.0  3.0   2.0
9216           Haltom City, TX 76117     For Sale  265000.0  3.0   1.0
9219           Haltom City, TX 76117      Pending  222000.0  3.0   1.5
9220           Haltom City, TX 76117      Pending  294500.0  3.0   2.0
9223           Haltom City, TX 76117     For Sale  245500.0  3.0   1.0
9224                 Haltom City, TX     For Sale  360990.0  3.0   2.5
9226                 Haltom City, TX     For Sale  326990.0  3.0   2.5
9227           Haltom City, TX 76117      Pending  264999.0  3.0   2.0
9230           Haltom City, TX 76117      Pending  254000.0  3.0   2.0
9231           Haltom City, TX 76117      Pending  349000.0  3.0   2.0
9232           Haltom City, TX 76117      Pending  249700.0  3.0   1.0
9233           Haltom City, TX 76117      Pending  250000.0  3.0   2.0
9234           Haltom City, TX 76117      Pending  220000.0  3.0   1.0

        Sqft                  City State    Zip
9155  1163.0               Camilla    GA  31730
9156  1742.0               Camilla    GA  31730
9157  2256.0               Camilla    GA  31730
9158  1458.0               Camilla    GA  31730
9159  2673.0               Camilla    GA  31730
9165  1600.0               Camilla    GA  31730
9167  1504.0               Camilla    GA  31730
9172  1537.0               Camilla    GA  31730
9174  1598.0               Camilla    GA  31730
9175  2100.0               Camilla    GA  31730
9176  1680.0               Camilla    GA  31730
9177  1039.0               Camilla    GA  31730
9178  1598.0               Camilla    GA  31730
9179  2289.0               Camilla    GA  31730
9185  1106.0           Haltom City    TX  76117
9186  1456.0           Haltom City    TX  76117
9187  1245.0           Haltom City    TX  76117
9189  1152.0           Haltom City    TX  76117
9191  1456.0           Haltom City    TX  76117
9194  1750.0           Haltom City    TX  76117
9196  1438.0           Haltom City    TX  76117
9197  1888.0           Haltom City    TX  76117
9199  1741.0  North Richland Hills    TX  76117
9200  1259.0           Haltom City    TX  76117
9201  1104.0           Haltom City    TX  76117
9202  1196.0           Haltom City    TX  76117
9206  1218.0           Haltom City    TX  76117
9207  1204.0           Haltom City    TX  76117
9211  1284.0           Haltom City    TX  76117
9212  1288.0           Haltom City    TX  76117
9213  2846.0           Haltom City    TX  76117
9214  1319.0  North Richland Hills    TX  76117
9216  1505.0           Haltom City    TX  76117
9219  1340.0           Haltom City    TX  76117
9220  1565.0           Haltom City    TX  76117
9223  1360.0           Haltom City    TX  76117
9224  1820.0           Haltom City    TX   None
9226  1413.0           Haltom City    TX   None
9227  1467.0           Haltom City    TX  76117
9230  1768.0           Haltom City    TX  76117
9231  1573.0           Haltom City    TX  76117
9232  1180.0           Haltom City    TX  76117
9233  1095.0           Haltom City    TX  76117
9234   960.0           Haltom City    TX  76117

In [286]:
# Dropping rows with too many beds (i.e. apartment complexes or the like)

df_rs.drop(df_rs[df_rs['Beds'] == '155'].index, inplace=True)
df_rs.drop(df_rs[df_rs['Beds'] == '41'].index, inplace=True)

In [287]:
df_rs['Beds'].value_counts()

3         2871
4         1715
2          772
5          436
1          111
6           86
3.0         44
7           21
8           12
Studio      12
2.0         12
4.0         11
9            4
5.0          2
14           2
12           2
13           1
6.0          1
Name: Beds, dtype: int64

In [289]:
# Replacing those values with periods with the normal values

df_rs['Beds'] = df_rs['Beds'].replace({'3.0': '3', '2.0': '2', '1.0': '1', '4.0': '4', '5.0': '5', '6.0': '6'})

In [290]:
df_rs['Beds'].value_counts()

3         2915
4         1726
2          784
5          438
1          111
6           87
7           21
8           12
Studio      12
9            4
12           2
14           2
13           1
Name: Beds, dtype: int64

In [291]:
df_rs['Baths'].value_counts()

2       2371
2.5      997
1        846
3        781
3.5      379
1.5      254
4        156
4.5       92
2.0       33
5.5       30
5         26
3.5+      23
4.5+      18
1.0       18
2.5+      16
1.5+       9
6.5        8
5.5+       6
6          5
6.5+       3
3.0        3
9          2
9.5        2
8          2
0.5+       2
7          2
7.5        1
15         1
7.5+       1
0.5        1
4.0        1
Name: Baths, dtype: int64

In [294]:
# Replacing those values with periods with the normal values

df_rs['Baths'] = df_rs['Baths'].replace({'3.0': '3', '2.0': '2', '1.0': '1', '4.0': '4'})

# I'm going to do that with the + values too

df_rs['Baths'] = df_rs['Baths'].replace({'3.5+': '3.5', '4.5+': '4.5', '2.5+': '2.5', '1.5+': '1.5', '5.5+': '5.5', '6.5+': '6.5', '0.5+': '0.5', '7.5+': '7.5'})

In [295]:
df_rs['Baths'].value_counts()

2      2404
2.5    1013
1       864
3       784
3.5     402
1.5     263
4       157
4.5     110
5.5      36
5        26
6.5      11
6         5
0.5       3
9.5       2
8         2
7.5       2
9         2
7         2
15        1
Name: Baths, dtype: int64

This seems likely to be accurate enough

In [296]:
print(df_rs[df_rs['Baths'] == '15'])

     TysonZip                                     Address1  \
2534    72830  342 County Road 3446, Clarksville, AR 72830

                   Address2 Availability    Price Beds Baths    Sqft  \
2534  Clarksville, AR 72830      Pending  27000.0    3    15  1216.0

             City State    Zip
2534  Clarksville    AR  72830

In [297]:
# I checked the address for the one with 15 beds and it was clearly a mistake. So changing it here.

df_rs.loc[df_rs['Beds'] == '15', 'Beds'] = '1.5'

In [298]:
df_rs['Sqft'].value_counts()

1800.0      31
1200.0      31
1500.0      28
1400.0      24
1344.0      23
2000.0      21
960.0       20
2400.0      18
1688.0      18
1300.0      18
1440.0      18
1600.0      18
1680.0      18
1983.0      17
1248.0      17
1000.0      17
1487.0      17
1350.0      16
1456.0      16
2500.0      15
1347.0      15
1636.0      15
1862.0      15
1792.0      15
1152.0      15
1120.0      14
2100.0      14
1567.0      14
1512.0      14
2200.0      13
1056.0      13
2174.0      13
1568.0      13
1910.0      13
1796.0      13
2300.0      13
1700.0      13
1560.0      13
1790.0      13
2304.0      13
1626.0      12
1080.0      12
1280.0      12
900.0       12
1750.0      12
1217.0      12
2511.0      12
1250.0      12
1618.0      12
1266.0      12
1958.0      11
2368.0      11
720.0       11
1830.0      11
924.0       11
2601.0      11
1474.0      11
1296.0      11
1740.0      11
1092.0      11
1699.0      11
1008.0      11
1292.0      11
1050.0      10
1850.0      10
1667.0      10
1595.0      10
1459.0      10
1104.0      10
816.0       10
1040.0      10
1176.0      10
1475.0      10
1230.0      10
2250.0      10
1634.0       9
1442.0       9
1326.0       9
3000.0       9
2016.0       9
1260.0       9
912.0        9
1612.0       9
864.0        9
1216.0       9
2347.0       9
1729.0       9
2160.0       9
2565.0       9
1565.0       8
1587.0       8
1675.0       8
2800.0       8
1900.0       8
2042.0       8
1392.0       8
1450.0       8
1687.0       8
2030.0       8
1728.0       8
1536.0       8
952.0        8
1670.0       8
1686.0       8
1240.0       8
1950.0       8
1574.0       8
2372.0       8
1632.0       8
1384.0       8
2050.0       7
1960.0       7
2188.0       7
1480.0       7
1701.0       7
1290.0       7
1360.0       7
1232.0       7
1984.0       7
1575.0       7
1712.0       7
840.0        7
1356.0       7
1420.0       7
1466.0       7
832.0        7
1476.0       7
1644.0       7
1320.0       7
2744.0       7
2296.0       7
792.0        7
1744.0       7
1640.0       7
1580.0       7
2324.0       7
1518.0       7
1298.0       7
1368.0       7
2675.0       7
904.0        7
1955.0       7
1664.0       7
1404.0       7
1100.0       7
1720.0       7
2546.0       7
2797.0       7
1472.0       7
1458.0       7
1824.0       6
1659.0       6
2694.0       6
2600.0       6
2260.0       6
2019.0       6
1620.0       6
1390.0       6
784.0        6
1992.0       6
3300.0       6
2025.0       6
2607.0       6
1976.0       6
2087.0       6
1048.0       6
2184.0       6
1406.0       6
1212.0       6
950.0        6
1328.0       6
672.0        6
1376.0       6
992.0        6
1288.0       6
1504.0       6
1516.0       6
1272.0       6
2055.0       6
1510.0       6
2373.0       6
2737.0       6
2275.0       6
1446.0       6
1585.0       6
1832.0       6
2062.0       6
1916.0       6
1024.0       6
1968.0       6
1576.0       6
1412.0       6
1685.0       6
884.0        6
2152.0       6
1815.0       6
1525.0       6
2666.0       6
1820.0       6
1256.0       6
1911.0       6
1144.0       6
1645.0       6
1044.0       6
1808.0       6
1263.0       6
2041.0       6
896.0        6
1874.0       6
1757.0       6
2280.0       6
928.0        6
2069.0       6
3200.0       6
1496.0       6
1150.0       6
1966.0       6
2164.0       6
2820.0       6
1467.0       6
1743.0       6
2132.0       6
1776.0       6
2144.0       5
2080.0       5
2354.0       5
1095.0       5
1308.0       5
2545.0       5
923.0        5
1064.0       5
1332.0       5
2112.0       5
1257.0       5
2656.0       5
1424.0       5
1915.0       5
2192.0       5
3500.0       5
1572.0       5
1398.0       5
780.0        5
800.0        5
1868.0       5
1460.0       5
1432.0       5
1888.0       5
2228.0       5
2626.0       5
1540.0       5
2124.0       5
1764.0       5
1408.0       5
2480.0       5
1528.0       5
1261.0       5
1616.0       5
1842.0       5
1755.0       5
1096.0       5
1358.0       5
1422.0       5
1566.0       5
1196.0       5
1604.0       5
1441.0       5
2408.0       5
1931.0       5
936.0        5
2943.0       5
1794.0       5
1264.0       5
1556.0       5
2162.0       5
2261.0       5
1722.0       5
1624.0       5
1365.0       5
2512.0       5
1651.0       5
2739.0       5
1140.0       5
1848.0       5
1586.0       5
1160.0       5
2535.0       5
1814.0       5
1786.0       5
1352.0       5
2351.0       5
1927.0       5
2026.0       5
1609.0       5
2700.0       5
2017.0       5
2254.0       5
1116.0       5
1396.0       5
1520.0       5
1234.0       5
1501.0       5
1802.0       5
1439.0       5
4400.0       5
624.0        5
1702.0       5
1380.0       5
2004.0       5
1788.0       5
1920.0       5
925.0        5
1334.0       5
2064.0       5
980.0        5
1036.0       5
2507.0       5
1348.0       5
2603.0       5
4200.0       5
988.0        5
1172.0       5
2079.0       5
2140.0       5
1902.0       5
2544.0       5
1809.0       5
1340.0       5
1836.0       5
2034.0       5
2040.0       5
1806.0       5
972.0        4
2880.0       4
1488.0       4
968.0        4
1642.0       4
1898.0       4
1180.0       4
1105.0       4
1775.0       4
2437.0       4
1778.0       4
1860.0       4
1932.0       4
1948.0       4
1845.0       4
2138.0       4
1957.0       4
1341.0       4
5000.0       4
2450.0       4
2806.0       4
2294.0       4
2092.0       4
1247.0       4
1336.0       4
1660.0       4
3400.0       4
2127.0       4
1598.0       4
4000.0       4
2175.0       4
1485.0       4
1409.0       4
1433.0       4
1530.0       4
1742.0       4
2109.0       4
888.0        4
2149.0       4
2420.0       4
1772.0       4
2711.0       4
2227.0       4
2088.0       4
1863.0       4
1364.0       4
1268.0       4
1545.0       4
2378.0       4
1204.0       4
2217.0       4
1781.0       4
2032.0       4
2342.0       4
2343.0       4
1161.0       4
1032.0       4
2098.0       4
2445.0       4
3055.0       4
1020.0       4
1469.0       4
1762.0       4
1228.0       4
2817.0       4
1725.0       4
1407.0       4
1303.0       4
576.0        4
1880.0       4
2219.0       4
2364.0       4
2505.0       4
2172.0       4
3062.0       4
1414.0       4
3184.0       4
2495.0       4
1548.0       4
1780.0       4
3546.0       4
1795.0       4
1330.0       4
2286.0       4
2008.0       4
1940.0       4
2754.0       4
2319.0       4
1592.0       4
2052.0       4
1805.0       4
1614.0       4
2404.0       4
2263.0       4
2044.0       4
3800.0       4
1451.0       4
2104.0       4
1012.0       4
2153.0       4
1259.0       4
728.0        4
2614.0       4
2078.0       4
1370.0       4
1615.0       4
2750.0       4
2664.0       4
1928.0       4
1696.0       4
1062.0       4
1844.0       4
1890.0       4
1584.0       4
1270.0       4
1875.0       4
1041.0       4
1305.0       4
2235.0       4
1967.0       4
2128.0       4
2356.0       4
2350.0       4
2216.0       4
1047.0       4
2370.0       4
2568.0       4
1770.0       4
2570.0       4
2411.0       4
1253.0       4
1386.0       4
1511.0       4
1974.0       4
2513.0       4
2012.0       4
2142.0       4
2440.0       4
1434.0       4
1908.0       4
1319.0       4
2157.0       4
2119.0       4
1188.0       4
2292.0       4
1647.0       4
2360.0       4
1557.0       4
1242.0       4
1202.0       4
1497.0       4
1026.0       4
1736.0       4
1930.0       4
1754.0       4
768.0        4
1710.0       4
1870.0       4
1590.0       4
1650.0       4
1716.0       4
1760.0       4
1231.0       4
1167.0       4
876.0        4
2428.0       4
1168.0       4
2710.0       4
1208.0       4
1692.0       4
1214.0       4
1627.0       4
1782.0       4
917.0        4
3043.0       3
1550.0       3
2460.0       3
3697.0       3
2251.0       3
3212.0       3
1215.0       3
1514.0       3
2332.0       3
3570.0       3
1468.0       3
2001.0       3
1579.0       3
2693.0       3
1936.0       3
1431.0       3
1067.0       3
2720.0       3
2389.0       3
1925.0       3
1904.0       3
1532.0       3
2472.0       3
1934.0       3
1912.0       3
2009.0       3
3530.0       3
2702.0       3
1638.0       3
2189.0       3
3614.0       3
2029.0       3
2213.0       3
600.0        3
2695.0       3
1816.0       3
1112.0       3
2058.0       3
1163.0       3
1593.0       3
3393.0       3
2095.0       3
2782.0       3
1864.0       3
2328.0       3
2960.0       3
1284.0       3
3630.0       3
1837.0       3
2438.0       3
1596.0       3
1724.0       3
1591.0       3
2998.0       3
2900.0       3
990.0        3
2627.0       3
2783.0       3
1287.0       3
2108.0       3
2624.0       3
1405.0       3
1028.0       3
1827.0       3
2425.0       3
1865.0       3
1375.0       3
2388.0       3
2592.0       3
1148.0       3
1452.0       3
1787.0       3
2954.0       3
1205.0       3
1229.0       3
3223.0       3
3029.0       3
886.0        3
1006.0       3
2911.0       3
2631.0       3
1896.0       3
1535.0       3
2808.0       3
1416.0       3
2653.0       3
1039.0       3
1759.0       3
1058.0       3
2020.0       3
1858.0       3
2457.0       3
1681.0       3
1419.0       3
1752.0       3
1479.0       3
836.0        3
2024.0       3
3040.0       3
2529.0       3
1211.0       3
2816.0       3
2208.0       3
1254.0       3
3508.0       3
1872.0       3
2860.0       3
1798.0       3
850.0        3
1526.0       3
1803.0       3
1413.0       3
1158.0       3
2240.0       3
1315.0       3
2485.0       3
1374.0       3
1821.0       3
2648.0       3
1980.0       3
2156.0       3
1218.0       3
1470.0       3
2696.0       3
1894.0       3
1559.0       3
1274.0       3
2941.0       3
4913.0       3
2085.0       3
1741.0       3
1854.0       3
2972.0       3
2956.0       3
2023.0       3
2752.0       3
3675.0       3
2552.0       3
1873.0       3
3732.0       3
2784.0       3
2264.0       3
3168.0       3
2788.0       3
1674.0       3
2392.0       3
2097.0       3
1879.0       3
2048.0       3
1156.0       3
1220.0       3
2270.0       3
2647.0       3
1706.0       3
3032.0       3
1569.0       3
1381.0       3
1415.0       3
2337.0       3
1767.0       3
1697.0       3
2305.0       3
3576.0       3
1279.0       3
1676.0       3
1189.0       3
1739.0       3
1988.0       3
976.0        3
1088.0       3
2306.0       3
880.0        3
2942.0       3
2190.0       3
2186.0       3
1072.0       3
1732.0       3
2760.0       3
1342.0       3
3700.0       3
1421.0       3
1855.0       3
1665.0       3
1224.0       3
1978.0       3
2672.0       3
1226.0       3
1544.0       3
2804.0       3
934.0        3
480.0        3
2828.0       3
1484.0       3
1395.0       3
2576.0       3
1102.0       3
1445.0       3
1483.0       3
3600.0       3
2194.0       3
1502.0       3
1402.0       3
4900.0       3
1495.0       3
3342.0       3
1727.0       3
3048.0       3
1909.0       3
2320.0       3
2232.0       3
1436.0       3
1430.0       3
1937.0       3
1124.0       3
1505.0       3
815.0        3
1085.0       3
1892.0       3
1178.0       3
1876.0       3
1391.0       3
1959.0       3
2508.0       3
1943.0       3
1089.0       3
1857.0       3
2406.0       3
560.0        3
1608.0       3
2489.0       3
1708.0       3
2053.0       3
2211.0       3
2633.0       3
2122.0       3
1684.0       3
2792.0       3
2268.0       3
2256.0       3
1015.0       3
2377.0       3
1164.0       3
2550.0       3
2376.0       3
2326.0       3
1506.0       3
1136.0       3
3360.0       3
2401.0       3
2692.0       3
1513.0       3
1025.0       3
1573.0       3
984.0        3
1068.0       3
1813.0       3
1918.0       3
3256.0       3
1437.0       3
2562.0       3
1914.0       3
1678.0       3
682.0        3
2652.0       3
1987.0       3
1252.0       3
1491.0       3
975.0        3
2589.0       3
1297.0       2
2587.0       2
3670.0       2
2659.0       2
1145.0       2
918.0        2
2602.0       2
3442.0       2
1639.0       2
1378.0       2
2622.0       2
949.0        2
1996.0       2
2394.0       2
1192.0       2
3536.0       2
2928.0       2
2403.0       2
3227.0       2
1477.0       2
2178.0       2
2605.0       2
1428.0       2
1583.0       2
2218.0       2
2819.0       2
2334.0       2
1747.0       2
3188.0       2
2965.0       2
1369.0       2
1822.0       2
1362.0       2
1385.0       2
2540.0       2
2221.0       2
1239.0       2
2253.0       2
2340.0       2
3423.0       2
927.0        2
1285.0       2
2129.0       2
2114.0       2
3654.0       2
1418.0       2
2465.0       2
2470.0       2
3568.0       2
1258.0       2
1118.0       2
2640.0       2
1282.0       2
3246.0       2
951.0        2
2413.0       2
1891.0       2
1316.0       2
1171.0       2
2385.0       2
1322.0       2
2018.0       2
573.0        2
2908.0       2
4187.0       2
1357.0       2
1277.0       2
2106.0       2
948.0        2
1327.0       2
2002.0       2
3322.0       2
1448.0       2
1924.0       2
2821.0       2
1846.0       2
704.0        2
1091.0       2
1628.0       2
2057.0       2
911.0        2
2526.0       2
2309.0       2
2375.0       2
2615.0       2
1238.0       2
3518.0       2
3140.0       2
1738.0       2
2169.0       2
3292.0       2
660.0        2
2341.0       2
1366.0       2
2059.0       2
3240.0       2
3548.0       2
2267.0       2
2764.0       2
2066.0       2
1339.0       2
3167.0       2
1682.0       2
2226.0       2
1181.0       2
897.0        2
2484.0       2
4215.0       2
3664.0       2
2642.0       2
2595.0       2
998.0        2
2634.0       2
2312.0       2
1881.0       2
2904.0       2
1190.0       2
2028.0       2
2416.0       2
2673.0       2
3424.0       2
966.0        2
2084.0       2
1293.0       2
2949.0       2
2628.0       2
1060.0       2
2726.0       2
1070.0       2
1619.0       2
856.0        2
3440.0       2
2180.0       2
2878.0       2
2176.0       2
1797.0       2
3005.0       2
2036.0       2
2120.0       2
3606.0       2
2244.0       2
1629.0       2
2916.0       2
1954.0       2
2594.0       2
2777.0       2
2006.0       2
1784.0       2
2021.0       2
1304.0       2
1970.0       2
2574.0       2
1719.0       2
1773.0       2
1831.0       2
1993.0       2
1711.0       2
2136.0       2
1953.0       2
2474.0       2
2043.0       2
2070.0       2
1534.0       2
1653.0       2
1622.0       2
1182.0       2
1655.0       2
1388.0       2
4031.0       2
2355.0       2
3316.0       2
2490.0       2
3036.0       2
1508.0       2
3712.0       2
2101.0       2
2076.0       2
873.0        2
1672.0       2
3582.0       2
2504.0       2
1295.0       2
1209.0       2
1106.0       2
2888.0       2
1995.0       2
3695.0       2
1324.0       2
3096.0       2
1735.0       2
1828.0       2
2047.0       2
3137.0       2
2618.0       2
1170.0       2
2787.0       2
2278.0       2
2346.0       2
2563.0       2
1345.0       2
1975.0       2
1853.0       2
2371.0       2
1901.0       2
2577.0       2
1823.0       2
2619.0       2
2807.0       2
1094.0       2
2301.0       2
2658.0       2
2139.0       2
2993.0       2
2421.0       2
1499.0       2
1564.0       2
2314.0       2
2359.0       2
1689.0       2
2968.0       2
2604.0       2
1690.0       2
1417.0       2
3335.0       2
3153.0       2
2772.0       2
3370.0       2
1310.0       2
1717.0       2
2049.0       2
2276.0       2
2722.0       2
2999.0       2
2895.0       2
1077.0       2
1108.0       2
2582.0       2
2660.0       2
1671.0       2
2738.0       2
2257.0       2
2243.0       2
943.0        2
736.0        2
2596.0       2
1312.0       2
1289.0       2
3190.0       2
22137.0      2
2293.0       2
2037.0       2
2349.0       2
2646.0       2
1810.0       2
2476.0       2
3158.0       2
1774.0       2
2418.0       2
1956.0       2
3696.0       2
1971.0       2
3816.0       2
2402.0       2
2862.0       2
2014.0       2
6000.0       2
1206.0       2
2170.0       2
4957.0       2
3972.0       2
1053.0       2
2086.0       2
3228.0       2
3071.0       2
1492.0       2
1554.0       2
1382.0       2
2234.0       2
1878.0       2
2839.0       2
1203.0       2
1527.0       2
2945.0       2
2650.0       2
1010.0       2
616.0        2
2091.0       2
3306.0       2
1751.0       2
2873.0       2
1763.0       2
1447.0       2
2214.0       2
5200.0       2
1076.0       2
2316.0       2
1494.0       2
944.0        2
1131.0       2
1652.0       2
2645.0       2
2224.0       2
2883.0       2
1233.0       2
2302.0       2
2623.0       2
2854.0       2
3104.0       2
2997.0       2
3660.0       2
1625.0       2
1570.0       2
2277.0       2
4295.0       2
2110.0       2
2995.0       2
2870.0       2
2732.0       2
3178.0       2
2730.0       2
1473.0       2
3580.0       2
940.0        2
4078.0       2
1679.0       2
1825.0       2
2134.0       2
4972.0       2
3253.0       2
1726.0       2
2118.0       2
1016.0       2
1061.0       2
2920.0       2
2852.0       2
3192.0       2
1669.0       2
2458.0       2
1962.0       2
1571.0       2
2944.0       2
3088.0       2
3425.0       2
1610.0       2
320.0        2
1745.0       2
1895.0       2
2391.0       2
1321.0       2
1174.0       2
1683.0       2
1002.0       2
2281.0       2
2193.0       2
2543.0       2
2724.0       2
1847.0       2
690.0        2
1465.0       2
3900.0       2
2056.0       2
999.0        2
1785.0       2
1555.0       2
1588.0       2
1482.0       2
2105.0       2
1637.0       2
1552.0       2
2279.0       2
1371.0       2
1462.0       2
2874.0       2
1691.0       2
1302.0       2
2492.0       2
1307.0       2
1184.0       2
2520.0       2
3478.0       2
4750.0       2
1134.0       2
3100.0       2
2515.0       2
1673.0       2
3586.0       2
2850.0       2
1718.0       2
1941.0       2
3650.0       2
640.0        2
3339.0       2
973.0        2
1349.0       2
1961.0       2
1944.0       2
2205.0       2
1073.0       2
2506.0       2
1046.0       2
1107.0       2
2478.0       2
1578.0       2
1733.0       2
1840.0       2
1130.0       2
2102.0       2
2133.0       2
3609.0       2
2182.0       2
1522.0       2
1286.0       2
2426.0       2
2242.0       2
1114.0       2
3320.0       2
2274.0       2
1656.0       2
1132.0       2
2731.0       2
2155.0       2
1694.0       2
1111.0       2
1856.0       2
2255.0       2
1731.0       2
1243.0       2
1973.0       2
1225.0       2
2126.0       2
3124.0       2
3072.0       2
2765.0       2
500.0        2
1128.0       2
1599.0       2
2241.0       2
1179.0       2
1052.0       2
1654.0       2
2266.0       2
1299.0       2
920.0        2
1849.0       2
2204.0       2
1537.0       2
2503.0       2
2067.0       2
1789.0       2
1819.0       2
1723.0       2
1594.0       2
2035.0       2
1558.0       2
2258.0       2
750.0        2
1841.0       2
1235.0       2
1363.0       2
1561.0       2
1989.0       2
1933.0       2
1947.0       2
2493.0       2
2432.0       2
1372.0       2
962.0        2
3039.0       2
2560.0       2
1201.0       2
1946.0       2
916.0        2
1090.0       2
1438.0       2
1276.0       2
1377.0       2
7500.0       2
1237.0       2
1886.0       2
1546.0       2
810.0        2
713.0        2
2439.0       2
806.0        2
2629.0       2
2572.0       2
2935.0       2
2111.0       2
700.0        2
1034.0       2
1410.0       2
3172.0       2
1222.0       2
1325.0       2
1613.0       2
1905.0       2
2668.0       2
1906.0       2
1662.0       2
2912.0       2
3361.0       2
3064.0       2
2539.0       2
2523.0       2
1464.0       2
4438.0       2
2262.0       2
2010.0       2
2154.0       2
2688.0       2
6263.0       1
1045.0       1
2382.0       1
6064.0       1
6924.0       1
1524.0       1
1703.0       1
3002.0       1
1199.0       1
6350.0       1
2521.0       1
2103.0       1
2072.0       1
3155.0       1
3882.0       1
5930.0       1
2496.0       1
1331.0       1
1758.0       1
1493.0       1
2896.0       1
3264.0       1
1919.0       1
5950.0       1
1281.0       1
1533.0       1
1119.0       1
1066.0       1
1273.0       1
9518.0       1
3180.0       1
3232.0       1
2534.0       1
3685.0       1
3196.0       1
3358.0       1
692.0        1
3539.0       1
2167.0       1
2547.0       1
2708.0       1
62844.0      1
1245.0       1
3663.0       1
3407.0       1
787.0        1
2477.0       1
3542.0       1
2238.0       1

In [304]:
print(df_rs[df_rs['Sqft'] > 15000])

     TysonZip                                    Address1  \
5030    27332         106 Grinnel Loop, Sanford, NC 27332
5032    27332         103 Grinnel Loop, Sanford, NC 27332
5674    38261         1732 Stone St, Union City, TN 38261
7422    75090    820 N Sam Rayburn Fwy, Sherman, TX 75090
7888    72704  4199 W Sante Fe Sq, Fayetteville, AR 72704
8161    31092         202 St Charles Pl, Veinna, GA 31092

                    Address2 Availability       Price Beds Baths      Sqft  \
5030       Sanford, NC 27332     For Sale    390000.0    4   2.5   22137.0
5032       Sanford, NC 27332     For Sale    390000.0    4   2.5   22137.0
5674    Union City, TN 38261     For Sale   4500000.0  NaN   NaN   62844.0
7422       Sherman, TX 75090      Pending   8000000.0  NaN   NaN   65986.0
7888  Fayetteville, AR 72704      Pending  38500000.0  NaN   NaN  256672.0
8161        Veinna, GA 31092     For Sale   1850000.0  NaN   NaN   30055.0

              City State    Zip
5030       Sanford    NC  27332
5032       Sanford    NC  27332
5674    Union City    TN  38261
7422       Sherman    TX  75090
7888  Fayetteville    AR  72704
8161        Veinna    GA  31092

I checked those above individually.  The first two are errors, but the others are all multi-family units, so I'm removing them

In [305]:
df_rs.drop(df_rs[df_rs['Sqft'] > 30000].index, inplace=True)

In [310]:
df_rs.loc[df_rs['Sqft'] == 22137, 'Sqft'] = 2213

In [311]:
print(df_rs[df_rs['Sqft'] > 15000])

Empty DataFrame
Columns: [TysonZip, Address1, Address2, Availability, Price, Beds, Baths, Sqft, City, State, Zip]
Index: []

In [312]:
df_rs['City'].value_counts()

Seguin                  713
Broken Bow              311
Fayetteville            295
Cumming                 230
Bowling Green           226
Sherman                 192
Monroe                  169
Sanford                 158
Alexandria              142
Rogers                  137
Springdale              125
Traverse City           119
Shelbyville             106
Sedalia                 103
Goodlettsville           97
Vineland                 87
Jacksonville             82
Russellville             73
Easley                   72
Chicago                  71
Rome                     68
Zeeland                  65
Jackson                  65
Caseyville               63
Carthage                 63
Emporia                  59
Eufaula                  59
Vicksburg                58
Council Bluffs           56
Enid                     56
Warren                   55
Monett                   54
Hutchinson               53
Amherst                  52
Clarksville              52
Waterloo                 52
Houston                  51
Hanceville               50
Haltom City              45
Humboldt                 45
Dexter                   45
North Little Rock        44
Hope                     44
North Richland Hills     44
Omaha                    43
Dardanelle               41
Kansas City              38
Rainbow City             38
Fort Smith               35
Union City               34
Corydon                  34
Vernon                   32
Green Forest             32
Waldron                  32
Albertville              32
Berryville               31
Saint Joseph             31
Amarillo                 31
Logansport               29
Storm Lake               28
White Hall               28
Center                   27
San Lorenzo              26
Nashville                25
Denison                  24
Norfolk                  23
Lexington                22
Camilla                  21
Perry                    21
Garden City              21
Claremont                20
Waverly                  20
Sioux City               18
Blountsville             17
Henderson                17
Pine Bluff               15
Auburn                   14
New London               14
Portland                 14
Dallas                   14
Kennewick                13
Newbern                  11
Vienna                   11
Washington               10
Pasco                    10
New Holland               9
Albany                    9
Mount Pleasant            9
Moline                    8
Pendleton                 8
Tecumseh                  8
Concordia                 8
Cove                      8
Holcomb                   8
SPRINGDALE                7
Glendale                  6
Plano                     6
Hillsdale                 5
Stanton                   5
Ulysses                   5
Columbus Junction         5
Calhoun                   5
Ringgold                  5
Sergeant Bluff            5
Jacinto City              5
Burbank                   5
Arlington                 4
Le Claire                 4
Sebree                    4
Lakin                     4
Noel                      4
Wickes                    4
FAYETTEVILLE              4
Adams                     4
Clinton                   4
Dakota Dunes              4
Sublette                  4
East Moline               3
Fulton                    3
Newman Grove              3
Slaughters                3
Dakota City               3
Scott City                3
South Sioux City          3
Sloan                     3
Geneseo                   3
Carrollton                3
Temperanceville           3
Wapello                   3
Unadilla                  3
South Hutchinson          3
Grand Prairie             3
Satanta                   3
Flower Mound              3
Sterling                  3
Brock                     3
Bettendorf                2
Coal Valley               2
Sherrard                  2
Owensboro                 2
Camanche                  2
Talmage                   2
Dixon                     2
Tom Bean                  2
Morrison                  2
Wilkesboro                2
Beatrice                  2
Riverside                 2
Little Flock              2
Leigh                     2
Kalona                    2
Sharonville               2
Winfield                  2
Midlothian                2
Vandervoort               2
New Boston                2
Crawfordsville            2
Wayland                   2
Gillham                   2
Ponca                     2
Umpire                    2
Humphrey                  2
Bethel                    2
Hochatown                 2
Duncanville               2
Allen                     2
Three Way                 1
Ennis                     1
Frisco                    1
Corinth                   1
Southlake                 1
Sachse                    1
McCook Lake               1
Bedford                   1
Jefferson                 1
Emerson                   1
Othello                   1
Prophetstown              1
Idabel                    1
Haslet                    1
South Amherst             1
Richardsville             1
Hampton                   1
Silvis                    1
Battiest                  1
Orion                     1
Fallsville                1
Fairview Heights          1
                          1
Princeton                 1
Viola                     1
Avoca                     1
The Colony                1
Cedar Hill                1
Deerfield                 1
Mansfield                 1
Howells                   1
San Leandro               1
Letts                     1
Hanson                    1
Ainsworth                 1
Evansville                1
Lindsay                   1
Robards                   1
Marion                    1
Clarkson                  1
Battle Creek              1
Pilger                    1
Little Rock               1
Mesa                      1
Finley                    1
Columbus City             1
Joy                       1
Lewisville                1
Dunbar                    1
Bakerhill                 1
Modoc                     1
Eltopia                   1
Leoti                     1
Gadsden                   1
Grannis                   1
Johnson                   1
Muscatine                 1
Eagletown                 1
De Queen                  1
Green For                 1
Lakeside                  1
Edgar                     1
Cozad                     1
Fort Worth                1
Name: City, dtype: int64

In [313]:
df_rs['State'].value_counts()

TX    1245
AR    1042
KY     418
OK     374
NC     349
GA     333
TN     294
IA     262
MO     245
MI     239
KS     203
AL     199
NE     174
IL     171
MS     136
NJ      87
FL      82
SC      72
OH      65
IN      59
WA      32
CA      27
WI      14
ME      14
PA       9
VA       8
OR       8
SD       6
Name: State, dtype: int64

That worked this time

In [314]:
df_rs['Zip'].value_counts()

78155    451
74728    317
72704    292
42101    222
30040    201
27332    152
72756    140
75090    140
72764    124
28112    122
49684    119
65301    103
37160     99
37072     97
08360     87
32254     82
72802     73
60641     71
39204     65
62232     64
30161     60
36027     60
29640     60
39183     59
66801     59
73701     56
51501     56
77029     56
48091     55
65708     54
41001     54
72830     53
67501     53
50703     52
75633     51
49464     50
35077     49
38343     46
63841     45
72114     45
76117     45
44001     45
71801     44
68137     43
71602     43
72834     41
35906     39
66106     38
72901     35
38261     34
72638     33
35950     32
76384     32
72958     32
64507     31
79108     31
72616     31
46947     29
50588     29
47112     29
94580     27
76180     27
75935     27
71852     25
68850     24
51442     24
68701     23
31730     21
50220     21
28610     20
68462     20
67846     20
35031     17
42420     17
99337     14
68305     14
31092     14
54961     14
04102     14
45246     12
39051     12
38059     11
99301     11
52353     10
17557      9
42602      9
52641      9
68450      8
61265      8
64020      8
97801      8
51106      8
67851      8
75237      7
71937      7
51104      7
42406      5
24586      5
57049      5
42327      5
51054      5
67880      5
61257      5
68779      5
99323      5
52738      5
52732      4
52753      4
67877      4
64854      4
67860      4
68301      4
71973      4
61244      3
67871      3
51055      3
68443      3
68776      3
61252      3
68758      3
67505      3
75028      3
61254      3
67870      3
42455      3
42456      3
23442      3
68731      3
52653      3
68320      3
75007      3
61270      2
52730      2
52722      2
42301      2
42409      2
68448      2
68310      2
61281      2
61240      2
28697      2
76065      2
75093      2
75054      2
71841      2
71971      2
52247      2
75056      2
52659      2
52327      2
61272      2
52621      2
52654      2
71972      2
68643      2
68642      2
68770      2
75023      2
76021      1
75206      1
75104      1
75137      1
75013      1
75048      1
75075      1
76018      1
75223      1
75051      1
75002      1
51108      1
61277      1
75204      1
76092      1
76210      1
61486      1
52768      1
75228      1
61273      1
75119      1
75033      1
75232      1
61282      1
61256      1
75074      1
76002      1
76012      1
51105      1
75116      1
76063      1
68768      1
99344      1
75220      1
68629      1
68641      1
99343      1
68644      1
42452      1
52201      1
52754      1
47712      1
42413      1
52737      1
61260      1
52761      1
71832      1
71953      1
74734      1
71944      1
51109      1
67861      1
67838      1
68378      1
67863      1
68346      1
68733      1
57038      1
76015      1
75225      1
68715      1
Name: Zip, dtype: int64

In [315]:
print(df_rs['Zip'].nunique())

219

That's significantly more zip codes than we have food production facility zip codes. Probably because when homes aren't found in that zip code it looks for homes within a 3-mile radius instead. So I need to set up my data-scraping so that when it finds homes, it also adds a line to the data appending that will add the Tyson zip it was looking for.

So the notes above are the way things turned out the first time. So I fixed my scraper and ran through it all again with a new column adding TysonZip, so that it's easy to link up to each food production facility.  Then I cleaned it and checked it all again too.

In [419]:
# Importing cleaned data again
df_rs = pd.read_csv(os.path.join(path, 'Data', 'Cleaned', 'Realtor_Scraped_ForSale.csv'), dtype={'TysonZip': str}, index_col = False)

df_rs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6167 entries, 0 to 6166
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TysonZip      6167 non-null   object
 1   Address1      6167 non-null   object
 2   Address2      6167 non-null   object
 3   Availability  6167 non-null   object
 4   Price         6167 non-null   float64
 5   Beds          6115 non-null   object
 6   Baths         6089 non-null   float64
 7   Sqft          6167 non-null   float64
 8   City          6166 non-null   object
 9   State         6167 non-null   object
 10  Zip           5592 non-null   float64
dtypes: float64(4), object(7)
memory usage: 530.1+ KB

In [316]:
# I'm going to go ahead and export what I have and then update my scraper and run it again

df_rs.to_csv(os.path.join(path, 'Data', 'Cleaned', 'Realtor_Scraped_ForSale.csv'), index=False)

## 7. Realtor.com scraped rental listings for zip codes in list

### 7A. Web Scraping Script

In [229]:
# I'm going to go ahead and run this rental script again since I updated the other list and I've updated the script
# a little to make it easier to link to the zip code list

import os
import requests
from bs4 import BeautifulSoup
import pandas as pd
import datetime
import time
import random
import csv
import re

start_time = time.time()

# Defining path
path=r'D:\Adam\Employment\Data Analysis Course\Final Data Project'

# Defining location of zipfile
zipfile = 'D:\Adam\Employment\Data Analysis Course\Final Data Project\Data\Cleaned\Tyson_zips_only.csv'

# Open the CSV file that contains the list of zip codes.
with open(zipfile, 'r') as f:
    reader = csv.reader(f)
    zip_codes = list(reader)

data = []    
    
# Loop through the list of zip codes.
for zip_code in zip_codes:
    print(f"Processing zip code: {zip_code[0]}")
    
    # Add a random delay before going to next zip code
    time.sleep(random.randint(30, 90))
    
    # Loop through the page numbers (1-20).
    for page_num in range(1, 20):
        print(f"Processing page {page_num}")
    
        # Update the URL in the script.
        url_template = "https://www.realtor.com/apartments/{}/pg-{}"
        url = url_template.format(zip_code[0], page_num)

        # Set user-agent header to avoid bot detection
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}

        # Add a random delay before making the request
        time.sleep(random.randint(8, 16))

        # Send HTTP GET request to the URL and get the HTML response
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            print("Request successful")
        else:
            print(f"Request failed with status code: {response.status_code}. No more listings pages found.")
            break

        # Parse the HTML response using BeautifulSoup
        soup = BeautifulSoup(response.content, 'html.parser')

        # Find the container for all the properties
        container = soup.find('section', class_=re.compile(r'PropertiesList_propertiesContainer'))

        # Check if the container is empty
        if container is None:
            print("No listings found")
            break

        # Check if the page contains the text "We're Sorry"
        if "We're Sorry" in soup.text:
            print("No more pages")
            break

        # Find all the listings in the container
        listings = container.find_all('div', class_=re.compile(r'BasePropertyCard_propertyCardWrap'))

        # Loop through each listing and extract the details
        for listing in listings:
            if listing is not None:
                try:
                    address1 = listing.find('div', {'class': 'truncate-line', 'data-testid': 'card-address-1'}).text.strip()
                except AttributeError:
                    address1 = ''

                try:
                    address2 = listing.find('div', {'class': 'truncate-line', 'data-testid': 'card-address-2'}).text.strip()
                except AttributeError:
                    address2 = ''

                try:
                    style = listing.find('div', {'class': 'message'}).text.split(' - ')[1]
                except AttributeError:
                    style = ''

                try:
                    price = listing.find('div', class_=re.compile(r'Price__Component')).text.strip().replace(',', '').replace('$', '')
                except AttributeError:
                    price = ''

                try:
                    beds = listing.find('li', {'data-testid': 'property-meta-beds'}).text.strip().replace('bed', '')
                except AttributeError:
                    beds = ''

                try:
                    baths = listing.find('li', {'data-testid': 'property-meta-baths'}).text.strip().replace('bath', '')
                except AttributeError:
                    baths = ''

                try:
                    sqft = listing.find('li', {'data-testid': 'property-meta-sqft'}).text.strip().replace(',', '').split('sqft')[0]
                except AttributeError:
                    sqft = ''

            else:
                print('No listing found.')

            # Split the beds, baths, and sqft values at the " - " and create two new rows with the values before and after the " - "

            if "-" in price:
                price_split = price.split(" - ")
                if "-" in beds:
                    beds_split = beds.split(" - ")
                    if "-" in sqft:
                        sqft_split = sqft.split(" - ")
                        if "-" in baths:
                            baths_split = baths.split(" - ")
                            data.append([zip_code[0], address1, address2, style, price_split[0], beds_split[0], baths_split[0], sqft_split[0]])
                            data.append([zip_code[0], address1, address2, style, price_split[1], beds_split[1], baths_split[1], sqft_split[1]])

                        else:
                            data.append([zip_code[0], address1, address2, style, price_split[0], beds_split[0], baths, sqft_split[0]])
                            data.append([zip_code[0], address1, address2, style, price_split[1], beds_split[1], baths, sqft_split[1]])
                    else:
                        data.append([zip_code[0], address1, address2, style, price_split[0], beds_split[0], baths, sqft])
                        data.append([zip_code[0], address1, address2, style, price_split[1], beds_split[1], baths, sqft])    
                else:
                    data.append([zip_code[0], address1, address2, style, price_split[0], beds, baths, sqft])
                    data.append([zip_code[0], address1, address2, style, price_split[1], beds, baths, sqft])
            else:
                data.append([zip_code[0], address1, address2, style, price, beds, baths, sqft])
       
        # stopping pagination if less than 41 listings found
        if int(soup.find('div', class_=re.compile(r'MatchProperties')).text.strip().split(' matching')[0]) < 40:
            print("No more listings")
            break
        else:
            continue
        
    print("Finished processing zip code")

# Create a Pandas dataframe from the extracted data
df = pd.DataFrame(data, columns=['TysonZip', 'Address1', 'Address2', 'Style', 'Price', 'Beds', 'Baths', 'Sqft'])

# get today's date in the format YYYY-MM-DD
today = datetime.datetime.today().strftime('%Y-%m-%d')

# Export the dataframe to a CSV file
df.to_csv(os.path.join(path, 'Data', 'Scraped', f'TysonZips_rentals_{today}.csv'), index=False)

# Print the dataframe
print(df)

end_time = time.time()

execution_time = end_time - start_time

print("Execution time:", execution_time)

Processing zip code: 73701
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 42602
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 35950
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 79108
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 44001
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 72764
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 72616
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 35031
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 42101
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 74728
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 31730
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 75633
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 39051
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 62232
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 75935
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 39183
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 60641
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 72756
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 45246
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 28610
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 72830
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 41001
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 39204
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 49684
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 64020
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 47112
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 51501
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request successful
Processing page 6
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 30040
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 68731
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 75237
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 24586
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 72834
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 51442
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 63841
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 29640
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 66801
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 36027
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 67851
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 72901
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 35906
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 37072
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 71944
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 72638
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 76117
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 71801
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 77029
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 38343
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 67505
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 67501
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 32254
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 61257
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 66106
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 68850
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 46947
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 52738
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 68748
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 27332
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 65708
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 28112
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 72114
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 71852
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 17557
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 54961

Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 38059
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 64854
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 76180
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request successful
Processing page 5
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 38261
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 68137
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 99363
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 50220
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 71602
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 04102
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 42452
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 30161
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 35077
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 94580
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 65301
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 78155
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 37160
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 75090
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 64507
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 50588
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 68450
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 23442
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 72802
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 72704
Processing page 1
Request successful
Processing page 2
Request successful
Processing page 3
Request successful
Processing page 4
Request failed with status code: 404. No more listings pages found.
Finished processing zip code
Processing zip code: 76384
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 31092
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 08360
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 72958
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 48091
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 50703
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 68462
Processing page 1
Request successful
No more listings
Finished processing zip code
Processing zip code: 28697
Processing page 1
Request successful
No listings found
Finished processing zip code
Processing zip code: 49464
Processing page 1
Request successful
No more listings
Finished processing zip code
     TysonZip                                           Address1  \
0       73701                          1201 E Broadway Ave Apt B
1       73701                          1201 E Broadway Ave Apt J
2       73701                                      609 N 13th St
3       73701                                      624 N 10th St
4       73701                                      812 W Elm Ave
5       73701                                    1910 N Grand St
6       73701                                      401 S 19th St
7       73701                                      1306 Nancy Dr
8       73701                                    1906 E Pine Ave
9       73701                                      726 N 14th St
10      73701                                  1219 N Kennedy St
11      73701                                   2612 E Maple Ave
12      35950                                301 W Main St Ste B
13      35950                                   306 E McCord Ave
14      79108                                  10505 Broadway Dr
15      79108
16      79108                                 8403 N Highway 287
17      79108
18      79108                                   420 Mesquite Ave
19      79108                                  1506 E Central St
20      79108                                      4611 Dumas Dr
21      44001                                       36 Westwoods
22      44001                                       36 Westwoods
23      44001                                     7055 Quarry Rd
24      44001                                     7055 Quarry Rd
25      72764                                 1701 S West End St
26      72764                                 1701 S West End St
27      72764                                  1517 Electric Ave
28      72764                                  1517 Electric Ave
29      72764                                      5325 N Oak St
30      72764                                      5325 N Oak St
31      72764                         3810 S Thompson Ave Unit 7
32      72764                        3810 S Thompson Ave Unit 25
33      72764                             3324 S Old Missouri Rd
34      72764                           514 Butterfield Coach Rd
35      72764                           514 Butterfield Coach Rd
36      72764                                 3702-B Locksley St
37      72764                                 3702-B Locksley St
38      72764                                     1406 Oriole St
39      72764                                     1406 Oriole St
40      72764                                     726 E Emma Ave
41      72764                                     726 E Emma Ave
42      72764                         3810 S Thompson Ave Unit 6
43      72764                        3810 S Thompson Ave Unit 32
44      72764                         3810 S Thompson Ave Unit 5
45      72764                        3810 S Thompson Ave Unit 35
46      72764                        3810 S Thompson Ave Unit 39
47      72764                        3810 S Thompson Ave Unit 21
48      72764                        3810 S Thompson Ave Unit 30
49      72764                        3810 S Thompson Ave Unit 29
50      72764                        3810 S Thompson Ave Unit 14
51      72764                               2785 Ruth Ave Unit B
52      72764                              711 Mountain View Ave
53      72764                                    20466 Sonora Rd
54      72764                                    2275 E Emma Ave
55      72764                                 3551 Butterfly Ave
56      72764                              1232 Wilson St Unit B
57      72764                               315 Texas Ln Apt 101
58      72764                                316 Erin Pl Apt 202
59      72764                                316 Erin Pl Apt 102
60      72764                                    3839 E Embry Dr
61      72764                               315 Texas Ln Apt 206
62      72764                           1414 S Powell St Apt 202
63      72764                           1414 S Powell St Apt 102
64      72764                           1706 S Powell St Apt 203
65      72764                              1160 Dove Loop Unit B
66      72764                                  884 Palisades Ave
67      72764                             1600 Juniper Cir Apt B
68      72764                                3444 Acorn Falls Ln
69      72764                           1006 Walnut Ave Unit 101
70      72764                                   3568 Bastille St
71      72764                                420 Park St Apt 201
72      72764                                    703 W Grove Ave
73      72764                            700 Virginia St Apt 101
74      72764                               315 Texas Ln Apt 206
75      72764                           1414 S Powell St Apt 202
76      72764                           1414 S Powell St Apt 102
77      72764                           1706 S Powell St Apt 203
78      72764                              1160 Dove Loop Unit B
79      72764                                  884 Palisades Ave
80      72764                             1600 Juniper Cir Apt B
81      72764                                3444 Acorn Falls Ln
82      72764                           1006 Walnut Ave Unit 101
83      72764                                   3568 Bastille St
84      72764                                420 Park St Apt 201
85      72764                                    703 W Grove Ave
86      72764                            700 Virginia St Apt 101
87      72764                                    2586 Adrian Ave
88      72764                              2006 Ashlee Dr Unit A
89      72764                                  1299 Electric Ave
90      72764                                  1299 Electric Ave
91      72764                                   4207 Cherokee Cv
92      72764                                    2321 Orchard St
93      72764                                    1249 Ashport St
94      72764                                  608 Black Oak Ave
95      72764                                  608 Black Oak Ave
96      72616                                 204 Ember Dr Apt 1
97      72616                                 208 Ember Dr Apt 2
98      35031                                40 Ratliff St Apt 7
99      42101                                    2244 Hickory St
100     42101                                    2244 Hickory St
101     42101                                 1117 Greenwood Aly
102     42101                                   1614 Parkside Dr
103     42101                       213 Walnut Creek Ct Unit 213
104     42101                       261 Walnut Creek Ct Unit 261
105     42101                       112 Walnut Creek Ct Unit 112
106     42101                              218 Kelly Rd Unit K74
107     42101                         4485 Wal Valley Way Unit A
108     42101                       324 Walnut Creek Ct Unit 324
109     42101                         4497 Wal Valley Way Unit A
110     42101                             7136 Weatherstone Blvd
111     42101                                    6525 Fortuna Ct
112     42101                                   1519 Calgary Way
113     42101                                   377 Cedar Run St
114     42101                                       1180 Fair St
115     42101                                   1271 Kentucky St
116     42101                                    506 Labrador Dr
117     42101                                   324 Gatewood Ave
118     42101                             134 Westwood Cir Apt C
119     42101                                      132 Pebble Ct
120     42101                          114 Whispering Hills Blvd
121     42101                                 5487 Hackberry Way
122     42101                                    6541 Fortuna Ct
123     42101                                      396 Deluth Dr
124     42101                                    6545 Fortuna Ct
125     42101                                    125 Bonaire Ave
126     42101                                      909 Cabell Dr
127     42101                               1799 Russellville Rd
128     42101                               1799 Russellville Rd
129     42101                                  4490 Woodstone Dr
130     74728                                      807 Dierks St
131     74728                                        100 Abby Ln
132     74728                                        100 Abby Ln
133     75633                                     101 Senior Ave
134     75633                                    1100 S Adams St
135     62232                                     8018 Tahoe Rdg
136     62232                                311 N Main St Apt 7
137     75935                                    705 Clifford St
138     39183                               4223 I20 Frontage Rd
139     39183                               4223 I20 Frontage Rd
140     39183                                      1215 Adams St
141     39183                                4225 20 Frontage Rd
142     39183                                4225 20 Frontage Rd
143     39183                                     2501 Culkin Rd
144     39183                                     2501 Culkin Rd
145     60641                                 4179 W Belmont Ave
146     60641                                 4179 W Belmont Ave
147     60641                                 4200 W Belmont Ave
148     60641                                 4200 W Belmont Ave
149     60641
150     60641
151     60641                           2956 N Pulaski Rd Unit 2
152     60641        2948-52 N Laramie-9 2948 ½ N Laramie Unit 3
153     60641                           2958 N Pulaski Rd Unit 2
154     60641                               5344 W Eddy St Apt 2
155     60641                            4037 W Nelson St Unit 1
156     60641                         4007 N Kildare Ave Apt 105
157     60641                          4177 W Belmont Ave Unit 2
158     60641                          3153 N Tripp Ave Unit 205
159     60641                    5425 W Montrose Ave Unit 5425S3
160     60641                    3941 N Keeler Ave Unit 3941-404
161     60641                        4022 W Montrose Ave Unit St
162     60641                       4250 W Nelson St Unit 4250-2
163     60641                       4254 W Nelson St Unit 4254-1
164     60641                       4001 W Monttrose Ave Unit St
165     60641                            4820 W George St Unit G
166     60641                           5141 W Roscoe St Unit 1R
167     60641                      2923 N Long Ave Unit AF2923-2
168     60641                       4244 W Nelson St Unit 4244-2
169     60641                      4903 W Cullom Ave Unit 4903-3
170     60641                 4819-21 W Cornelia Ave Unit 4819-1
171     60641                         3243 N Lockwood Ave Unit 2
172     60641                       4263 W Nelson St Unit 4263-1
173     60641                          3250 N Pulaski Rd Apt 318
174     60641                          4825 W Oakdale Ave Unit 2
175     60641                            5201 W Cullom Ave Apt 1
176     60641                            5201 W Cullom Ave Apt 2
177     60641                            5201 W Cullom Ave Apt 3
178     60641                            3450 N Lowell Ave Apt 1
179     60641                                  4025 W Melrose St
180     60641                                  5257 W Nelson Ave
181     60641                                  4121 W Cullom Ave
182     60641                                  4121 W Cullom Ave
183     60641                          4154 W Berteau Ave Unit B
184     60641                          4112 N Kedvale Ave Apt Ge
185     60641                           4131 W Berteau Ave Apt 2
186     60641                         4300 W Montrose Ave Unit 3
187     60641                         4300 W Montrose Ave Unit 4
188     60641                           2944 N Laramie Ave Apt 2
189     60641                       4300 W Montrose Ave Unit 200
190     60641                            4207 W Roscoe St Unit 2
191     60641                        4131 W Belmont Ave Unit 413
192     60641                                    5422 W Dakin St
193     60641                         4222 N Keystone Ave Apt 1B
194     60641                                  3750 N Lowell Ave
195     60641                                   5518 W Barry Ave
196     60641                          3250 N Pulaski Rd Apt 201
197     60641                          3250 N Pulaski Rd Apt 203
198     60641                        3711 N Kenneth Ave Unit 119
199     60641                     4200 W Belmont Ave Unit 4214-2
200     60641                             5141 W Roscoe St Apt 2
201     60641                             5141 W Roscoe St Apt 3
202     60641                          5359 W Berenice Ave Apt 2
203     60641                            3921 N Linder Ave Apt 1
204     60641                               2837 N Long Ave Fl 2
205     60641                            4235 N Lamon Ave Apt 3N
206     60641                               4030 N Milwaukee Ave
207     60641                                  4350 N Cicero Ave
208     60641                           5225 W Melrose St Unit 1
209     60641                            3450 N Lowell Ave Apt 2
210     60641                                5160 W Montrose Ave
211     60641                                   1 W Montrose Ave
212     60641                                5111 W Montrose Ave
213     60641                 4819-21 W Cornelia Ave Unit 4821-1
214     60641                          3058 N Kostner Ave Apt 1E
215     60641                              3053 N Kilpatrick Ave
216     60641                         4153 W Melrose Ave Unit 1E
217     60641                                5160 W Montrose Ave
218     60641                                  3054 N Kolmar Ave
219     60641                     4200 W Belmont Ave Unit 4210-3
220     60641                           4031 W Melrose St Apt 3N
221     60641                        5107 W Montrose Ave Unit 2W
222     60641                         4300 W Montrose Ave Unit 2
223     60641                       3035 N Kilpatrick Ave Unit 2
224     60641                           5327 W Wolfram St Unit 1
225     60641                   4179 W Belmont Ave Unit 4177-002
226     60641                   4179 W Belmont Ave Unit 3153-205
227     60641                   4179 W Belmont Ave Unit 4181-302
228     60641                         5301 W Newport Ave Unit 1R
229     60641                       3035 N Kilpatrick Ave Unit G
230     60641                          2837 N Long Ave Unit Bsmt
231     60641                          2856 N Kostner Ave Unit 2
232     60641                         4250 N Keystone Ave Apt 2S
233     60641                           2849 N Linder Ave Unit 2
234     60641                           5522 W Berteau Ave Apt 2
235     60641                           5240 W Cullom Ave Unit 1
236     60641                           3453 N Lowell Ave Unit 1
237     60641                                4821 W Cornelia Ave
238     60641                   4179 W Belmont Ave Unit 4181-201
239     60641                   4179 W Belmont Ave Unit 4177-204
240     60641                   4179 W Belmont Ave Unit 4177-303
241     60641                   4179 W Belmont Ave Unit 4181-301
242     60641                           3813 N Cicero Ave Unit 2

In [374]:
# Importing scraped rental data
df_rr = pd.read_csv(os.path.join(path, 'Data', 'Scraped', f'TysonZips_rentals_2023-05-05.csv'), dtype={'TysonZip': str}, index_col = False)

### 7B. Consistency Checks

In [375]:
# checking dataset info

df_rr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1610 entries, 0 to 1609
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   TysonZip  1610 non-null   object
 1   Address1  1606 non-null   object
 2   Address2  1606 non-null   object
 3   Style     1610 non-null   object
 4   Price     1610 non-null   object
 5   Beds      1605 non-null   object
 6   Baths     1602 non-null   object
 7   Sqft      1415 non-null   object
dtypes: object(8)
memory usage: 100.8+ KB

I'm going to need to convert price and Sqft to integers... but there may be some strange values in those, so I'll have to check that first

In [377]:
# making it show me all the rows
pd.options.display.max_rows = len(df_rr['Price'].value_counts())

df_rr['Price'].value_counts()

1395                 28
1200                 27
650                  24
1500                 23
2400                 22
900                  22
1649                 21
1100                 21
850                  20
750                  20
1450                 20
1300                 19
1050                 19
1850                 19
1650                 18
895                  18
1600                 18
1250                 18
2000                 17
1950                 17
1800                 17
1000                 17
950                  17
2200                 16
1550                 16
1900                 14
795                  14
1350                 14
1495                 14
2500                 13
1195                 13
1695                 13
695                  13
1750                 12
625                  12
1995                 12
2100                 12
1275                 12
1599                 12
Contact For Price    11
1595                 11
2600                 11
1095                 11
595                  11
800                  11
1795                 10
1700                 10
1150                 10
2700                 10
675                  10
725                  10
2300                  9
2900                  9
1400                  9
925                   9
2895                  9
500                   8
775                   8
875                   8
1295                  8
700                   7
2250                  7
975                   7
1425                  7
2445                  6
1025                  6
995                   6
1225                  6
2795                  6
3200                  6
1475                  6
475                   6
1249                  6
550                   6
1645                  6
2650                  5
3000                  5
2150                  5
1349                  5
1134                  5
5000                  5
2695                  5
2095                  5
1675                  5
600                   5
1895                  5
2800                  5
2295                  4
2850                  4
2350                  4
1525                  4
1625                  4
2195                  4
1589                  4
1375                  4
2050                  4
1970                  4
1527                  4
999                   4
575                   4
1725                  4
1129                  4
1901                  4
825                   4
1740                  4
2750                  4
1870                  4
1825                  3
620                   3
1465                  3
1685                  3
400                   3
1205                  3
1221                  3
1399                  3
955                   3
495                   3
799                   3
1575                  3
1975                  3
1435                  3
1738                  3
1125                  3
1508                  3
1720                  3
1455                  3
2450                  3
1663                  3
450                   3
3600                  3
1597                  3
1099                  3
1075                  3
1775                  3
3400                  3
2395                  3
1470                  2
1519                  2
3800                  2
3300                  2
1336                  2
936                   2
490                   2
1109                  2
1160                  2
1089                  2
1437                  2
2995                  2
2630                  2
1902                  2
1175                  2
1207                  2
100                   2
2245                  2
3990                  2
2545                  2
1672                  2
2375                  2
830                   2
1780                  2
1119                  2
1535                  2
1875                  2
2495                  2
2140                  2
640                   2
560                   2
1442                  2
425                   2
1811                  2
1199                  2
980                   2
1845                  2
985                   2
4725                  2
2025                  2
1070                  2
1305                  2
1064                  2
1748                  2
1872                  2
2595                  2
1885                  2
885                   2
1745                  2
1561                  2
920                   2
845                   2
1341                  2
965                   2
3500                  2
1940                  2
3900                  2
2215                  2
1147                  2
938                   2
1670                  2
1374                  2
1285                  2
2145                  2
1365                  2
1110                  2
1105                  2
1371                  2
2950                  2
1633                  2
1145                  2
1060                  2
2275                  2
1565                  2
1167                  2
2535                  1
1580                  1
1735                  1
1609                  1
1080                  1
1467                  1
1515                  1
1139                  1
945                   1
949                   1
2645                  1
645                   1
1355                  1
770                   1
720                   1
1905                  1
1068                  1
1718                  1
1880                  1
1622                  1
1122                  1
3050                  1
1432                  1
1759                  1
1559                  1
2080                  1
2320                  1
2816                  1
1398                  1
1340                  1
2705                  1
1640                  1
953                   1
1165                  1
1667                  1
3183                  1
1919                  1
2466                  1
1584                  1
2440                  1
1569                  1
1755                  1
652                   1
835                   1
1052                  1
2549                  1
1607                  1
1836                  1
1548                  1
854                   1
1157                  1
1257                  1
1152                  1
1234                  1
1320                  1
1410                  1
1316                  1
1457                  1
1182                  1
1613                  1
1524                  1
1478                  1
1460                  1
1342                  1
2499                  1
2045                  1
2199                  1
2280                  1
1897                  1
2190                  1
1029                  1
1790                  1
3960                  1
2845                  1
1925                  1
1782                  1
2926                  1
2049                  1
1743                  1
1421                  1
1184                  1
1396                  1
710                   1
891                   1
1477                  1
1476                  1
1325                  1
1847                  1
4000                  1
1230                  1
1132                  1
1799                  1
2325                  1
2541                  1
1343                  1
1587                  1
1312                  1
660                   1
1319                  1
1392                  1
1557                  1
1293                  1
1151                  1
2865                  1
2485                  1
1834                  1
2044                  1
911                   1
1402                  1
2975                  1
1055                  1
1469                  1
1074                  1
1490                  1
1434                  1
1020                  1
1019                  1
1                     1
886                   1
2315                  1
2160                  1
2820                  1
1560                  1
2219                  1
1988                  1
810                   1
943                   1
1730                  1
1135                  1
1379                  1
840                   1
820                   1
410                   1
2236                  1
2899                  1
2455                  1
3110                  1
1299                  1
1141                  1
1405                  1
1009                  1
1170                  1
860                   1
1040                  1
2075                  1
3625                  1
2085                  1
4500                  1
2349                  1
2420                  1
3275                  1
5595                  1
1506                  1
1048                  1
1422                  1
1360                  1
1345                  1
525                   1
693                   1
492                   1
718                   1
586                   1
1330                  1
849                   1
1409                  1
1290                  1
1054                  1
1164                  1
745                   1
692                   1
694                   1
1499                  1
1033                  1
1181                  1
1890                  1
1335                  1
2270                  1
1185                  1
1990                  1
2480                  1
3700                  1
1855                  1
3100                  1
3195                  1
4200                  1
6300                  1
1280                  1
4400                  1
1602                  1
1059                  1
1406                  1
1016                  1
1545                  1
1254                  1
1440                  1
1258                  1
1215                  1
1235                  1
915                   1
1416                  1
1334                  1
1049                  1
1010                  1
1183                  1
1381                  1
2165                  1
1161                  1
1268                  1
1710                  1
1245                  1
1835                  1
767                   1
1739                  1
1612                  1
937                   1
1313                  1
843                   1
699                   1
1480                  1
1351                  1
1604                  1
1920                  1
1031                  1
979                   1
1085                  1
910                   1
1669                  1
959                   1
1078                  1
870                   1
2020                  1
1606                  1
1197                  1
1489                  1
1287                  1
1785                  1
415                   1
1370                  1
1005                  1
1806                  1
1255                  1
1534                  1
2265                  1
1155                  1
455                   1
1171                  1
1514                  1
865                   1
1358                  1
989                   1
2830                  1
2170                  1
2345                  1
1429                  1
563                   1
2107                  1
963                   1
765                   1
940                   1
638                   1
551                   1
2426                  1
Name: Price, dtype: int64

I found only one strange value, "contact for price", so I'm going to drop that now.

In [378]:
# Dropping rows with "Contact For Price" value

df_rr.drop(df_rr[df_rr['Price'] == 'Contact For Price'].index, inplace=True)

In [379]:
df_rr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1599 entries, 0 to 1609
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   TysonZip  1599 non-null   object
 1   Address1  1595 non-null   object
 2   Address2  1595 non-null   object
 3   Style     1599 non-null   object
 4   Price     1599 non-null   object
 5   Beds      1597 non-null   object
 6   Baths     1594 non-null   object
 7   Sqft      1409 non-null   object
dtypes: object(8)
memory usage: 112.4+ KB

In [380]:
# making it an int64 dtype

df_rr = df_rr.astype({'Price': 'int64'})

In [381]:
df_rr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1599 entries, 0 to 1609
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   TysonZip  1599 non-null   object
 1   Address1  1595 non-null   object
 2   Address2  1595 non-null   object
 3   Style     1599 non-null   object
 4   Price     1599 non-null   int64
 5   Beds      1597 non-null   object
 6   Baths     1594 non-null   object
 7   Sqft      1409 non-null   object
dtypes: int64(1), object(7)
memory usage: 112.4+ KB

In [383]:
# making it show me all the rows
pd.options.display.max_rows = len(df_rr['Sqft'].value_counts())

df_rr['Sqft'].value_counts()

700            29
1000           21
1100           21
900            20
1050           18
400            16
1200           15
694            14
1729           14
800            14
950            14
1300           13
550            12
1146           12
750            11
850            11
1067           10
726            10
600            10
1261           10
1159            9
650             9
1634            8
816             8
1372            7
1350            7
660             7
884             7
680             7
784             7
500             6
1680            6
350             6
1064            6
1500            6
1212            6
1440            6
1080            6
1082            6
2002            6
956             6
1152            6
960             6
1796            5
952             5
855             5
1400            5
663             5
2032            5
720             5
2000            5
727             5
1344            5
1056            5
1738            5
564             4
300             4
1800            4
418             4
1150            4
1340            4
525             4
1216            4
2054            4
1234            4
1627            4
1380            4
1600            4
1450            4
1131            4
1298            4
327             4
450             4
1280            4
675             4
640             4
1319            4
924             4
540             3
1232            3
1900            3
780             3
1116            3
646             3
1445            3
842             3
1224            3
744             3
740             3
1470            3
1415            3
1092            3
568             3
983             3
1034            3
933             3
475             3
1508            3
1836            3
820             3
872             3
1040            3
1256            3
936             3
560             3
722             3
752             3
1147            3
1264            3
2500            3
2600            3
975             3
915             3
935             3
1910            3
1395            3
1425            3
1528            3
1155            3
1120            3
896             3
1097            3
810             3
974             3
620             3
1393            3
702             3
1036            3
825             3
770             3
625             3
725             3
1700            3
1025            3
1703            3
1463            3
980             3
1130            3
1221            2
1098            2
1314            2
1618            2
1255            2
1389            2
1265            2
1266            2
695             2
670             2
1056 - 1105     2
1442            2
1168            2
1170            2
1484            2
876             2
1028            2
698             2
1260            2
1920            2
1408            2
1127            2
1307            2
558             2
529             2
635             2
1416            2
1240            2
2039            2
1390            2
1602            2
874             2
2190            2
539             2
737             2
2200            2
1673            2
1132            2
1158            2
1472            2
1329            2
754             2
3000            2
1134            2
957             2
630             2
638             2
1410            2
1013            2
480             2
1407            2
870             2
1580            2
1878            2
2240            2
1250            2
1318            2
1233            2
1720            2
1446            2
1075            2
738             2
1290            2
1614            2
1433            2
693             2
1156            2
1180            2
741             2
690             2
1510            2
600 - 692       2
1980            2
1186            2
1477 - 1483     2
592             2
544             2
2252            2
676             2
1982            2
1905            2
1218            2
1248            2
795             2
1583            2
849             2
1135            2
648             2
1114            2
1987            2
1281            2
1027            2
1275            2
925             2
1231            2
1736            2
1238            2
570             2
1468            2
1142            2
1026            2
250             2
1665            2
496             2
904             2
2650            1
518             1
1838            1
1546            1
719             1
1882            1
1879            1
605             1
1773            1
1010            1
1030            1
3152            1
2591            1
2576            1
2217            1
3005            1
1065            1
1324            1
708             1
1326            1
380             1
1469            1
1138            1
1954            1
1110            1
1267            1
1088            1
808             1
665             1
1872            1
2417            1
1242            1
909             1
565             1
1897            1
1143            1
1850            1
2178            1
683             1
5040            1
1320            1
667             1
1884            1
1874            1
445             1
1295            1
1747            1
1128            1
2094            1
1638            1
1636            1
2110            1
1526            1
1669            1
1843            1
1485            1
1038            1
1818            1
1746            1
2047            1
1530            1
2090            1
2015            1
1974            1
1452            1
1976            1
1090 - 1289     1
204             1
984             1
20193           1
1717            1
1532            1
1215            1
1276            1
2041            1
2641            1
1851            1
1512            1
1392            1
1140            1
1830            1
1480            1
316             1
2430            1
1127 - 1620     1
1418            1
682             1
992             1
710             1
1053            1
1252            1
1332            1
978             1
425             1
1017            1
666             1
1060            1
944             1
993             1
2585            1
1787            1
1308            1
1042            1
1178            1
1690            1
2473            1
1556            1
1529            1
1842            1
1337            1
1104            1
2250            1
2355            1
945             1
1702            1
2341            1
1824            1
1871            1
2301            1
1658            1
3144            1
1722            1
1875            1
1964            1
2492            1
1950            1
1136            1
6480            1
3750            1
2029            1
2513            1
1848            1
2210            1
2898            1
2435            1
2270            1
1347            1
973             1
1090            1
728             1
552             1
954             1
700 - 1048      1
1840            1
1003            1
1176            1
1364            1
2637            1
2034            1
1933            1
880             1
1918            1
1753            1
2326            1
2089            1
1936            1
836             1
2362            1
1902            1
1670            1
1297            1
1236            1
1388            1
977             1
1527            1
2472            1
300 - 790       1
1244            1
1437            1
1387            1
2171            1
1311            1
1591            1
790             1
2152            1
440             1
1612            1
1969            1
1467            1
1182            1
2414            1
1762            1
1301            1
3153            1
1566            1
2208            1
3242            1
4144            1
3304            1
2108            1
2756            1
2370            1
2450            1
1972            1
1788            1
5138            1
1633            1
718             1
943             1
588             1
1144            1
971             1
1277            1
459             1
502             1
735             1
965             1
1550            1
1873            1
1639            1
434             1
1643            1
2422            1
3426            1
4674            1
2154            1
1671            1
3317            1
1374            1
3028            1
2897            1
2150            1
613             1
2115            1
2167            1
3570            1
1806            1
2288            1
2074            1
2596            1
4034            1
3142            1
1791            1
3145            1
2621            1
1921            1
2136            1
2012            1
1355            1
1008            1
1188            1
2406            1
1411            1
1588            1
1585            1
1375            1
1443            1
1334            1
745             1
1592            1
1460            1
1839            1
1172            1
1750            1
1091            1
785             1
554             1
726 - 1137      1
1085            1
673             1
1369            1
2902            1
2928            1
6111            1
885             1
1018            1
890             1
829             1
546             1
1448            1
1539            1
858             1
1909            1
1536            1
1284            1
959             1
1160            1
1072            1
730             1
1688            1
1398            1
1183            1
654             1
777             1
1803            1
2620            1
1953            1
2085            1
1613            1
1545            1
2625            1
2535            1
1880            1
869             1
2100            1
696             1
688             1
1362            1
3137            1
1887            1
582             1
1161            1
1024            1
1537            1
1223            1
1209            1
1984            1
1487            1
972             1
852             1
1205            1
871             1
1579            1
1413            1
1885            1
528             1
611             1
966             1
1041            1
575             1
336             1
591             1
1125            1
819             1
2664            1
1071            1
1417            1
1061            1
1906            1
912             1
1185            1
2805            1
1193            1
1113            1
804             1
686             1
1274            1
1239            1
572             1
812             1
672             1
624             1
1179            1
734             1
2428            1
1597            1
1946            1
2098            1
1414            1
100             1
2609            1
2124            1
3104            1
1070            1
873             1
1858            1
1686            1
1073            1
364             1
521             1
327 - 836       1
913             1
2285            1
963             1
674 - 1569      1
2400            1
1412            1
860             1
2099            1
569             1
1444            1
864             1
1086            1
614             1
578             1
1315            1
1164            1
621             1
932             1
1365            1
1149            1
809             1
542             1
519             1
835             1
403             1
1020            1
509             1
390             1
585             1
580             1
430             1
1730            1
792             1
948             1
2651            1
1760            1
1195            1
2441            1
2036            1
2378            1
2459            1
1772            1
2009            1
1312            1
21439           1
1228            1
1808            1
986 - 1150      1
622             1
1279            1
994             1
953             1
1171            1
470             1
916             1
495             1
2618            1
Name: Sqft, dtype: int64

In [384]:
print(df_rr[df_rr['Sqft'] == '986 - 1150'])

    TysonZip       Address1                Address2      Style  Price   Beds  \
605    35906  98 Sutton Cir  Rainbow City, AL 35906  Apartment    940  2 - 3

    Baths        Sqft
605   1.5  986 - 1150

A lot of them still have 2 values separated by a dash, so I'm just going to keep the lower value (since with the way I wrote my script, it means these only had 1 price listed, and it's more likely they listed the "starting from" price than the highest possible price).

In [385]:
df_rr['Sqft'] = df_rr['Sqft'].str.split(' - ').str[0]

In [386]:
df_rr['Sqft'].value_counts()

700      30
1000     21
1100     21
900      20
1050     18
400      16
1200     15
694      14
950      14
1729     14
800      14
1300     13
600      12
1146     12
550      12
726      11
750      11
850      11
1261     10
1067     10
650       9
1159      9
816       8
1634      8
1372      7
680       7
784       7
1056      7
884       7
660       7
1350      7
1440      6
1082      6
1212      6
1500      6
350       6
1080      6
956       6
500       6
960       6
2002      6
1064      6
1152      6
1680      6
727       5
300       5
952       5
855       5
720       5
1400      5
1796      5
663       5
1738      5
2000      5
2032      5
327       5
1344      5
1380      4
1627      4
1150      4
2054      4
1131      4
450       4
1298      4
1450      4
675       4
1600      4
1216      4
1340      4
640       4
924       4
525       4
1234      4
1800      4
564       4
418       4
1319      4
1280      4
1395      3
974       3
1508      3
1470      3
780       3
1147      3
810       3
1528      3
1040      3
1116      3
1256      3
1025      3
1097      3
825       3
740       3
540       3
568       3
560       3
983       3
872       3
646       3
936       3
1130      3
1120      3
702       3
980       3
1036      3
975       3
935       3
915       3
820       3
1264      3
475       3
1034      3
1092      3
1836      3
842       3
744       3
1700      3
722       3
933       3
725       3
770       3
1127      3
1703      3
1445      3
1463      3
896       3
1415      3
1910      3
620       3
1232      3
1224      3
2500      3
1155      3
625       3
1900      3
1425      3
752       3
1393      3
2600      3
1098      2
1416      2
1980      2
1240      2
1484      2
1233      2
1168      2
1265      2
1255      2
539       2
1982      2
1028      2
1408      2
1314      2
738       2
1132      2
1238      2
1736      2
1329      2
1307      2
1390      2
1075      2
1580      2
1170      2
690       2
670       2
695       2
1221      2
1987      2
1920      2
635       2
737       2
1158      2
1260      2
1281      2
496       2
250       2
1186      2
1614      2
1510      2
741       2
1180      2
1156      2
693       2
1433      2
1477      2
592       2
544       2
2200      2
1013      2
1407      2
570       2
698       2
529       2
874       2
1673      2
1218      2
1442      2
1266      2
1602      2
2039      2
1389      2
2240      2
1142      2
1468      2
676       2
754       2
795       2
849       2
480       2
1027      2
1231      2
2252      2
1290      2
876       2
1618      2
1090      2
1318      2
638       2
904       2
558       2
1410      2
1135      2
1446      2
1720      2
1250      2
1665      2
2190      2
1134      2
3000      2
870       2
1878      2
957       2
1114      2
1472      2
1905      2
630       2
1275      2
1248      2
648       2
925       2
1583      2
1026      2
6480      1
1003      1
1613      1
2085      1
728       1
552       1
954       1
546       1
1840      1
1722      1
1176      1
316       1
3144      1
1638      1
1658      1
2100      1
2301      1
1871      1
1545      1
973       1
1875      1
1411      1
3750      1
869       1
1950      1
2029      1
1880      1
2513      1
1848      1
2492      1
2535      1
1136      1
3152      1
1964      1
2898      1
2435      1
6111      1
2270      1
2625      1
1347      1
2210      1
380       1
1546      1
1398      1
2928      1
1469      1
654       1
1183      1
719       1
1882      1
1773      1
2902      1
1369      1
1324      1
1688      1
1884      1
730       1
1072      1
1128      1
673       1
1085      1
1065      1
3005      1
1160      1
2576      1
1838      1
1874      1
2178      1
2650      1
565       1
708       1
2637      1
1747      1
445       1
1588      1
1953      1
1320      1
5040      1
1850      1
1143      1
1242      1
1897      1
1585      1
1872      1
808       1
1088      1
1110      1
1138      1
1803      1
858       1
777       1
909       1
1364      1
1612      1
2034      1
1974      1
1104      1
2250      1
2355      1
2430      1
1480      1
829       1
1636      1
2620      1
1830      1
890       1
2110      1
1526      1
1669      1
1843      1
1485      1
1038      1
1018      1
1818      1
1746      1
2047      1
1530      1
885       1
2090      1
1337      1
1842      1
1529      1
1017      1
1418      1
682       1
992       1
710       1
1448      1
1053      1
1252      1
1332      1
978       1
425       1
666       1
1556      1
1060      1
944       1
993       1
2585      1
1787      1
1308      1
1042      1
1178      1
1690      1
2473      1
2015      1
1452      1
1527      1
785       1
2362      1
1902      1
1670      1
1297      1
1236      1
688       1
1388      1
1933      1
977       1
2472      1
1244      1
1437      1
1387      1
2171      1
1311      1
696       1
1591      1
790       1
2152      1
440       1
1295      1
1969      1
2094      1
836       1
1936      1
2089      1
1851      1
1976      1
204       1
984       1
20193     1
1717      1
1532      1
1215      1
1276      1
2041      1
2641      1
1512      1
2326      1
1392      1
1140      1
945       1
1702      1
2341      1
1824      1
880       1
1918      1
1753      1
1362      1
1879      1
1375      1
1954      1
1643      1
2009      1
1312      1
21439     1
1228      1
2012      1
2136      1
1808      1
1921      1
2621      1
3145      1
986       1
622       1
1791      1
3142      1
4034      1
2596      1
2074      1
1460      1
2288      1
1806      1
1592      1
1279      1
994       1
1772      1
3570      1
2459      1
1873      1
1301      1
591       1
1125      1
819       1
2664      1
1071      1
1417      1
1061      1
364       1
521       1
1315      1
2378      1
1730      1
792       1
5138      1
1639      1
948       1
2651      1
1760      1
1195      1
2441      1
2036      1
2167      1
953       1
336       1
2115      1
1444      1
864       1
3426      1
1086      1
614       1
913       1
578       1
1164      1
621       1
932       1
2422      1
1365      1
1149      1
809       1
542       1
3137      1
519       1
835       1
403       1
1887      1
1020      1
509       1
1185      1
569       1
2099      1
860       1
745       1
613       1
2150      1
1171      1
470       1
916       1
2897      1
3028      1
495       1
430       1
580       1
585       1
4674      1
390       1
1374      1
2285      1
3317      1
963       1
674       1
2400      1
1412      1
1671      1
2154      1
3153      1
1182      1
1267      1
2406      1
1550      1
804       1
686       1
1274      1
1239      1
572       1
554       1
812       1
672       1
624       1
1179      1
965       1
735       1
734       1
1334      1
2805      1
2428      1
1946      1
2098      1
502       1
1091      1
1414      1
100       1
1113      1
1193      1
1355      1
605       1
665       1
2417      1
683       1
582       1
667       1
959       1
1284      1
1326      1
1010      1
518       1
1536      1
434       1
1030      1
2591      1
2217      1
1467      1
2414      1
1188      1
1909      1
1443      1
1539      1
1008      1
2609      1
2124      1
575       1
3104      1
3304      1
4144      1
1906      1
1024      1
1537      1
1223      1
1209      1
1984      1
1487      1
972       1
852       1
1205      1
3242      1
871       1
2208      1
1579      1
1566      1
1413      1
1161      1
1885      1
611       1
966       1
1041      1
2108      1
1839      1
2756      1
1633      1
1070      1
459       1
1750      1
1277      1
971       1
1144      1
588       1
943       1
718       1
1172      1
1788      1
528       1
1762      1
1972      1
873       1
2450      1
1858      1
1686      1
1073      1
1597      1
2370      1
912       1
2618      1
Name: Sqft, dtype: int64

In [387]:
print(df_rr[df_rr['Sqft'].isnull()])

     TysonZip                            Address1  \
1       73701           1201 E Broadway Ave Apt J
3       73701                       624 N 10th St
4       73701                       812 W Elm Ave
5       73701                     1910 N Grand St
14      79108                   10505 Broadway Dr
15      79108                                 NaN
16      79108                  8403 N Highway 287
20      79108                       4611 Dumas Dr
21      44001                        36 Westwoods
22      44001                        36 Westwoods
31      72764          3810 S Thompson Ave Unit 7
32      72764         3810 S Thompson Ave Unit 25
42      72764          3810 S Thompson Ave Unit 6
43      72764         3810 S Thompson Ave Unit 32
44      72764          3810 S Thompson Ave Unit 5
45      72764         3810 S Thompson Ave Unit 35
46      72764         3810 S Thompson Ave Unit 39
47      72764         3810 S Thompson Ave Unit 21
48      72764         3810 S Thompson Ave Unit 30
49      72764         3810 S Thompson Ave Unit 29
50      72764         3810 S Thompson Ave Unit 14
96      72616                  204 Ember Dr Apt 1
97      72616                  208 Ember Dr Apt 2
119     42101                       132 Pebble Ct
123     42101                       396 Deluth Dr
133     75633                      101 Senior Ave
134     75633                     1100 S Adams St
137     75935                     705 Clifford St
140     39183                       1215 Adams St
149     60641                                 NaN
150     60641                                 NaN
154     60641                5344 W Eddy St Apt 2
155     60641             4037 W Nelson St Unit 1
157     60641           4177 W Belmont Ave Unit 2
158     60641           3153 N Tripp Ave Unit 205
159     60641     5425 W Montrose Ave Unit 5425S3
160     60641     3941 N Keeler Ave Unit 3941-404
161     60641         4022 W Montrose Ave Unit St
162     60641        4250 W Nelson St Unit 4250-2
163     60641        4254 W Nelson St Unit 4254-1
164     60641        4001 W Monttrose Ave Unit St
167     60641       2923 N Long Ave Unit AF2923-2
168     60641        4244 W Nelson St Unit 4244-2
169     60641       4903 W Cullom Ave Unit 4903-3
170     60641  4819-21 W Cornelia Ave Unit 4819-1
171     60641          3243 N Lockwood Ave Unit 2
172     60641        4263 W Nelson St Unit 4263-1
173     60641           3250 N Pulaski Rd Apt 318
175     60641             5201 W Cullom Ave Apt 1
176     60641             5201 W Cullom Ave Apt 2
177     60641             5201 W Cullom Ave Apt 3
178     60641             3450 N Lowell Ave Apt 1
179     60641                   4025 W Melrose St
180     60641                   5257 W Nelson Ave
181     60641                   4121 W Cullom Ave
182     60641                   4121 W Cullom Ave
183     60641           4154 W Berteau Ave Unit B
190     60641             4207 W Roscoe St Unit 2
191     60641         4131 W Belmont Ave Unit 413
192     60641                     5422 W Dakin St
193     60641          4222 N Keystone Ave Apt 1B
195     60641                    5518 W Barry Ave
199     60641      4200 W Belmont Ave Unit 4214-2
211     60641                    1 W Montrose Ave
214     60641           3058 N Kostner Ave Apt 1E
219     60641      4200 W Belmont Ave Unit 4210-3
220     60641            4031 W Melrose St Apt 3N
223     60641        3035 N Kilpatrick Ave Unit 2
229     60641        3035 N Kilpatrick Ave Unit G
246     60641        3035 N Kilpatrick Ave Unit 1
256     60641         4267 W Addison St Unit Grdn
258     60641             4924 W School St Unit 1
260     60641                   4255 W Addison St
261     60641                5039 W Eddy St Apt 2
262     60641          4952 W Berteau Ave Unit 2W
263     60641                 4715 W Cornelia Ave
267     60641      4409 N Kenneth Ave Unit 4411-3
269     60641         4181 W Belmont Ave Unit 201
270     60641         3318 N Leclaire Ave Unit 1S
321     41001                     1300 Downing St
326     39204           2059 Cooperwell Dr Unit B
327     39204           2059 Cooperwell Dr Unit A
357     51501                       1315 Avenue I
361     51501                      2532 S 18th St
363     51501                   625 5th Ave Apt 3
377     30040         3326 Castleberry Village Dr
381     30040                  5430 Crestwick Way
404     30040                   2275 Lexington Ln
405     30040                     2219 Canton Hwy
414     30040          1004 Tribble Gap Rd Apt 1D
418     30040                    3024 Kentmere Dr
449     75237                      2875 Bronco Dr
457     75237                 2732 Meadow Gate Ln
463     24586            1380 Old Quarry Rd Apt 1
464     24586          1380 Old Quarry Rd Unit 10
465     72834                      10278 Dover Ln
473     29640                       306 Gibson Rd
476     29640                         509 Oak Cir
478     29640                   292 E Compass Way
502     29640                   315 E Compass Way
503     29640                   326 E Compass Way
504     29640                   293 E Compass Way
505     29640                   330 E Compass Way
506     29640                   313 E Compass Way
507     29640                   295 E Compass Way
508     29640                   247 E Compass Way
509     29640                   306 E Compass Way
520     66801                         1341 Road R
526     66801                       605 Valley Dr
527     66801                 909 Constitution St
542     72901                       1206 N 6th St
543     72901                    2319 Savannah St
545     72901                      1101 S 18th St
561     72901                2104 Savannah St # 1
562     72901                 912 S 19th St Apt A
575     72901                              N 18th
577     72901                  4412 Jenny Lind Rd
579     72901                       1904G N St Ft
594     72901                              N 18th
596     72901                  4412 Jenny Lind Rd
598     72901                       1904G N St Ft
608     35906                 459 Becky Allen Cir
611     35906               207 St Christopher St
612     35906                    180 Swindall Cir
614     37072                 333 Northcreek Blvd
615     37072                 333 Northcreek Blvd
645     72638                  204 Ember Dr Apt 1
646     72638                  208 Ember Dr Apt 2
650     76117                   5151 Broadway Ave
691     77029                       301 Mascot St
693     77029                    2202 McCarty Ave
718     38343                     146 Jadewood Dr
775     32254               3510 Bougainvillea St
795     32254               3510 Bougainvillea St
819     66106                       4917 Vista St
820     66106                 1302-1304 S 32nd St
825     46947                   1323 Riverside Dr
826     46947                      1528 George St
831     27332                       50 Kittery Pt
832     27332                     36 Hill Side Ln
851     65708                     221 Fairway Ave
852     28112           3141 Highway 74 # 74-2421
859     28112                  1009 Southridge Dr
861     28112                  2017 Briarberry Ln
862     28112                          3141 E Hwy
863     28112                   1406 Virginia Ave
865     28112                   4910 Pageland Hwy
898     72114                 900 W 16th St Apt 2
921     72114        900 W 16th St Unit Newrenter
922     72114     630 Riverfront Park Dr Unit 123
939     72114     630 Riverfront Park Dr Unit 123
956     17557                 117 E Main St Apt 4
957     17557                    15 Colonial Park
962     54961                       702 Algoma St
1092    76180                    4909 Wyoming Trl
1153    38261            811 W Reelfoot Ave Lot 1
1154    38261            811 W Reelfoot Ave Lot 1
1184    71602                   1002 N Hemlock St
1186    04102               44 Stevens Ave Unit 2
1188    04102                       243 Spring St
1196    30161                      8 Thomas Rd NE
1201    30161                 27 Willingham St SW
1202    30161                    26 Stevens St NE
1203    30161                    200 E 12th St SW
1204    30161                    202 E 12th St SW
1206    30161                   513 Wilson Ave SW
1207    30161      1211 Spring Creek St SW Unit A
1208    30161                      304-B Pearl St
1216    94580                16201 Hesperian Blvd
1217    94580                16201 Hesperian Blvd
1252    78155                       813 Zunker St
1257    78155                     838 Saint James
1275    78155                     1333 Hidalgo St
1294    78155         800 N State Highway 123 Byp
1301    78155                      3821 Donald Dr
1414    64507             706 S Woodbine Rd Ste D
1450    72704                    1211 N Rupple Rd
1473    72704                      3114 W Anne St
1480    72704                  120 N Hinsdale Ave
1530    08360                      215 S East Ave
1531    08360                        262 Wheat Rd
1549    48091                      7544 Dodge Ave
1550    48091                       7068 Hupp Ave
1567    50703                      76 Mulberry St
1568    50703                      76 Mulberry St
1571    50703                 314 Lester St Apt 1
1572    50703                     24 Van Buren St
1574    50703                     213 Mulberry St
1580    50703                 628 Sycamore St # 2
1581    50703                 628 Sycamore St # 1

                            Address2      Style  Price     Beds  Baths Sqft
1                     Enid, OK 73701      House    700        1      1  NaN
3                     Enid, OK 73701      House    650        2      1  NaN
4                     Enid, OK 73701      House    850        3      2  NaN
5                     Enid, OK 73701      House   2000        2      1  NaN
14                Amarillo, TX 79108      Other    850        2      2  NaN
15                               NaN      Other   1200        2    1.5  NaN
16                Amarillo, TX 79108      Other    965        3      2  NaN
20                Amarillo, TX 79108      Other    845        2      1  NaN
21                 Amherst, OH 44001  Apartment   1099        2  1 - 2  NaN
22                 Amherst, OH 44001  Apartment   1565        4  1 - 2  NaN
31              Springdale, AR 72764      House    750        2      1  NaN
32              Springdale, AR 72764      House    895        2      1  NaN
42              Springdale, AR 72764      House    895        2      1  NaN
43              Springdale, AR 72764      House    895        2      1  NaN
44              Springdale, AR 72764      House    895        2      1  NaN
45              Springdale, AR 72764      House   1000        2      1  NaN
46              Springdale, AR 72764      House   1000        2      1  NaN
47              Springdale, AR 72764      House   1000        2      1  NaN
48              Springdale, AR 72764      House   1350        3      2  NaN
49              Springdale, AR 72764      House   1375        3      2  NaN
50              Springdale, AR 72764      House   1400        3      2  NaN
96            Green Forest, AR 72638  Apartment    920        1      1  NaN
97            Green Forest, AR 72638  Apartment    650        1      1  NaN
119          Bowling Green, KY 42101      House    850        2    1.5  NaN
123          Bowling Green, KY 42101      House   1600        3      2  NaN
133               Carthage, TX 75633  Apartment    492        1      1  NaN
134               Carthage, TX 75633  Apartment    693        2      1  NaN
137                 Center, TX 75935  Apartment    525        2      1  NaN
140              Vicksburg, MS 39183      Other   1400        1      1  NaN
149                              NaN      House   1250        1      1  NaN
150                              NaN      House   1600        2      1  NaN
154                Chicago, IL 60641      Condo   1550        2      1  NaN
155                Chicago, IL 60641      House   2600        3      2  NaN
157                Chicago, IL 60641      Condo   2500        2      2  NaN
158                Chicago, IL 60641      Condo   2700        2      2  NaN
159                Chicago, IL 60641  Apartment   1250        1      1  NaN
160                Chicago, IL 60641  Apartment   1855        1      1  NaN
161                Chicago, IL 60641  Apartment   2750   Studio      2  NaN
162                Chicago, IL 60641  Apartment   1070        2      1  NaN
163                Chicago, IL 60641  Apartment   1375        2      1  NaN
164                Chicago, IL 60641  Apartment   4400   Studio      2  NaN
167                Chicago, IL 60641  Apartment   1350        2      1  NaN
168                Chicago, IL 60641  Apartment   1600        2      1  NaN
169                Chicago, IL 60641  Apartment   1500        2      1  NaN
170                Chicago, IL 60641  Apartment   1775        2      1  NaN
171                Chicago, IL 60641  Apartment    875   Studio      1  NaN
172                Chicago, IL 60641  Apartment   1600        2      1  NaN
173                Chicago, IL 60641  Apartment   1100   Studio      1  NaN
175                Chicago, IL 60641  Apartment   2600        3      2  NaN
176                Chicago, IL 60641  Apartment   2650        3      2  NaN
177                Chicago, IL 60641  Apartment   2700        3      2  NaN
178                Chicago, IL 60641  Apartment   1725        3      1  NaN
179                Chicago, IL 60641  Apartment   1175        1      1  NaN
180                Chicago, IL 60641  Apartment   1225        1      1  NaN
181                Chicago, IL 60641  Apartment   1280        1      1  NaN
182                Chicago, IL 60641  Apartment   1295        1      1  NaN
183                Chicago, IL 60641      Condo   3600        3    2.5  NaN
190                Chicago, IL 60641  Apartment   2850        2      2  NaN
191                Chicago, IL 60641  Apartment   2350        2      2  NaN
192                Chicago, IL 60641  Apartment   1250        2      1  NaN
193                Chicago, IL 60641  Apartment   1650        2      1  NaN
195                Chicago, IL 60641  Apartment   1095        1      1  NaN
199                Chicago, IL 60641  Apartment   4200        3    3.5  NaN
211                Chicago, IL 60641      House   1200        1      1  NaN
214                Chicago, IL 60641  Apartment   1850        3      1  NaN
219                Chicago, IL 60641  Apartment   4725        4    3.5  NaN
220                Chicago, IL 60641  Apartment   1175        1      1  NaN
223                Chicago, IL 60641      House   1950        2      1  NaN
229                Chicago, IL 60641      House   1550        2      1  NaN
246                Chicago, IL 60641      House   2250        3      2  NaN
256                Chicago, IL 60641  Apartment   1050        1      1  NaN
258                Chicago, IL 60641  Apartment   1500        2      1  NaN
260                Chicago, IL 60641  Apartment   1050        1      1  NaN
261                Chicago, IL 60641  Apartment   1800        3      1  NaN
262                Chicago, IL 60641  Apartment   1275        1      1  NaN
263                Chicago, IL 60641  Apartment   1475        2      1  NaN
267                Chicago, IL 60641  Apartment   1350        1      1  NaN
269                Chicago, IL 60641      Condo   3600        3      2  NaN
270                Chicago, IL 60641  Apartment   1675        2      1  NaN
321            Cold Spring, KY 41076  Apartment   1275        2      2  NaN
326                Jackson, MS 39204      Condo   1050        2      2  NaN
327                Jackson, MS 39204      Condo   1050        2      2  NaN
357         Council Bluffs, IA 51501      House    900        2      1  NaN
361         Council Bluffs, IA 51501      House    900        2      1  NaN
363         Council Bluffs, IA 51501      Condo    810        2      1  NaN
377                Cumming, GA 30040   Townhome   2400        3    2.5  NaN
381                Cumming, GA 30040      House   2500        3    2.5  NaN
404                Cumming, GA 30040      House   2095        3    2.5  NaN
405                Cumming, GA 30040      House   1600        3      1  NaN
414                Cumming, GA 30040      House   1425        2      1  NaN
418                Cumming, GA 30040   Townhome   2150        3    2.5  NaN
449                 Dallas, TX 75237      House   2265        4      2  NaN
457                 Dallas, TX 75237      House   1785        3      2  NaN
463               Ringgold, VA 24586  Apartment    700        2      1  NaN
464               Ringgold, VA 24586  Apartment    700        2      1  NaN
465             Dardanelle, AR 72834      House   1000        3      1  NaN
473                 Easley, SC 29640      House   1195        3      2  NaN
476                 Easley, SC 29640      House   2600        4    2.5  NaN
478                 Easley, SC 29640   Townhome   1599        3    2.5  NaN
502                 Easley, SC 29640   Townhome   1599        3    2.5  NaN
503                 Easley, SC 29640   Townhome   1599        3    2.5  NaN
504                 Easley, SC 29640   Townhome   1649        3    2.5  NaN
505                 Easley, SC 29640   Townhome   1649        3    2.5  NaN
506                 Easley, SC 29640   Townhome   1649        3    2.5  NaN
507                 Easley, SC 29640   Townhome   1599        3    2.5  NaN
508                 Easley, SC 29640   Townhome   1600        3    2.5  NaN
509                 Easley, SC 29640   Townhome   1649        3    2.5  NaN
520                Emporia, KS 66801      House    900        3      1  NaN
526                Emporia, KS 66801  Apartment    500        2      2  NaN
527                Emporia, KS 66801  Apartment    500        2      1  NaN
542             Fort Smith, AR 72901      House    850        2      1  NaN
543             Fort Smith, AR 72901      House    695        2      1  NaN
545             Fort Smith, AR 72901      House    895        3      2  NaN
561             Fort Smith, AR 72901      Condo    850        2      1  NaN
562             Fort Smith, AR 72901      Condo    600        3      1  NaN
575             Fort Smith, AR 72901  Apartment    560      NaN      1  NaN
577             Fort Smith, AR 72901      House    725        2      1  NaN
579             Fort Smith, AR 72901  Apartment    640        1      1  NaN
594             Fort Smith, AR 72901  Apartment    560      NaN      1  NaN
596             Fort Smith, AR 72901      House    725        2      1  NaN
598             Fort Smith, AR 72901  Apartment    640        1      1  NaN
608           Rainbow City, AL 35906      House    900        3    1.5  NaN
611           Rainbow City, AL 35906  Apartment    963        2      2  NaN
612           Rainbow City, AL 35906      House   2300        4   2.5+  NaN
614         Goodlettsville, TN 37072  Apartment   1649        1  1 - 2  NaN
615         Goodlettsville, TN 37072  Apartment   2107        3  1 - 2  NaN
645           Green Forest, AR 72638  Apartment    920        1      1  NaN
646           Green Forest, AR 72638  Apartment    650        1      1  NaN
650            Haltom City, TX 76117      House    975        1      1  NaN
691                Houston, TX 77029      Other    600   Studio    NaN  NaN
693                Houston, TX 77029      Other   3800   Studio    NaN  NaN
718                Jackson, TN 38305      House   2295        5    2.5  NaN
775           Jacksonville, FL 32254      Condo   1150        3      3  NaN
795           Jacksonville, FL 32254      Condo   1150        3      3  NaN
819            Kansas City, KS 66106      House   1085        2      1  NaN
820            Kansas City, KS 66106  Apartment    750        1      1  NaN

In [388]:
# Convert sqft to numeric while keeping null values as null

df_rr['Sqft'] = pd.to_numeric(df_rr['Sqft'], errors='coerce')

In [389]:
df_rr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1599 entries, 0 to 1609
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   TysonZip  1599 non-null   object
 1   Address1  1595 non-null   object
 2   Address2  1595 non-null   object
 3   Style     1599 non-null   object
 4   Price     1599 non-null   int64
 5   Beds      1597 non-null   object
 6   Baths     1594 non-null   object
 7   Sqft      1409 non-null   float64
dtypes: float64(1), int64(1), object(6)
memory usage: 112.4+ KB

In [390]:
# Checking for duplicates (and reviewing them first - because sometimes apartments have the same address)

df_rr_dups = df_rr[df_rr.duplicated()]

print(df_rr_dups)

    TysonZip                         Address1                     Address2  \
74     72764             315 Texas Ln Apt 206         Springdale, AR 72764
75     72764         1414 S Powell St Apt 202         Springdale, AR 72764
76     72764         1414 S Powell St Apt 102         Springdale, AR 72764
77     72764         1706 S Powell St Apt 203         Springdale, AR 72764
78     72764            1160 Dove Loop Unit B         Springdale, AR 72764
79     72764                884 Palisades Ave         Springdale, AR 72764
80     72764           1600 Juniper Cir Apt B         Springdale, AR 72764
81     72764              3444 Acorn Falls Ln         Springdale, AR 72764
82     72764         1006 Walnut Ave Unit 101         Springdale, AR 72764
83     72764                 3568 Bastille St         Springdale, AR 72764
84     72764              420 Park St Apt 201         Springdale, AR 72764
85     72764                  703 W Grove Ave         Springdale, AR 72764
86     72764          700 Virginia St Apt 101         Springdale, AR 72764
217    60641              5160 W Montrose Ave            Chicago, IL 60641
516    29640      3653 Farrs Bridge Rd Unit A             Easley, SC 29640
583    72901                      2014 N E St         Fort Smith, AR 72901
584    72901                   4407 S 26th St         Fort Smith, AR 72901
586    72901                    721 N 21st St         Fort Smith, AR 72901
587    72901                      2520 N E St         Fort Smith, AR 72901
588    72901                   1624 Fresno St         Fort Smith, AR 72901
589    72901                   1624 Fresno St         Fort Smith, AR 72901
590    72901                     322 N 6th St         Fort Smith, AR 72901
591    72901               5401 Jenny Lind Rd         Fort Smith, AR 72901
592    72901               5401 Jenny Lind Rd         Fort Smith, AR 72901
593    72901              622 N 19th St Apt 2         Fort Smith, AR 72901
594    72901                           N 18th         Fort Smith, AR 72901
595    72901                    905 S 19th St         Fort Smith, AR 72901
596    72901               4412 Jenny Lind Rd         Fort Smith, AR 72901
597    72901  18 Hiland Dr Unit 18HILANDDRIVE         Fort Smith, AR 72901
598    72901                    1904G N St Ft         Fort Smith, AR 72901
599    72901                    912 Lecta Ave         Fort Smith, AR 72901
600    72901                    722 S 19th St         Fort Smith, AR 72901
601    72901             1500 Independence St         Fort Smith, AR 72901
791    32254                   920 Ontario St       Jacksonville, FL 32254
792    32254                    2853 W 1st St       Jacksonville, FL 32254
793    32254                   3327 Dignan St       Jacksonville, FL 32254
794    32254                  1091 Detroit St       Jacksonville, FL 32254
795    32254            3510 Bougainvillea St       Jacksonville, FL 32254
796    32254                 222 Shortreed St       Jacksonville, FL 32254
797    32254                    1094 Hood Ave       Jacksonville, FL 32254
798    32254                  1055 Melson Ave       Jacksonville, FL 32254
799    32254            414 Willow Branch Ave       Jacksonville, FL 32254
800    32254                    2863 W 9th St       Jacksonville, FL 32254
801    32254                   3228 Dignan St       Jacksonville, FL 32254
802    32254                   3055 Dignan St       Jacksonville, FL 32254
803    32254                  849 Superior St       Jacksonville, FL 32254
804    32254               2940 Fitzgerald St       Jacksonville, FL 32254
805    32254                3359 Columbus Ave       Jacksonville, FL 32254
806    32254            3055 Dignan St Unit 1       Jacksonville, FL 32254
807    32254               3246 Warrington St       Jacksonville, FL 32254
808    32254                  970 Douglas Cir       Jacksonville, FL 32254
809    32254                   3048 W 19th St       Jacksonville, FL 32254
810    32254                1073 Seminole Ave       Jacksonville, FL 32254
939    72114  630 Riverfront Park Dr Unit 123  North Little Rock, AR 72114
940    72114                    824 W 25th St  North Little Rock, AR 72114
941    72114                 1618 N Locust St  North Little Rock, AR 72114
942    72114                    2908 E 2nd St  North Little Rock, AR 72114
943    72114              1405 W Long 17th St  North Little Rock, AR 72114
944    72114             115 College Park Cir  North Little Rock, AR 72114
945    72114                    1822 Maple St  North Little Rock, AR 72114
946    72114                4295 Shadcrest Cv        Little Rock, AR 72114
947    72114                     1507 Nona St  North Little Rock, AR 72114
948    72114                     1507 Nona St  North Little Rock, AR 72114
949    72114    630 W Riverfront Dr Unit 201B  North Little Rock, AR 72114
950    72114      1922 W Short 17th St Unit 2  North Little Rock, AR 72114
951    72114                      1004 N D St  North Little Rock, AR 72114
952    72114                   1513 Marion St  North Little Rock, AR 72114
953    72114              1603 W Long 17th St  North Little Rock, AR 72114
954    72114          1101 Dorothy Rodham Way  North Little Rock, AR 72114
955    72114                   1235 W 10th St  North Little Rock, AR 72114

              Style  Price     Beds Baths    Sqft
74            Condo   1249        3     2  1280.0
75            Condo    695        1     1   400.0
76            Condo    695        1     1   400.0
77            Condo    695        1     1   400.0
78            Other   1050        3     2  1300.0
79            House   2145        4     2  1982.0
80        Apartment    850        2     1   900.0
81            House   1495        3     2  1700.0
82            House    795        2     1   744.0
83            House   1950        3   2.5  1980.0
84            House    625        1     1   400.0
85            House   1500        3     1  1100.0
86            Other    795        2     1   738.0
217       Apartment   1275        1     1   750.0
516           Condo   1349        2     1   900.0
583           House   1095        2     1   924.0
584           House   1195        2     1   936.0
586           House   1295        3     2  1260.0
587       Apartment    625        1     1   550.0
588       Apartment    675        1     1   635.0
589       Apartment    795        2     1   935.0
590       Apartment    650        1     1   525.0
591       Apartment    675        1     1   600.0
592       Apartment    795        2     1   737.0
593       Apartment    600        1     1   350.0
594       Apartment    560      NaN     1     NaN
595           House   1295        3     2  1158.0
596           House    725        2     1     NaN
597  Duplex/Triplex   1100        3     2   820.0
598       Apartment    640        1     1     NaN
599           House    500        1     1   475.0
600           House    950        2     1  1034.0
601           House   1195        2     1  1092.0
791           House   1249        3     1  1142.0
792           House   1600        4     2  1468.0
793           House   1425        4     2  1234.0
794           House   1207        2     1   754.0
795           Condo   1150        3     3     NaN
796           House    995        2     1   663.0
797           House   1435  Studio+     1  1224.0
798           House   1500        3     2  1280.0
799           House   1450        3     1  1200.0
800           House   1199        3     1  1200.0
801           House   1300        4   1.5  1056.0
802           House   1695        3     2  1050.0
803           House   1300        2     1   795.0
804           House   1275        3     2   849.0
805       Apartment   1000        1     1   550.0
806           House   1695        3     2  1050.0
807           House   1300        2     1   952.0
808           House   1250        3   1.5  1027.0
809           House   1350        3     1  1231.0
810           House   1508        3     1   950.0
939       Apartment    100        1     1     NaN
940           House   1250        3     2  1614.0
941           House   1100        3   1.5  1510.0
942       Apartment    620        1     1   741.0
943       Apartment    495        1     1   600.0
944       Apartment    595        1     1   646.0
945       Apartment    695        2     1  1180.0
946           House   1110        3     1  1156.0
947       Apartment    595        1     1   600.0
948       Apartment    650        2     1   720.0
949       Apartment   1250        2     2  1150.0
950       Apartment    550        2     1   800.0
951       Apartment    625        1     1   693.0
952       Apartment    650        1     1   700.0
953       Apartment    650        3     1  1036.0
954       Apartment    895        3     1  1380.0
955       Apartment   1395        3     2  1433.0

I manually checked some of these addresses and they do mostly look like multi-unit properties, so I'm going to go ahead and leave them

In [391]:
# Checking for missing values

missing_values = df_rr.isnull().sum()

# total rows in dataframe
total_rows = df_rr.shape[0]

# making it show me all the rows
pd.options.display.max_rows = len(df_rr.dtypes)

# calculating percentage of missing values
percent_missing = ((missing_values / total_rows) * 100).round(2)

# Making a dataframe to show missing values
missing_value_table = pd.concat([missing_values, percent_missing], axis=1)

# Naming columns for sorting
missing_value_table.columns = ['Missing Values', 'Percent Missing']

# sorting the view based on most missing values %
missing_value_table.sort_values('Percent Missing', ascending=True, inplace=True)

print(missing_value_table)

          Missing Values  Percent Missing
TysonZip               0             0.00
Style                  0             0.00
Price                  0             0.00
Beds                   2             0.13
Address1               4             0.25
Address2               4             0.25
Baths                  5             0.31
Sqft                 190            11.88

Sqft has a lot of missing values, but I think that's ok. At this point, the main interest are whether or not units for rent are available within a certain price range at the food facility locations

In [392]:
# counting number of unique values in each column

print(df_rr.nunique())

TysonZip      75
Address1    1357
Address2      88
Style          7
Price        472
Beds          13
Baths         14
Sqft         653
dtype: int64

So only 75 of the 95 TysonZips had rental units available.  That seems like less than anticipated. I'm going to check a lot of those zip codes manually and see if it stays that way, or if there was some error with the scraper.  The other details look like I'd expect *maybe*, though the large number of different Beds and Baths units might indicate there's still something to be cleaned in the cleaning phase.

I checked out all of those zip codes manually and it's true that there's nothing there. So the scraper worked, but those places are apparently small enough that they can't meet rental housing demand and/or don't list on major sites like realtor.com (I also checked a couple of them on Trulia and also nothing)

### 7C. Data Cleaning

In [393]:
# I'm going to check the value counts for each columns because there's probably still some cleaning to do on Beds and Baths

df_rr['Style'].value_counts()

Apartment         694
House             664
Townhome           76
Condo              66
Other              62
Condo/Townhome     22
Duplex/Triplex     15
Name: Style, dtype: int64

In [394]:
# making it show me all the rows
pd.options.display.max_rows = len(df_rr['Beds'].value_counts())

df_rr['Beds'].value_counts()

3             564
2             462
1             317
4             162
Studio         47
5              19
Studio+        15
2 - 3           3
6               2
Studio - 2      2
1 - 2           2
1 - 3           1
1 - 4           1
Name: Beds, dtype: int64

In [395]:
# I'm going to keep the first value in those that say "2-3" and stuff like that (for the same reason as above, because
# if they only listed one price, they probably listed the starting price, adn thus what would apply to the smallest unit)

df_rr['Beds'] = df_rr['Beds'].str.split(' - ').str[0]

In [396]:
# Changing Studio+ to Studio
df_rr['Beds'] = df_rr['Beds'].replace({'Studio+': 'Studio'})

In [397]:
df_rr['Beds'].value_counts()

3         564
2         465
1         321
4         162
Studio     64
5          19
6           2
Name: Beds, dtype: int64

In [398]:
# making it show me all the rows
pd.options.display.max_rows = len(df_rr['Baths'].value_counts())

df_rr['Baths'].value_counts()

1          745
2          575
2.5        130
3.5         42
1.5         41
3           33
1 - 2        9
4            8
4.5          5
0.5+         2
5.5+         1
3.5+         1
2.5+         1
1 - 2.5      1
Name: Baths, dtype: int64

In [399]:
# Keeping the first number when there's a -, for the same reason as above

df_rr['Baths'] = df_rr['Baths'].str.split(' - ').str[0]

In [403]:
# Changing Baths+ to value without +

df_rr['Baths'] = df_rr['Baths'].replace({'5.5+': '5.5', '3.5+': '3.5', '2.5+': '2.5'})

In [404]:
# making it show me all the rows
pd.options.display.max_rows = len(df_rr['Baths'].value_counts())

df_rr['Baths'].value_counts()

1       755
2       575
2.5     131
3.5      43
1.5      41
3        33
4         8
4.5       5
0.5+      2
5.5       1
Name: Baths, dtype: int64

In [409]:
# Going to split Address 2 into city, state, and zip

df_rr['City'] = df_rr['Address2'].str.split(',', expand=True)[0]

In [410]:
# Now I'm making a new column for the state abbreviation

df_rr['State'] = df_rr['Address2'].str.split(', ', expand=True)[1]
df_rr['State'] = df_rr['State'].str.split(' ', expand=True)[0]

In [411]:
# Now I'm going to try to do that with zip code.

df_rr['Zip'] = df_rr['Address2'].str.split(', ', expand=True)[1]
df_rr['Zip'] = df_rr['Zip'].str.split(' ', expand=True)[1]

In [416]:
# counting number of unique values in each column

print(df_rr.nunique())

TysonZip      75
Address1    1357
Address2      88
Style          7
Price        472
Beds           7
Baths         10
Sqft         653
City          81
State         25
Zip           77
dtype: int64

So we only have a couple more in Zip than we have in TysonZip, which means even when the search automatically expands by 3 miles when nothing found in original zip code, in only 2 of those instances were they able to find rental property outside the zip code but still in the local radius.  Doesn't bode well for those food processing facilities that don't have rentals within their zip code - it seems to indicate no rentals available in the local vicinity either.

### 7D. Basic Descriptive Analysis

In [405]:
# Checking basic stats on each column

# making it show me all the rows
pd.options.display.max_rows = len(df_rr.dtypes)

df_rr.describe().applymap(lambda x: f"{x:0.2f}")

         Price      Sqft
count  1599.00   1409.00
mean   1531.75   1247.92
std     717.73    964.62
min       1.00    100.00
25%    1017.50    784.00
50%    1434.00   1100.00
75%    1870.00   1470.00
max    6300.00  21439.00

That seems about like I'd expect, though it's terrible how high rent prices are for relatively small homes

In [406]:
# Now I'm going to count unique values in each object column

df_rr['Address1'].value_counts()

401 E Ave              4
6021 Parker Blvd       4
5401 Jenny Lind Rd     4
1507 Nona St           4
                      ..
1410 C St S            1
2510 Ionia St          1
912 S 19th St Apt A    1
566 Alice St           1
Name: Address1, Length: 1357, dtype: int64

In [407]:
# Making list of duplicates

duplicates_rr = df_rr[df_rr.duplicated(['Address1'], keep=False)]

# making it show me all the rows
pd.options.display.max_rows = len(duplicates_rr)

print(duplicates_rr)

     TysonZip                         Address1  \
15      79108                              NaN
17      79108                              NaN
21      44001                     36 Westwoods
22      44001                     36 Westwoods
23      44001                   7055 Quarry Rd
24      44001                   7055 Quarry Rd
25      72764               1701 S West End St
26      72764               1701 S West End St
27      72764                1517 Electric Ave
28      72764                1517 Electric Ave
29      72764                    5325 N Oak St
30      72764                    5325 N Oak St
34      72764         514 Butterfield Coach Rd
35      72764         514 Butterfield Coach Rd
36      72764               3702-B Locksley St
37      72764               3702-B Locksley St
38      72764                   1406 Oriole St
39      72764                   1406 Oriole St
40      72764                   726 E Emma Ave
41      72764                   726 E Emma Ave
61      72764             315 Texas Ln Apt 206
62      72764         1414 S Powell St Apt 202
63      72764         1414 S Powell St Apt 102
64      72764         1706 S Powell St Apt 203
65      72764            1160 Dove Loop Unit B
66      72764                884 Palisades Ave
67      72764           1600 Juniper Cir Apt B
68      72764              3444 Acorn Falls Ln
69      72764         1006 Walnut Ave Unit 101
70      72764                 3568 Bastille St
71      72764              420 Park St Apt 201
72      72764                  703 W Grove Ave
73      72764          700 Virginia St Apt 101
74      72764             315 Texas Ln Apt 206
75      72764         1414 S Powell St Apt 202
76      72764         1414 S Powell St Apt 102
77      72764         1706 S Powell St Apt 203
78      72764            1160 Dove Loop Unit B
79      72764                884 Palisades Ave
80      72764           1600 Juniper Cir Apt B
81      72764              3444 Acorn Falls Ln
82      72764         1006 Walnut Ave Unit 101
83      72764                 3568 Bastille St
84      72764              420 Park St Apt 201
85      72764                  703 W Grove Ave
86      72764          700 Virginia St Apt 101
89      72764                1299 Electric Ave
90      72764                1299 Electric Ave
94      72764                608 Black Oak Ave
95      72764                608 Black Oak Ave
96      72616               204 Ember Dr Apt 1
97      72616               208 Ember Dr Apt 2
99      42101                  2244 Hickory St
100     42101                  2244 Hickory St
127     42101             1799 Russellville Rd
128     42101             1799 Russellville Rd
131     74728                      100 Abby Ln
132     74728                      100 Abby Ln
138     39183             4223 I20 Frontage Rd
139     39183             4223 I20 Frontage Rd
141     39183              4225 20 Frontage Rd
142     39183              4225 20 Frontage Rd
143     39183                   2501 Culkin Rd
144     39183                   2501 Culkin Rd
145     60641               4179 W Belmont Ave
146     60641               4179 W Belmont Ave
147     60641               4200 W Belmont Ave
148     60641               4200 W Belmont Ave
149     60641                              NaN
150     60641                              NaN
181     60641                4121 W Cullom Ave
182     60641                4121 W Cullom Ave
210     60641              5160 W Montrose Ave
217     60641              5160 W Montrose Ave
248     60641                  1101 11 W Grace
249     60641                  1101 11 W Grace
280     72756              3302 N Dixieland Rd
281     72756              3302 N Dixieland Rd
300     72756                 1603 W Walnut St
301     72756                 1603 W Walnut St
303     45246                     100 Kelly Rd
304     45246                     100 Kelly Rd
305     45246               11580 Olde Gate Dr
306     45246               11580 Olde Gate Dr
308     45246                51 Bishopsgate Dr
309     45246                51 Bishopsgate Dr
312     45246              1235 Chesterdale Dr
313     45246              1235 Chesterdale Dr
314     45246                    11777 Rose Ln
315     45246                    11777 Rose Ln
316     28610                 2985 N Oxford St
317     28610                 2985 N Oxford St
318     41001                     100 Aqua Way
319     41001                     100 Aqua Way
322     39204                 2010 Chadwick Dr
323     39204                 2010 Chadwick Dr
324     39204                  1533 Raymond Rd
325     39204                  1533 Raymond Rd
334     39204                 1805 Hospital Dr
335     39204                 1805 Hospital Dr
339     39204                  1142 Raymond Rd
340     39204                  1142 Raymond Rd
341     39204               1595 W Highland Dr
342     39204               1595 W Highland Dr
344     49684                   309 W Front St
345     49684                   309 W Front St
347     49684                  851 Fitzhugh Dr
348     49684                  851 Fitzhugh Dr
351     51501            4141 Rivers Edge Pkwy
352     51501            4141 Rivers Edge Pkwy
353     51501                     20 S 41st St
354     51501                     20 S 41st St
355     51501                   3201 Renner Dr
356     51501                   3201 Renner Dr
364     30040              350 Bradley Park Ln
365     30040              350 Bradley Park Ln
366     30040                 98 Buford Dam Rd
367     30040                 98 Buford Dam Rd
432     75237           7272 Marvin D Love Fwy
433     75237           7272 Marvin D Love Fwy
434     75237           7575 S Westmoreland Rd
435     75237           7575 S Westmoreland Rd
436     75237           7550 S Westmoreland Rd
437     75237           7550 S Westmoreland Rd
439     75237                   3801 Gannon Ln
440     75237                   3801 Gannon Ln
441     75237           7310 Marvin D Love Fwy
442     75237           7310 Marvin D Love Fwy
443     75237                5959 Watership Ln
444     75237                5959 Watership Ln
445     75237               8004 W Virginia Dr
446     75237               8004 W Virginia Dr
447     75237               4311 Woodhollow Dr
448     75237               4311 Woodhollow Dr
451     75237               3636 W Red Bird Ln
452     75237               3636 W Red Bird Ln
453     75237           6010 S Westmoreland Rd
454     75237           6010 S Westmoreland Rd
455     75237                4060 Preferred Pl
456     75237                4060 Preferred Pl
459     75237                 3900 Investor Dr
460     75237                 3900 Investor Dr
461     75237             8501 Old Hickory Trl
462     75237             8501 Old Hickory Trl
467     29640               130 Perry Bend Cir
468     29640               130 Perry Bend Cir
469     29640                     601 S 5th St
470     29640                     601 S 5th St
471     29640                    105 Gettys Ln
472     29640                    105 Gettys Ln
515     29640      3653 Farrs Bridge Rd Unit A
516     29640      3653 Farrs Bridge Rd Unit A
518     66801           1200 Whittier Place Ln
519     66801           1200 Whittier Place Ln
522     66801                  2935 W 24th Ave
523     66801                  2935 W 24th Ave
524     66801                 1533 Merchant St
525     66801                 1533 Merchant St
528     66801                   736 E 12th Ave
529     66801                   736 E 12th Ave
530     66801                   1931 W 24th St
531     66801                   1931 W 24th St
533     66801                    110 W 6th Ave
534     66801                    110 W 6th Ave
535     66801                 1201 Triplett Dr
536     66801                 1201 Triplett Dr
540     72901                   4801 S 31st St
541     72901                   4801 S 31st St
564     72901                      2014 N E St
565     72901                   4407 S 26th St
567     72901                    721 N 21st St
568     72901                      2520 N E St
569     72901                   1624 Fresno St
570     72901                   1624 Fresno St
571     72901                     322 N 6th St
572     72901               5401 Jenny Lind Rd
573     72901               5401 Jenny Lind Rd
574     72901              622 N 19th St Apt 2
575     72901                           N 18th
576     72901                    905 S 19th St
577     72901               4412 Jenny Lind Rd
578     72901  18 Hiland Dr Unit 18HILANDDRIVE
579     72901                    1904G N St Ft
580     72901                    912 Lecta Ave
581     72901                    722 S 19th St
582     72901             1500 Independence St
583     72901                      2014 N E St
584     72901                   4407 S 26th St
586     72901                    721 N 21st St
587     72901                      2520 N E St
588     72901                   1624 Fresno St
589     72901                   1624 Fresno St
590     72901                     322 N 6th St
591     72901               5401 Jenny Lind Rd
592     72901               5401 Jenny Lind Rd
593     72901              622 N 19th St Apt 2
594     72901                           N 18th
595     72901                    905 S 19th St
596     72901               4412 Jenny Lind Rd
597     72901  18 Hiland Dr Unit 18HILANDDRIVE
598     72901                    1904G N St Ft
599     72901                    912 Lecta Ave
600     72901                    722 S 19th St
601     72901             1500 Independence St
602     72901                   1511 Boston St
603     72901                   1511 Boston St
606     35906                  3715 Rainbow Dr
607     35906                  3715 Rainbow Dr
614     37072              333 Northcreek Blvd
615     37072              333 Northcreek Blvd
616     37072                    110 Harris St
617     37072                    110 Harris St
618     37072                    100 Lennox Pl
619     37072                    100 Lennox Pl
634     37072                     452 Moss Trl
635     37072                     452 Moss Trl
638     37072         100 Robert Cartwright Dr
639     37072         100 Robert Cartwright Dr
642     37072                  30 Dry Creek Rd
643     37072                  30 Dry Creek Rd
645     72638               204 Ember Dr Apt 1
646     72638               208 Ember Dr Apt 2
648     76117            5613 Coventry Park Dr
649     76117            5613 Coventry Park Dr
662     76117                    5501 Adams Dr
663     76117                    5501 Adams Dr
670     76117                     3001 Jane Ln
671     76117                     3001 Jane Ln
675     76117             5101 Springlake Pkwy
676     76117             5101 Springlake Pkwy
678     76117             5301 Springlake Pkwy
679     76117             5301 Springlake Pkwy
681     76117             5201 Springlake Pkwy
682     76117             5201 Springlake Pkwy
708     38343             33 Constellation Cir
709     38343             33 Constellation Cir
710     38343                       10 Hull Cv
711     38343                       10 Hull Cv
721     67505                   900 E 11th Ave
722     67505                   902 E 11th Ave
723     67505                   321 W 10th Ave
724     67505                    723 E 9th Ave
725     67505                   1402 E 5th Ave
727     67505                  512 N Poplar St
728     67505                   1612 W 4th Ave
729     67505               1415 N Prairie Ave
731     67505                   1304 E 5th Ave
732     67505                 1509 N Monroe St
734     67505                     14 E 2nd Ave
735     67505                        401 E Ave
736     67505                        401 E Ave
737     67501                   900 E 11th Ave
738     67501                   902 E 11th Ave
739     67501                   321 W 10th Ave
740     67501                    723 E 9th Ave
741     67501                   1402 E 5th Ave
742     67501                  512 N Poplar St
743     67501                   1612 W 4th Ave
744     67501               1415 N Prairie Ave
745     67501                   1304 E 5th Ave
746     67501                 1509 N Monroe St
747     67501                     14 E 2nd Ave
748     67501                        401 E Ave
749     67501                        401 E Ave
771     32254                   920 Ontario St
772     32254                    2853 W 1st St
773     32254                   3327 Dignan St
774     32254                  1091 Detroit St
775     32254            3510 Bougainvillea St
776     32254                 222 Shortreed St
777     32254                    1094 Hood Ave
778     32254                  1055 Melson Ave
779     32254            414 Willow Branch Ave
780     32254                    2863 W 9th St
781     32254                   3228 Dignan St
782     32254                   3055 Dignan St
783     32254                  849 Superior St
784     32254               2940 Fitzgerald St
785     32254                3359 Columbus Ave
786     32254            3055 Dignan St Unit 1
787     32254               3246 Warrington St
788     32254                  970 Douglas Cir
789     32254                   3048 W 19th St
790     32254                1073 Seminole Ave
791     32254                   920 Ontario St
792     32254                    2853 W 1st St
793     32254                   3327 Dignan St
794     32254                  1091 Detroit St
795     32254            3510 Bougainvillea St
796     32254                 222 Shortreed St
797     32254                    1094 Hood Ave
798     32254                  1055 Melson Ave
799     32254            414 Willow Branch Ave
800     32254                    2863 W 9th St
801     32254                   3228 Dignan St
802     32254                   3055 Dignan St
803     32254                  849 Superior St
804     32254               2940 Fitzgerald St
805     32254                3359 Columbus Ave
806     32254            3055 Dignan St Unit 1
807     32254               3246 Warrington St
808     32254                  970 Douglas Cir
809     32254                   3048 W 19th St
810     32254                1073 Seminole Ave
812     66106                 2312 Victoria Dr
813     66106                 2312 Victoria Dr
814     66106                   1425 S 55th St
815     66106                   1425 S 55th St
821     66106                   7265 Forest Dr
822     66106                   7265 Forest Dr
828     46947                  3405 Lindsay Dr
829     46947                  3405 Lindsay Dr
868     28112                  900 E Sunset Dr
869     28112                  900 E Sunset Dr
873     72114                  5 Esplanade Cir
874     72114                  5 Esplanade Cir
875     72114                 75 Riverfront Dr
876     72114                 75 Riverfront Dr
877     72114              630 W Riverfront Dr
878     72114              630 W Riverfront Dr
914     72114                   1540 W 10th St
915     72114                   1540 W 10th St
922     72114  630 Riverfront Park Dr Unit 123
923     72114                    824 W 25th St
924     72114                 1618 N Locust St
925     72114                    2908 E 2nd St
926     72114              1405 W Long 17th St
927     72114             115 College Park Cir
928     72114                    1822 Maple St
929     72114                4295 Shadcrest Cv
930     72114                     1507 Nona St
931     72114                     1507 Nona St
932     72114    630 W Riverfront Dr Unit 201B
933     72114      1922 W Short 17th St Unit 2
934     72114                      1004 N D St
935     72114                   1513 Marion St
936     72114              1603 W Long 17th St
937     72114          1101 Dorothy Rodham Way
938     72114                   1235 W 10th St
939     72114  630 Riverfront Park Dr Unit 123
940     72114                    824 W 25th St
941     72114                 1618 N Locust St
942     72114                    2908 E 2nd St
943     72114              1405 W Long 17th St
944     72114             115 College Park Cir
945     72114                    1822 Maple St
946     72114                4295 Shadcrest Cv
947     72114                     1507 Nona St
948     72114                     1507 Nona St
949     72114    630 W Riverfront Dr Unit 201B
950     72114      1922 W Short 17th St Unit 2
951     72114                      1004 N D St
952     72114                   1513 Marion St
953     72114              1603 W Long 17th St
954     72114          1101 Dorothy Rodham Way
955     72114                   1235 W 10th St
958     17557                  150 Ashlea Gdns
959     17557                  150 Ashlea Gdns
964     54961                    1508 Cedar St
965     54961                    1508 Cedar St
971     76180                 4401 Glenview Ct
972     76180                 4401 Glenview Ct
973     76180                  6100 Ashbury St
974     76180                  6100 Ashbury St
975     76180                 6021 Parker Blvd
976     76180                 6021 Parker Blvd
979     76180           8341 Emerald Hills Way
980     76180           8341 Emerald Hills Way
981     76180             6309 Iron Horse Blvd
982     76180             6309 Iron Horse Blvd
983     76180             6715 Buenos Aires Dr
984     76180             6715 Buenos Aires Dr
985     76180             6490 Iron Horse Blvd
986     76180             6490 Iron Horse Blvd
987     76180                 6901 NE Loop 820
988     76180                 6901 NE Loop 820
990     76180                9012 Courtenay St
991     76180                9012 Courtenay St
992     76180                     8515 26 Blvd
993     76180                     8515 26 Blvd
994     76180             4201 City Point Dr W
995     76180             4201 City Point Dr W
996     76180                8601 Ice House Dr
997     76180                8601 Ice House Dr
998     76180                8359 N Harwood Rd
999     76180                8359 N Harwood Rd
1000    76180                 6250 Rosewood Dr
1001    76180                 6250 Rosewood Dr
1002    76180             6424 Iron Horse Blvd
1003    76180             6424 Iron Horse Blvd
1004    76180                 6100 Browning Dr
1005    76180                 6100 Browning Dr
1013    76180                  1598 Weyland Dr
1014    76180                  1598 Weyland Dr
1053    76180                 6021 Parker Blvd
1054    76180                 6021 Parker Blvd
1058    76180                  8500 Harwood Rd
1059    76180                  8500 Harwood Rd
1077    76180               7731 N College Cir
1078    76180               7731 N College Cir
1080    76180                8500 Harwood Rd N
1081    76180                8500 Harwood Rd N
1083    76180                  1601 Weyland Dr
1084    76180                  1601 Weyland Dr
1086    76180                  5521 Davis Blvd
1087    76180                  5521 Davis Blvd
1090    76180                8515 Boulevard 26
1091    76180                8515 Boulevard 26
1153    38261         811 W Reelfoot Ave Lot 1
1154    38261         811 W Reelfoot Ave Lot 1
1155    38261                    1732 Stone St
1156    38261                    1732 Stone St
1157    68137                 5410 S 111th Plz
1158    68137                 5410 S 111th Plz
1161    68137              12775 Woodcrest Plz
1162    68137              12775 Woodcrest Plz
1164    68137                    12230 Anne St
1165    68137                    12230 Anne St
1169    68137                 6816 S 137th Plz
1170    68137                 6816 S 137th Plz
1172    68137                       11025 M St
1173    68137                       11025 M St
1175    68137                10985 Roxbury Plz
1176    68137                10985 Roxbury Plz

So there's a lot of address duplicates because of the way I wrote the code to capture both high and low values for each rental unit that listed a range. So I won't remove them.

In [408]:
# Now I'm going to count unique values in each object column

df_rr['Address2'].value_counts()

North Richland Hills, TX 76180    181
Chicago, IL 60641                 133
Fayetteville, AR 72704            105
Seguin, TX 78155                   98
North Little Rock, AR 72114        81
Springdale, AR 72764               70
Cumming, GA 30040                  67
Sherman, TX 75090                  66
Fort Smith, AR 72901               65
Jacksonville, FL 32254             61
Easley, SC 29640                   50
Haltom City, TX 76117              41
Waterloo, IA 50703                 33
Dallas, TX 75237                   31
Goodlettsville, TN 37072           31
Bowling Green, KY 42101            29
Hutchinson, KS 67501               26
Omaha, NE 68137                    22
Rogers, AR 72756                   22
Warren, MI 48091                   22
Jackson, MS 39204                  21
Monroe, NC 28112                   21
Sanford, NC 27332                  20
Rome, GA 30161                     20
Emporia, KS 66801                  20
Houston, TX 77029                  17
Vineland, NJ 08360                 15
Shelbyville, TN 37160              14
Kansas City, KS 66106              12
Enid, OK 73701                     12
Council Bluffs, IA 51501           12
Cincinnati, OH 45246               11
Jackson, TN 38305                  11
Rainbow City, AL 35906              9
San Lorenzo, CA 94580               8
Portland, ME 04102                  8
Vicksburg, MS 39183                 7
Traverse City, MI 49684             7
New Holland, PA 17557               6
Logansport, IN 46947                6
Saint Joseph, MO 64507              5
Amarillo, TX 79108                  5
Lincoln, NE 68507                   5
Green Forest, AR 72638              4
New London, WI 54961                4
Amherst, OH 44001                   4
Sedalia, MO 65301                   4
Union City, TN 38261                4
Bella Vista, AR 72715               3
Ashland, CA 94580                   3
Lincoln, NE 68505                   3
Broken Bow, OK 74728                3
Russellville, AR 72802              3
Perry, IA 50220                     3
Storm Lake, IA 50588                2
Pine Bluff, AR 71602                2
Newbern, TN 38059                   2
Hanceville, AL 35077                2
Medina, TN 38355                    2
Little Rock, AR 72114               2
Ringgold, VA 24586                  2
Carthage, TX 75633                  2
Caseyville, IL 62232                2
Forest Park, OH 45246               2
Catawba County, NC 28610            2
Newport, KY 41071                   2
Cold Spring, KY 41076               2
Zeeland, MI 49464                   2
Hutchinson, KS 67502                2
North Richland Hills, TX 76117      2
Albertville, AL 35950               2
Springdale, OH 45246                1
Fayetteville, AR 72764              1
Blountsville, AL 35031              1
Plum Springs, KY 42101              1
Fort Worth, TX 76180                1
Port Byron, IL 61275                1
Vernon, TX 76384                    1
Center, TX 75935                    1
Georgetown, GA 39854                1
Dexter, MO 63841                    1
Tom Bean, TX 75090                  1
White Hall, AR 71602                1
Monett, MO 65708                    1
South Sioux City, NE 68776          1
Fort Worth, TX 76117                1
Dardanelle, AR 72834                1
Corydon, IN 47112                   1
Name: Address2, dtype: int64

In [412]:
df_rr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1599 entries, 0 to 1609
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   TysonZip  1599 non-null   object
 1   Address1  1595 non-null   object
 2   Address2  1595 non-null   object
 3   Style     1599 non-null   object
 4   Price     1599 non-null   int64
 5   Beds      1597 non-null   object
 6   Baths     1594 non-null   object
 7   Sqft      1409 non-null   float64
 8   City      1595 non-null   object
 9   State     1595 non-null   object
 10  Zip       1595 non-null   object
dtypes: float64(1), int64(1), object(9)
memory usage: 149.9+ KB

In [413]:
# Now I'm going to count unique values in each object column

df_rr['City'].value_counts()

North Richland Hills    183
Chicago                 133
Fayetteville            106
Seguin                   98
North Little Rock        81
Springdale               71
Cumming                  67
Sherman                  66
Fort Smith               65
Jacksonville             61
Easley                   50
Haltom City              41
Waterloo                 33
Jackson                  32
Goodlettsville           31
Dallas                   31
Bowling Green            29
Hutchinson               28
Rogers                   22
Omaha                    22
Warren                   22
Monroe                   21
Sanford                  20
Rome                     20
Emporia                  20
Houston                  17
Vineland                 15
Shelbyville              14
Kansas City              12
Enid                     12
Council Bluffs           12
Cincinnati               11
Rainbow City              9
Portland                  8
Lincoln                   8
San Lorenzo               8
Traverse City             7
Vicksburg                 7
Logansport                6
New Holland               6
Amarillo                  5
Saint Joseph              5
Sedalia                   4
Union City                4
New London                4
Green Forest              4
Amherst                   4
Perry                     3
Bella Vista               3
Ashland                   3
Broken Bow                3
Russellville              3
Carthage                  2
Hanceville                2
Pine Bluff                2
Caseyville                2
Storm Lake                2
Newbern                   2
Zeeland                   2
Albertville               2
Little Rock               2
Ringgold                  2
Forest Park               2
Catawba County            2
Newport                   2
Medina                    2
Fort Worth                2
Cold Spring               2
Dexter                    1
South Sioux City          1
Georgetown                1
Corydon                   1
Vernon                    1
Blountsville              1
Tom Bean                  1
White Hall                1
Plum Springs              1
Port Byron                1
Monett                    1
Center                    1
Dardanelle                1
Name: City, dtype: int64

In [414]:
# Now I'm going to count unique values in each object column

df_rr['State'].value_counts()

TX    448
AR    360
IL    136
GA     88
TN     64
FL     61
KS     60
SC     50
IA     50
NC     43
KY     34
MI     31
NE     31
MS     28
OH     18
OK     15
NJ     15
AL     14
MO     11
CA     11
ME      8
IN      7
PA      6
WI      4
VA      2
Name: State, dtype: int64

In [415]:
# Now I'm going to count unique values in each object column

df_rr['Zip'].value_counts()

76180    182
60641    133
72704    105
78155     98
72114     83
72764     71
75090     67
30040     67
72901     65
32254     61
29640     50
76117     44
50703     33
37072     31
75237     31
42101     30
67501     26
68137     22
72756     22
48091     22
28112     21
39204     21
27332     20
30161     20
66801     20
77029     17
08360     15
45246     14
37160     14
73701     12
51501     12
66106     12
94580     11
38305     11
35906      9
04102      8
39183      7
49684      7
46947      6
17557      6
79108      5
68507      5
64507      5
44001      4
54961      4
72638      4
38261      4
65301      4
72715      3
71602      3
68505      3
72802      3
74728      3
50220      3
35077      2
50588      2
38355      2
38059      2
24586      2
75633      2
62232      2
28610      2
41071      2
41076      2
49464      2
35950      2
67502      2
72834      1
68776      1
65708      1
63841      1
39854      1
76384      1
75935      1
61275      1
35031      1
47112      1
Name: Zip, dtype: int64

In [420]:
df_rr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1599 entries, 0 to 1609
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   TysonZip  1599 non-null   object
 1   Address1  1595 non-null   object
 2   Address2  1595 non-null   object
 3   Style     1599 non-null   object
 4   Price     1599 non-null   int64
 5   Beds      1597 non-null   object
 6   Baths     1594 non-null   object
 7   Sqft      1409 non-null   float64
 8   City      1595 non-null   object
 9   State     1595 non-null   object
 10  Zip       1595 non-null   object
dtypes: float64(1), int64(1), object(9)
memory usage: 149.9+ KB

In [417]:
# Time to export the data and wrap up this lesson

df_rr.to_csv(os.path.join(path, 'Data', 'Cleaned', 'Realtor_Scraped_Rental.csv'), index=False)